### ISSUE TITLE
[Major Bug] DISAPEAR DINO?

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#100]
_Originally written by **YukiNeko | 76561198041761378**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600X Six-Core Processor           
Vendor: AuthenticAMD
GPU Brand: AMD Radeon RX 5700
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

Hello, my pteradon just disapeared from menu section withouth being actualy killed or anything 0_0 its just not there anymore, and its so confusing 0_0

**Comment by Thy-Vipe** [comment]
Should be fixed - closing until further notice.
