### ISSUE TITLE
[Quality of life] Lurd Teeth

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1014]
_Originally written by **Gling | 76561198120397137**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

Detach entirely and flost in space when holding eggs

**Comment by Trip-Trap** [comment]
will get fixed with remodel
