### ISSUE TITLE
[Enhancement] Make AP's super far away trees disappear

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#102]
_Originally written by **Detestation | 76561198019845935**_
Game Version: 1.1.942

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Dinosaur** 
Map: Ancestral_Plains

AP's super far away trees should disappear to make the game run smoother
https://cdn.discordapp.com/attachments/675807658271309825/722573471925927957/unknown.png

**Comment by Predatoria** [comment]
Vipe did this on AP and it's now on live.  I'm going to close this.
