### ISSUE TITLE
[Bug] Tesselation option does not work

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#103]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.942

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Map view** 
Map: Ancestral_Plains

*Expected Results:* For tesselation to smooth out terrain.
*Actual Results:* Enabling or disabling tesselation in option doesn't change anything.
*Replication:* Spawn in to get a good view of the map. Go into escape menu > options and disable&enable tesselation. Note that nothing will happen.

https://cdn.discordapp.com/attachments/658770584095817739/722574512113320026/unknown.png

**Comment by Thy-Vipe** [comment]
Tesselation is currently disabled on all materials for performance reasons. Got to get the game to run overall smoothly before going to the fancy stuff.  :p
