### ISSUE TITLE
[Bug] Creature spawning in wrong location

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#104]
_Originally written by **Ghostnoodles | 76561198392484240**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Creating a dinosaur** 
Map: Rival_Shores

When in the creature select menu, if you click on aquatic and choose a dinosaur and rapidly click to herbivore/carnivore without selecting a new dinosaur, you spawn in as the prior selected aquatic. Thus being stuck on land as the aquatic. It works the other reverse as well; carnivore/herbivore in water etc.

**Comment by cleafspear** [comment]
this issue appears to no longer occur on branch dev1.1.1049
