### ISSUE TITLE
[Quality of life] hhelp

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10434]
_Originally written by **boutgeneral | 76561198101240071**_
Game Version: 1.2.0053

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **IM MUTED HELP** 
Map: Islatitania

i got muted please help         HHELP HELP HELP HELP HELP

**Comment by CeciliaSE** [comment]
With no coordinates or other context clues, this issue cannot be tested for.
