### ISSUE TITLE
[Quality of life] kill me rex

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10445]
_Originally written by **Yoshi_pl | 76561198885236487**_
Game Version: 1.2.0053

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **kill** 
Map: DM_Caldera_Canvas

rex kill me me pls ds rex a frends
Location: X=-64080.000 Y=45832.000 Z=4834.771

**Comment by Skyedrago** [comment]
Player report, not a bug
