### ISSUE TITLE
[Quality of life] kill me and qxit

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10446]
_Originally written by **Yoshi_pl | 76561198885236487**_
Game Version: 1.2.0053

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **killning** 
Map: DM_Caldera_Canvas

w9sh kill spawn me and qxit and kill me location big humans

**Comment by CeciliaSE** [comment]
Unfortunately, I need more information than this issue provides. Issues submitted by the same account hold location coordinates, and I will investigate them to the best of my abilities as soon as we get a Caldera canvas up and running.
