### ISSUE TITLE
[Quality of life] pwl27 kill alll pleyer

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10447]
_Originally written by **Yoshi_pl | 76561198885236487**_
Game Version: 1.2.0053

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **killning** 
Map: DM_Caldera_Canvas

pwl 27 kill all pleyer not end :(

**Comment by Skyedrago** [comment]
Player report, not a bug
