### ISSUE TITLE
[Quality of life] snapp kill

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10466]
_Originally written by **Yoshi_pl | 76561198885236487**_
Game Version: 1.2.0053

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: DM_Caldera_Canvas

snap kill me a sapwn
Location: X=-42479.738 Y=9631.860 Z=5581.576
name:snapp ><

**Comment by Skyedrago** [comment]
Player report, not a bug
