### ISSUE TITLE
[Quality of life] kotan

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10470]
_Originally written by **Yoshi_pl | 76561198885236487**_
Game Version: 1.2.0053

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: DM_Caldera_Canvas

kotan kill me a grup
Location: X=-31968.137 Y=10462.303 Z=2020.647

**Comment by Skyedrago** [comment]
https://github.com/Thy-Vipe/BeastsOfBermuda-issues/issues/10471 Same as this one
