### ISSUE TITLE
[Quality of life] cukie

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10503]
_Originally written by **Yoshi_pl | 76561198885236487**_
Game Version: 1.2.0084

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: DM_Caldera_Canvas

Location: X=-55925.312 Y=32741.098 Z=5893.659
cukie report me a go toportal me 1.2

**Comment by Skyedrago** [comment]
Seems to be a player report? Possibly not a bug
