### ISSUE TITLE
[Enhancement] RESKIN PACHY

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10532]
_Originally written by **Triton | 76561197969239706**_
Game Version: 1.2.0084

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores_Canvas

Please Reskin and BUFF pachy! Please redue the pachy look, and revise its talent tree. This pachy has been nurfed to the point where its unplayable.

**Comment by SilverWing430** [comment]
Not a bug
