### ISSUE TITLE
[Quality of life] maciej 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10559]
_Originally written by **Yoshi_pl | 76561198885236487**_
Game Version: 1.2.0084

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Islatitania

 rev maciej pls 540 rev maciej pls.  rex kill maciej rex cheter

Location: X=160419.250 Y=471190.812 Z=-6381.138

**Comment by SilverWing430** [comment]
Not a bug
