### ISSUE TITLE
[Bug] Cant text in chat ???????? WTF Do i write even more here Fuuuu saik

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10553]
_Originally written by **??4x | 76561197998058396**_
Game Version: 1.2.0084

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3600 6-Core Processor              
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1660 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **I`m muted from chat don´t know why** 
Map: Islatitania

Freakin unmute, btw nice report stuff 
that dont work and ppl get muted and if u stuck u cant contact an admin smart !!

**Comment by SilverWing430** [comment]
Not a bug
