### ISSUE TITLE
[Quality of life] und body

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10560]
_Originally written by **maciejborkowski09 | 76561199063493819**_
Game Version: 1.2.0084

*===== System Specs =====
CPU Brand: 13th Gen Intel(R) Core(TM) i5-13600KF
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 3080
GPU Driver Info: Unknown
Num CPU Cores: 14
===================*
Map: Islatitania

j was sit next 

Location: X=169988.531 Y=440493.031 Z=-6810.702 and j have body rex call 33 and j call 4. 3sek later this rex kill mee but was have body j was 2.1 wieh

**Comment by SilverWing430** [comment]
Not a bug
