### ISSUE TITLE
[Quality of life] watching people self feed

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10573]
_Originally written by **OtakuSenpai | 76561199139264391**_
Game Version: 1.2.0084

*===== System Specs =====
CPU Brand: AMD Ryzen 9 5900HX with Radeon Graphics        
Vendor: AuthenticAMD
GPU Brand: AMD Radeon(TM) Graphics
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **apa** 
Map: Islatitania

self feeding at events red acro apa shiny sai and krono 2;11 south cali time got recording they logged after i came up on global and they are still doing it not really fair
Location: was at ravine by the bridge and shrine ;

**Comment by SilverWing430** [comment]
Not a bug report
