### ISSUE TITLE
[Quality of life] Settings problem

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1058]
_Originally written by **0verload | 76561198318156808**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

when i change the sound/ volume of things it doesnt change whatsoever

**Comment by Trip-Trap** [comment]
*probably* fixed
