### ISSUE TITLE
[Quality of life] aplle kill

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10597]
_Originally written by **Yoshi_pl | 76561198885236487**_
Game Version: 1.2.0084

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Islatitania

aplle kill me not 1 min respawn me pls my grow my gorw: 1.286 rex

Location: X=88287.984 Y=460105.750 Z=-12611.478 is not dotal good location

**Comment by xMeelo** [comment]
..Not a bug
