### ISSUE TITLE
[Quality of life] Blur when returning to main menu from server

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#106]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.942

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Main Menu** 
Map: Ancestral_Plains

*Expected Results:* Main menu looking the same when returning from a server.
*Actual Results:* The main menu will have a DoF blur when returning from a server.
*Replication:* Return to the main menu from the server.

https://cdn.discordapp.com/attachments/559471669853421579/722588396891013171/unknown.png

**Comment by Predatoria** [comment]
I cannot get this to happen.  Are there any additional steps?  I tried returning to the main menu while underwater and it looked normal to me.

**Comment by Trip-Trap** [comment]
Doesn't happen to me anymore either.
