### ISSUE TITLE
[Enhancement] geting reamoved from group

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10614]
_Originally written by **Shaggy | 76561198017763075**_
Game Version: 1.2.0084

*===== System Specs =====
CPU Brand: AMD Ryzen 5 5600G with Radeon Graphics         
Vendor: AuthenticAMD
GPU Brand: Radeon RX 570 Series
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **i geting reamoved form the group but i was not in a group in the first place.** 
Map: DM_Caldera_Canvas

i was playing solo and some one ienvted me and then i got reamoved form the group and it keep reamoving me and this apa came and gus wip like so meny times at ones and idk who this apa is but it seem they are hacker or admin idk but they keep targeting me other in the server are not geting reamoved but i am only me so im geting targeted like amdin targeted or hacker targeted but idk who they are and idk what to do with the reamoving thing.

**Comment by Skyedrago** [comment]
Not a bug
