### ISSUE TITLE
[Quality of life] bloqué dans une maison

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10615]
_Originally written by **Wanhedda-Prime | 76561198371612464**_
Game Version: 1.2.0084

*===== System Specs =====
CPU Brand: AMD Ryzen 9 5900X 12-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 3060 Ti
GPU Driver Info: Unknown
Num CPU Cores: 12
===================*
Map: Islatitania

bonjour, mon dinosaure est bloqué dans une maison

**Comment by xMeelo** [comment]
User says their dinosaur is stuck in a house, no info on coords
