### ISSUE TITLE
[Severe Bug] Rusian1104975

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10622]
_Originally written by **Ruslan11041997 | 76561198286512626**_
Game Version: 1.2.0084

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **pls join me** 
Map: Rival_Shores

*Expected Results:* 10
*Actual Results:* 36
*Replication:* 2
Location: X=-71358.969 Y=68982.867 Z=11019.084

**Comment by SilverWing430** [comment]
This is not a Bug Report?

**Comment by IPvPeedMyself** [comment]
Not enough information.
