### ISSUE TITLE
[Bug] grow me

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10626]
_Originally written by **Yoshi_pl | 76561198885236487**_
Game Version: 1.2.0084

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: DM_Caldera_Canvas

im restar dino 1.7 im not grow.
plase me grow 1.7

**Comment by xMeelo** [comment]
Not a bug, and/or not enough information if bug
