### ISSUE TITLE
[Quality of life] Rat egg incubation

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10648]
_Originally written by **[Draco]BioAddict33 | 76561199508484689**_
Game Version: 1.2.0118

*===== System Specs =====
CPU Brand: 12th Gen Intel(R) Core(TM) i7-12700H
Vendor: GenuineIntel
GPU Brand: Intel(R) Iris(R) Xe Graphics
GPU Driver Info: Unknown
Num CPU Cores: 14
===================*
Map: Rival_Shores

megarats need to be fixed bad theyre egg incubation is awful and can hardly incubate an egg when obviously sitting on the nest even with 2 on it still hardly works please fix

**Comment by Skyedrago** [comment]
Likely a hitbox issue

**Comment by BoBAdministration** [comment]
fixed
