### ISSUE TITLE
[Enhancement] иван иванович петров

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10683]
_Originally written by **Ruslan11041997 | 76561198286512626**_
Game Version: 1.2.0123

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **14:12** 
Map: Rival_Shores_Canvas

*Expected Results:*
*Actual Results:* 
*Replication:* 
Location: X=78637.305 Y=226083.297 Z=4892.582

**Comment by SilverWing430** [comment]
not a bug?
