### ISSUE TITLE
[Bug] Speedhack / Faster game command > t.OverrideFPS 1

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10696]
_Originally written by **symbolic | 76561199226938563**_
Game Version: 1.2.0123

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

Speedhack if press f2 and select t.OverrideFPS and choose a number between 1-100 will gain u a faster game (Works without admin and any permissions)

**Comment by Undercooked-Mothman** [comment]
noted

**Comment by BoBAdministration** [comment]
Fixed
