### ISSUE TITLE
[Bug] my death id 407 help me

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10691]
_Originally written by **Cat | 76561198132120981**_
Game Version: 1.2.0123

*===== System Specs =====
CPU Brand: 13th Gen Intel(R) Core(TM) i7-13620H
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics
GPU Driver Info: Unknown
Num CPU Cores: 10
===================*
Context: **my death id 407** 
Map: Rival_Shores

my death id 407 help me
Location: X=-112513.703 Y=65250.031 Z=5997.467

**Comment by Skyedrago** [comment]
Likely death by another player since no issues here either
