### ISSUE TITLE
[Major Bug] my  death id 793

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10692]
_Originally written by **Cat | 76561198132120981**_
Game Version: 1.2.0123

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2060
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **my  death id 793** 
Map: Rival_Shores

my  death id 793

Location: X=-114772.945 Y=69452.125 Z=5984.686

**Comment by Skyedrago** [comment]
Seems to be another death by another player - no issues with terrain
