### ISSUE TITLE
[Major Bug] death id 927

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10693]
_Originally written by **Cat | 76561198132120981**_
Game Version: 1.2.0123

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2060
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **death id 927** 
Map: Rival_Shores

death id 927
Location: X=-79322.867 Y=70371.406 Z=8708.854
Location: X=-79322.867 Y=70371.406 Z=8708.854

**Comment by Skyedrago** [comment]
Possibly a kill by another player? Seems to be no issue with terrain here
