### ISSUE TITLE
[Severe Bug] People losing dead dinos out of their slots

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#107]
_Originally written by **Flammi | 76561198213845769**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: AMD FX(tm)-8300 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1050
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

It's not something i experienced myself, but some people just lose their dead dinos out of their slots and they are really lost as we cannot even see them on the revive list. They just disappear for no reason.

**Comment by Thy-Vipe** [comment]
Should be fixed - closing until further notice.
