### ISSUE TITLE
[Quality of life] killing

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10713]
_Originally written by **???Shadownigth??? | 76561199114215539**_
Game Version: 1.2.0164

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3600 6-Core Processor              
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Ancestral_Plains

kill me in grup i dont know why

**Comment by Undercooked-Mothman** [comment]
not a bug report
