### ISSUE TITLE
[Quality of life] kiler

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10714]
_Originally written by **Yoshi_pl | 76561198885236487**_
Game Version: 1.2.0164

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

Mummy kill shadow night in grup i dot know why
name killer : MummyMilkers
name deds pleyer:*shadownight*

**Comment by Undercooked-Mothman** [comment]
not a bug report
