### ISSUE TITLE
[Bug] Crystal grabbing bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1073]
_Originally written by **Axey Waxey | 76561199070071869**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD Ryzen 7 2700 Eight-Core Processor          
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2070
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Beasts of Bermuda? on a Rex in a  cave** 
Map: Rival_Shores

Every time i pick up Orange AND Blue crystals, then set them down, the blue crystals disappear completely.

**Comment by Trip-Trap** [comment]
#659
