### ISSUE TITLE
[Bug] Sai Eating Animation Only Plays While Moving

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10797]
_Originally written by **Specs+ | 76561199534778308**_
Game Version: 1.2.0198

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Saichania, Freeroam Server, Rival Shores** 
Map: Rival_Shores_Canvas

*Expected Results:* Saichania plays its eating animation when a player holds down their interact/eat button.
*Actual Results:* Saichania does not play its eating animation only when standing still. Eating animations still play when player walks or sprints.
*Replication:*
1. Select Saichania.
2. Use the interact key to eat while moving and while not moving. Should notice that Saichania does not play the eating animation while standing still.

**Comment by Undercooked-Mothman** [comment]
known bug

**Comment by BoBAdministration** [comment]
Fixed
