### ISSUE TITLE
[Quality of life] raptor rb

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10791]
_Originally written by **Yoshi_pl | 76561198885236487**_
Game Version: 1.2.0198

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Islatitania

Location: X=161579.078 Y=466524.219 Z=-4802.576.i kill megarap he is angry and rep me i kill him he 2 call im  3 call,
he call to me im banend.

**Comment by Undercooked-Mothman** [comment]
not a bug report
