### ISSUE TITLE
[Bug] Dino deleted from slot after dying

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#108]
_Originally written by **Aspen ??? | 76561198375371611**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **As a para** 
Map: Rival_Shores

So I was killed from a rulebreak and after I went to creature select, I had learned the death was never saved, instead there was an empty slot in the place of where the said dino used to be. So when the admin tried to revive my 1.160 para, there was no death for that para shown. Please fix this as it is VERY frustrating.

**Comment by Thy-Vipe** [comment]
Should be fixed - closing until further notice.
