### ISSUE TITLE
[Enhancement] Testing testing

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10810]
_Originally written by **Undercooked Mothman | 76561198189298150**_
Game Version: 1.2.0211

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **goopball** 
Map: Islatitania

*Expected Results:*  test
*Actual Results:*  test
*Replication:*  test

**Comment by Undercooked-Mothman** [comment]
not important! just a test
