### ISSUE TITLE
[Bug] ASDASDASDASDASDASDAD

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10812]
_Originally written by **Detestation | 76561198019845935**_
Game Version: 1.2.0214

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **ASDASDASDASDASDASDASDASD** 
Map: Islatitania

*Expected Results:* ASDASDASDASDASDAS
*Actual Results:* ASDASDASDASDA
*Replication:* ASDASDASDASDASDASDAD

Location: X=151425.875 Y=97867.055 Z=-4608.950

**Comment by Zelryn** [comment]
No information
