### ISSUE TITLE
[Bug] ASDASDASDASDASDASDASDASD

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10819]
_Originally written by **PIE_USER | 258**_
Game Version: 1.2.0214

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **ASDASDASDASDASDADSADASDASDASDASDASDASD** 
Map: UEDPIE_1_BB_Test_Map

*Expected Results:* ASDASDASDASDASDASDASDASD
*Actual Results:* ASDASDASDASDASDASDASDASD
*Replication:* ASDASDASDASDASDASDASDASD

Location: X=2845.000 Y=-45907.801 Z=147.535

**Comment by Zelryn** [comment]
No Information
