### ISSUE TITLE
[Bug] ASDASDASDASDASDASDASD

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10811]
_Originally written by **Detestation | 76561198019845935**_
Game Version: 1.2.0214

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **ASDASDASDASDASD** 
Map: Islatitania

*Expected Results:* ASDDDDD
*Actual Results:* ASDDDDDDDD
*Replication:* ASDDDADSDASDADASDASDASDASDASDASD

Location: X=127553.438 Y=86795.188 Z=-4611.726

**Comment by Zelryn** [comment]
No information
