### ISSUE TITLE
[Bug] Archelon shield not increasing 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10829]
_Originally written by **Diabell | 76561198037267915**_
Game Version: 1.2.0231

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Archelon** 
Map: Islatitania

Archelons shell shield does not increase at all from when i was a fresh spawn at 320 even with 1/3  armored shell

**Comment by Zelryn** [comment]
Known bug has now been fixed.
