### ISSUE TITLE
[Bug] ServerJoinBug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1082]
_Originally written by **???RapHead??? | 76561198387202626**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD Ryzen 5 1600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

When I Fail to Join a Server and it fails to join and i want to rejoin it says failed to join sever then if i try again it doesnt show any servers then i have to restart my game for every thing to be back to normal and i checked i have good internet connection

**Comment by cleafspear** [comment]
fixed in next patch
