### ISSUE TITLE
[Bug] Muted

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10835]
_Originally written by **QualityAssurance | 76561199073154738**_
Game Version: 1.2.0231

*===== System Specs =====
CPU Brand: AMD Ryzen 7 5800X 8-Core Processor             
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 3060
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **and i got muted** 
Map: Islatitania

i got permanentyl muted for some reason, i didnt do anything

**Comment by Undercooked-Mothman** [comment]
not a bug report
