### ISSUE TITLE
[Bug] Skill Tree bugging

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10845]
_Originally written by **Lady Zoe | 76561198123650168**_
Game Version: 1.2.0238

*===== System Specs =====
CPU Brand: AMD Ryzen 7 2700X Eight-Core Processor         
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Avter a revival and dont go away anymore** 
Map: Islatitania

my skill tree doesn't work anymore, i can't select anything anymore and the exhausted bite is selected individually without connection and i can't select anything anymore after a revival

**Comment by Undercooked-Mothman** [comment]
this is likely on an archelon and the person just needs a retalent to fix
