### ISSUE TITLE
[Major Bug] arche turtle tree bugged

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10858]
_Originally written by **Iggy | 76561198117662521**_
Game Version: 1.2.0264

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2070
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **archelon** 
Map: Islatitania

*Expected Results:* to add talent tree points, the hard head ability was recently added and the tree was not reset, leaving a empty spot
*Actual Results:* it only lets you add one talent point and not multiple when you normally would be able to, and immediately resets upon closing the talent tree
*Replication:* every single time you open the talent tree, on any turtle, and try to put in any talent. My friend was 2.2 before he died and now cannot use ANY talent points because it won't let him remove them.

**Comment by esvreel** [comment]
unable to recreate with fresh spawn archelons or archelons without survival points pre-update. need live branch archelon with preexisting survival talents.
