### ISSUE TITLE
[Major Bug] Talent Tree non-functional

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10859]
_Originally written by **Nilix | 76561198007141367**_
Game Version: 1.2.0264

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 3GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

Logged in after the update for the Coral Reef skin to a turtle that i had on Official 3, talents are non-responsive, cannot add points or anything

**Comment by esvreel** [comment]
unable to recreate with fresh spawn archelons or archelons without survival points pre-update. need live branch archelon with preexisting survival talents.

same issue as [10858](https://github.com/Predatoria/BeastsOfBermuda-issues/issues/10858)
