### ISSUE TITLE
[Bug] functions not working

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10850]
_Originally written by **TwinGuackiebirdie | 76561199210100934**_
Game Version: 1.2.0238

*===== System Specs =====
CPU Brand: 12th Gen Intel(R) Core(TM) i7-1255U
Vendor: GenuineIntel
GPU Brand: Intel(R) Iris(R) Xe Graphics
GPU Driver Info: Unknown
Num CPU Cores: 10
===================*
Context: **Apatosaurus** 
Map: Rival_Shores_Canvas

I was just playing normally and suddenly I could not sit, roar, or eat anything.

**Comment by Undercooked-Mothman** [comment]
not enough information to replicate
