### ISSUE TITLE
[Bug] broken talents

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10862]
_Originally written by **tulip | 76561199027816327**_
Game Version: 1.2.0264

*===== System Specs =====
CPU Brand: 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
Vendor: GenuineIntel
GPU Brand: Microsoft Basic Display Driver
GPU Driver Info: 
Num CPU Cores: 6
===================*
Map: Islatitania

idk how it happened but my talents arent working. for example, when i click on a talent that has, lets say, 2/3 points. the number of talents doesn't go down, it just stays the same. And, if I go out of the talents menu, then it resets it.

**Comment by Skyedrago** [comment]
Were they on an archelon that had their talents change? If that's the case not sure if this is a bug. Otherwise not enough info
