### ISSUE TITLE
[Bug] Turtle Talent point tree

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#10864]
_Originally written by **PikaSamurai | 76561198134439681**_
Game Version: 1.2.0264

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 3060
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Turtle, Offical server 6** 
Map: Rival_Shores

When i try to use my talent points(i have 5 right now) i can enter them but then once I close the tree they do not stay selected. I've tried restarting, uninstalling and reinstalling.

**Comment by Undercooked-Mothman** [comment]
this person probably needs to ask for a retalent
