### ISSUE TITLE
[Severe Bug] Logged on and my account was rolled back

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#109]
_Originally written by **SixTailedKitsune | 76561198356278196**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Beast of Bremuda on SunsetShores server** 
Map: Rival_Shores

my acro was .6 and when i logged in it was .1 the admins said there were no roll back on SunsetShores server

**Comment by Trip-Trap** [comment]
Conversation about a pachy that apparently always rolls back. 
https://discordapp.com/channels/280344667390738432/526080929660403713/722607439463317504

**Comment by Predatoria** [comment]
As of our latest patch, we've not seen any more reports of this and are marking bugs associated with loss of save data as fixed.
