### ISSUE TITLE
[Severe Bug] RessecutePlayer doesn't work

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#110]
_Originally written by **lunarpeach | 76561199015753475**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700T CPU @ 2.40GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Ancestral_Plains

My players doesn't have their dead dino in the slots and also I like an admin could not use ressecureplayer command

**Comment by Thy-Vipe** [comment]
Wrong command usage - and even then should be fixed. Closing until further notice.
