### ISSUE TITLE
[Quality of life] no gores spawning

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#111]
_Originally written by **littengamer1112 | 76561198992690060**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: AMD A8-7410 APU with AMD Radeon R5 Graphics    
Vendor: AuthenticAMD
GPU Brand: AMD Radeon R5
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **a velosiraptor** 
Map: Rival_Shores

owo who is this? i was playing vello on the rivail shores map and i looked alround the map
and the rexes were canibalizing there oun groups acros yeeting there brotheren off cliffs... 
it was some real CHOAS CHOAS

**Comment by Trip-Trap** [comment]
Bad Report
