### ISSUE TITLE
[Major Bug] Growth lose

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#112]
_Originally written by **Okumura | 76561198410650157**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand:         Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: AMD Radeon HD 7770 GHz Edition
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **today** 
Map: Rival_Shores

I logged into my Rex today and started growing. I was nearly 1. and after a server crash i was back to .45 even tho i was logged for an hour at around .7

**Comment by Thy-Vipe** [comment]
This one should be resolved, closing for now and marked as fixed until further notice.
