### ISSUE TITLE
[Major Bug] Satiation

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#113]
_Originally written by **Silvius | 76561198997784517**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **every map.** 
Map: Ancestral_Plains

There is a glitch or bug where I am unable to gain saitiation, no matter how many unjams or relog ins I do. I can be on for hours and it will not fix itself. At random it will work after not working for a while, but far and few in between. Thank you for your time and have a lovely day!

**Comment by Predatoria** [comment]
I suspect they were playing a carnivore and eating map carcasses.  Closing this.
