### ISSUE TITLE
[Bug] apato state issue when set to walk backwards and is swimming

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1132]
_Originally written by **Cleafspear | 76561198077984700**_
Game Version: 1.1.1040

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **apato** 
Map: Rival_Shores

*Expected Results:* when apato enters water while in the walk backwards state, the state should be either canceled on water enter or should continue swimming backwards instead of continuing foward
*Actual Results:* when the apato enters water while in the walk backwards state, it begins swimming foward, but when reaching a beach, it will nearly immedeatly resume walking backwards forcing it back into the swim state and viceversa. is very hard to get the timing right to release the walk backwards state.
*Replication:* as an apato in the walk backwards state, recive enough knockback to be launched into water deep enough to swim. swim to a beach with a fairly steep incline that can just be walked up, and attempt to exit the water. you will find yourself bouncing between the 2 states of walking backwards and swimming foward. you have to time hitting the crouch keybind during the extremely short time you are in the walk state before you begin swimming again

**Comment by Predatoria** [comment]
Should be fixed next tester patch
