### ISSUE TITLE
[Bug] water bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#114]
_Originally written by **Bulbertianus | 76561198987079439**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **dino** 
Map: Rival_Shores

At the snowmountain the lake overflows in storm in an ugly way.

Location: X=-192679.656 Y=47184.191 Z=37223.914

**Comment by Predatoria** [comment]
Couldn't reproduce it but maybe fixed.
