### ISSUE TITLE
[Major Bug] 1440p solution bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1146]
_Originally written by **SnippoCrunch | 76561198024180820**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD Ryzen 7 2700X Eight-Core Processor         
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Solution 1440p is buggy i cant mark talents i need to press on the right side of a talent to mark it** 
Map: Rival_Shores

Solution 1440p is buggy. ich muss neben den fenstern klicken das ich das fenster anklicken kann

**Comment by Trip-Trap** [comment]
The setres command is a known fix for this. Gonna close the issue
