### ISSUE TITLE
[Quality of life] playerlist

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#115]
_Originally written by **Bulbertianus | 76561198987079439**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **dino** 
Map: Rival_Shores

Names in playerlist is not in ABC order. Not sure if bug or just we can't see what order is in it.

**Comment by Predatoria** [comment]
Duplicate.  It's been fixed on tester.
