### ISSUE TITLE
[Bug] buggy cave entrance

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1153]
_Originally written by **Diabell | 76561198037267915**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

In the underwater cave  on the land bridge connecting desert and jungle of rival shores  there is a stretch of glitchy rock  that shows up going one way and is invisible coming through it  and acts as a solid object

**Comment by Predatoria** [comment]
It's part of the landscape mesh.  Set it to invisible here.  Should be fixed.
