### ISSUE TITLE
[Bug] velo climbing bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1156]
_Originally written by **B-moneyallday | 76561199082952751**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD Ryzen 7 1700 Eight-Core Processor          
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 980
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **as a velo** 
Map: Rival_Shores

i feel out of a tree while i was runing from the flood and got stuck in the climbing animation. i cant seem to sit or lay down, i also cna move as fast while runing on the ground. thank you and have a good day. B-moneyallday lol

**Comment by cleafspear** [comment]
This is fixed in the dev version
