### ISSUE TITLE
[Major Bug] fps drop from cave fog

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#116]
_Originally written by **Bulbertianus | 76561198987079439**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **any** 
Map: Rival_Shores

Location: X=-83473.539 Y=65378.418 Z=3298.745

In this cave at Rival Shores the mist/fog is growing once you enter the cave, and this grow not stops, eating up my FPS and boil my eggs over the GPU.

**Comment by cleafspear** [comment]
still active issue, confirmed on tester version 1.1.1049 with profile log to confirm. possible issue with the fog actor?

**Comment by cleafspear** [comment]
this appears tro of been tied to the lighting system instead of the fog. since the change if lenses flares as well is some of the diffusion.. it is a lot more stable.

**Comment by Predatoria** [comment]
Very likely lens flare-related.  I'm going to go ahead and close this, as I was unable to reproduce it and it's on an older map.
