### ISSUE TITLE
[Major Bug] Falling through map

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1162]
_Originally written by **Panda21 | 76561198368524998**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Velo ** 
Map: Rival_Shores

I was velo, jumped on rock, got stuck on climbing animation on the rock. So I pounced but then I just fell through the map and into the water and drowned.

**Comment by Trip-Trap** [comment]
Likely fixed with the "getting stuck in climbin animation" being fixed. Closing this for now
