### ISSUE TITLE
[Bug] under rocky area above water underwater when it isn't

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1170]
_Originally written by **Mutedmirth | 76561198046014700**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD A8-9600 RADEON R7, 10 COMPUTE CORES 4C+6G  
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **The Eastern Isles** 
Map: Rival_Shores

*Expected Results:*  To hide under a rocky area and as cave
*Actual Results:* Im swimming underwater and need air
*Replication:* Just go here as Ptera and move under the rock 

Location: X=235495.688 Y=191478.844 Z=4781.607

**Comment by Trip-Trap** [comment]
Watersource above reaches through the rock to a shelter beneath

**Comment by Predatoria** [comment]
Reduced Z scale of above water source.  Should be fixed.
