### ISSUE TITLE
[Quality of life] Jungle Biome - water tile mesh sticking through terrain mesh 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1184]
_Originally written by **Beenless | 76561198213334393**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Mega** 
Map: Rival_Shores

Found the drinkable water mesh poking out the hillside. 
Location: X=140736.703 Y=46974.492 Z=5020.382

**Comment by Trip-Trap** [comment]
Still on testers

**Comment by Predatoria** [comment]
Fixed in another report
