### ISSUE TITLE
[Enhancement] Lighting issue

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#119]
_Originally written by **Vipe | 76561197998584510**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: AMD Ryzen 9 3950X 16-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2080 Ti
GPU Driver Info: Unknown
Num CPU Cores: 16
===================*
Map: Rival_Shores

An other note. These plants at this location have bad billboard material that seemingly emits light.
Location: X=-119783.508 Y=45958.117 Z=4380.975

**Comment by cleafspear** [comment]
this issue appears to be resolved with the new lighting implemented with 1.1.1049, testing with different lighting settings showed that they appeared to no longer had the "glow" . confirmation will be needed.
