### ISSUE TITLE
[Severe Bug] blurry screen stuck

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#122]
_Originally written by **Bulbertianus | 76561198987079439**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **velo** 
Map: Rival_Shores

After being grabbed, then lose connection and reconnect ends as blurry screen like deep underwater.

**Comment by Thy-Vipe** [comment]
I likely fixed it, needs testing
