### ISSUE TITLE
[Bug] я появился на земле!

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1224]
_Originally written by **?????????????? ??: | 76561198115581468**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  
Vendor: AuthenticAMD
GPU Brand: AMD Radeon(TM) Vega 8 Graphics 
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

меня при выборе динозавра заспавнило на суше, как так?!!

**Comment by cleafspear** [comment]
translation:
[Bug] I appeared on earth!
When choosing a dinosaur, I spawned on land, how so ?!
