### ISSUE TITLE
[Major Bug] Several holes in map allow player to walk through

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1228]
_Originally written by **NibbleMeSoftly | 76561199023341594**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ptera** 
Map: Ancestral_Plains

There is a holole in map above the cave entrance in the wall. This hole allows players to walk to the inside of the map. Smaller hole is not far from large one that similarly allows the player to walk in to the map.

**Comment by Predatoria** [comment]
No coords so not sure where they're talking about.  Probably the one above the bridge
