### ISSUE TITLE
[Bug] Render Range Issue AP

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#124]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Render Issue** 
Map: Ancestral_Plains

The mountains on this island only show up super close.

Location: X=234190.422 Y=109773.750 Z=3757.826

**Comment by Thy-Vipe** [comment]
Should be fixed
