### ISSUE TITLE
[Quality of life] Ichthy sniff bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1242]
_Originally written by **Annie | 76561198077907050**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD FX(tm)-8350 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 960
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ichthyovenator** 
Map: Rival_Shores

I'm not too sure on whether or not this is supposed to happen, but ichthy cannot scent and swim at the same time. You must not be moving before you start smelling while underwater.

**Comment by cleafspear** [comment]
this is functional in 1.1.1049 closing as fixed in current patch
