### ISSUE TITLE
[Major Bug] se quedo bugeada el chat de registro de combate y me aparece en toda la pantalla

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1254]
_Originally written by **??? lucaslay | 76561198850448628**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 620
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Map: Rival_Shores

se quedo bugeada el chat de registro de combate y me aparece en toda la pantalla

**Comment by cleafspear** [comment]
translated:
[Major Bug] the combat registration chat was blocked and it appears on the whole screen
The combat registration chat was blocked and it appears on the whole screen
