### ISSUE TITLE
[Bug] Sturdy didnt work 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#126]
_Originally written by **Baron Rogue | 76561198024414406**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Velo** 
Map: Rival_Shores

A rex killed a pack member who was full hp and had 3/3 sturdy in one bite.

**Comment by Predatoria** [comment]
Rex bites can do so much damage it overrides sturdy, even at 3/3.  This likely was working as intended.
