### ISSUE TITLE
[Bug] self filling tunnels

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1262]
_Originally written by **Felix | 76561198128885210**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon (TM) RX 480 Graphics
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **ory** 
Map: Rival_Shores

i'm not sure if this is intentional since i've only started to play a few days ago but some burrows of mine just revert back to dirt even if i only left the burrow for 5 seconds to dump dirt. maybe it has to do with the amount of tunnel  one ory can have since i dug quite a lot of tunnel around in one area. it happened twice in different tunnel systems that are relatively close to each other.
 
Location: X=-219349.547 Y=-16092.445 Z=18483.029

**Comment by Predatoria** [comment]
Not sure what this person means.
