### ISSUE TITLE
[Quality of life] back from new

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#127]
_Originally written by **Bulbertianus | 76561198987079439**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

If you pick a new dino, but changed your mind, allow to go back to selectable dinos, to skip the - create new dino - kill it - part.

**Comment by Trip-Trap** [comment]
The new creature select will allow that.

**Comment by Trip-Trap** [comment]
Ah nm, they meant something different.

**Comment by cleafspear** [comment]
issue appears to be resolved on version 1.1.1029
