### ISSUE TITLE
[Bug] Water source floats

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1275]
_Originally written by **DukeBarradin | 76561198010573505**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 970
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

square water source floating underneath a tree
Location: X=140617.859 Y=46960.520 Z=4962.351

**Comment by Predatoria** [comment]
Fixed it in a different report
