### ISSUE TITLE
[Bug] My camera is stuck in my velo butt!

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#128]
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Map: Rival_Shores

Walking into this area by the waterfall in this mushroom kingdom cave has me stuck looking at my feathery cloaca. 
Location: X=109714.094 Y=84938.789 Z=4097.975

**Comment by Thy-Vipe** [comment]
Fixed it

**Comment by Trip-Trap** [comment]
There is a map hole there now.

**Comment by Predatoria** [comment]
Fixed it just now.  It was reported on another bug report as well.
