### ISSUE TITLE
[Bug] Blurry sky with 3/3 Aqua Affinity

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#129]
_Originally written by **TheRiversEdge | 76561198107871153**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: AMD FX(tm)-8320 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Terrestrial creature with 3/3 Aqua Affinity** 
Map: Rival_Shores

*Expected Results:* Sky remains the same after exiting water with 3/3 Aqua Affinity
*Actual Results:* After exiting water, sky will become blurry with 3/3 Aqua Affinity
*Replication:* Spawn as a terrestrial, non semi-aquatic/aquatic creature, put 3 points into Aqua Affinity, enter water, exit water and notice the blurry sky

**Comment by Predatoria** [comment]
+Fixed: underwater blur staying on screen when out of water

That was checked on tester.  I think this is a duplicate
