### ISSUE TITLE
[Bug] Water plain on Ptera Mt floods out of pond area during flood

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1297]
_Originally written by **notrook | 76561199019085966**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Pteranodon** 
Map: Rival_Shores

The water plain rises out of the pond area, causing the entire square plain to be visible for the player

**Comment by Predatoria** [comment]
Set both these little ponds to not be able to rise during floods
