### ISSUE TITLE
[Bug] sai reflect wont work

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1299]
_Originally written by **Gingervitus9100 | 76561198177698425**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3600 6-Core Processor              
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1660 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Ancestral_Plains

when i was fighting a sai their reflect worked but they could hit right through my reflect and it would not register

**Comment by Trip-Trap** [comment]
Likely lag issue
