### ISSUE TITLE
[Major Bug] Crowded Grouping...

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#130]
_Originally written by **RedVelvet | 76561198245495712**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Kronosaurus/Megalosaurus/Acrocanthosaurus** 
Map: Rival_Shores

A parent gets too far from their kids and gets the crowded group debuff. Even if the kids are hatchlings, the game acts as if they are adults when you get a certain range away from them. - This makes it very hard to go get food and leave them in caves, because you will get intimmed to death if you leave them. We have mostly noticed this on apexes due to their low packing limits.

**Comment by Predatoria** [comment]
Reproduced, fixed, and tested on PIE.

**Comment by Trip-Trap** [comment]
Likely fixed
