### ISSUE TITLE
[Bug] spot that velos can fall into and become trapped in

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#131]
_Originally written by **Cleafspear | 76561198077984700**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Velo** 
Map: Rival_Shores

location contains a spot that you can fall into while smaller then a 1.6 velo. you will fall into an inverted mesh spot and must be teleproted out
Location: X=-205377.453 Y=24724.557 Z=23284.830

**Comment by Predatoria** [comment]
Fixed
