### ISSUE TITLE
[Bug] Dew Claw new meg model

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#132]
_Originally written by **Gling | 76561198120397137**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

THe dew claws on the hind legs of the new adult meg model are detached and floating a short distance away from the feet, while in full rest/sleep position

**Comment by Predatoria** [comment]
This has been reported to Callie.  I noticed it last night.

**Comment by Predatoria** [comment]
I got an updated model from Callie and imported it into UE4.  I'm labeled this as potentially fixed.

**Comment by Trip-Trap** [comment]
Still an issue
![grafik](https://user-images.githubusercontent.com/56919683/85200357-047a1f80-b2f7-11ea-9621-10cb239649aa.png)

**Comment by Predatoria** [comment]
Should be fixed next patch!
