### ISSUE TITLE
[Bug] Stuck in hole

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1324]
_Originally written by **Annyon | 76561198045582487**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 3GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

*Expected Results:* 
*Actual Results:* 
*Replication:* 
Location: X=-94687.617 Y=57597.035 Z=10565.076

**Comment by Predatoria** [comment]
Filled hole with rock
