### ISSUE TITLE
[Bug] Crystal glitch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1327]
_Originally written by **Nokohi | 76561198314904698**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Rex** 
Map: Rival_Shores

When I pick up blue and red crystals the blue crystals turn to red crystals.

**Comment by Trip-Trap** [comment]
#659
