### ISSUE TITLE
[Bug] Little hole in cave

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#133]
_Originally written by **Mr. Spino | 76561198181071317**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2070 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **U can see there little hole** 
Map: Rival_Shores

Location: X=-98032.773 Y=43299.668 Z=3840.848

Can u repair the map here ?

**Comment by Predatoria** [comment]
Fixed
