### ISSUE TITLE
[Quality of life] drop bug?

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#134]
_Originally written by **Serenity | 76561198130229125**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **megalo** 
Map: Rival_Shores

hey, a meg hatchling died from being dropped after carry. It was close to the ground so it cant be fall dmg.

**Comment by Predatoria** [comment]
I'd need more information.  I won't be able to reproduce this bug from the provided information.  I'm going to close unless anybody has any further information on this.
