### ISSUE TITLE
[Quality of life] Ory can use random meshes big enough to block predators

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1342]
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Oryctodromeus** 
Map: Rival_Shores

-Have your ory dig a burrow and find something like a large rock that can block a one block tunnel
-Dig a one block wide hole behind said mesh
-No stale air in affect, your ory cant be reached unless they dig around the mesh.

**Comment by Predatoria** [comment]
Not gonna bother fixing this one
