### ISSUE TITLE
[Bug] Glitched out rock on Ancestral Plains

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1349]
_Originally written by **TheRiversEdge | 76561198107871153**_
Game Version: 1.1.1056

*===== System Specs =====
CPU Brand: AMD FX(tm)-8320 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **on Ancestral Plains** 
Map: Ancestral_Plains

*Expected Results:* Rock is firmly planted in the ground
*Actual Results:* Part of the rock is floating
*Replication:* Go to the below coords on Ancestral Plains

Location: X=116599.594 Y=122526.609 Z=11271.792

**Comment by Predatoria** [comment]
Deleted floating rock
