### ISSUE TITLE
[Bug] Acrocanthosaurus getting slow while carrying stuff and running

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#135]
_Originally written by **Phobos | 76561198075458294**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Acrocanthosaurus carrying stuff while being fat** 
Map: Rival_Shores

I just saw after i picked plants up (meanwhile i am fat 130 food). My walking speed is still the same like I carry nothing but if I start to sprint with shift I am slower than the walk. (And yes it use the stamina for the sprint but i am much more slower than if i walk normal with plants in my mouth)

**Comment by Predatoria** [comment]
Easy fix.  I modified the c++ to fix this but it's untested.  Will need testing on tester branch to confirm.
