### ISSUE TITLE
[Bug] Floating Tree Ancestral Plains

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1351]
_Originally written by **TheRiversEdge | 76561198107871153**_
Game Version: 1.1.1056

*===== System Specs =====
CPU Brand: AMD FX(tm)-8320 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **on Ancestral Plains** 
Map: Ancestral_Plains

*Expected Results:* Tree is grounded and not stuck to neighboring tree
*Actual Results:* Tree is floating and stuck to neighboring tree
*Replication:* Go to the below coords on Ancestral Plains

Location: X=-35339.266 Y=9121.331 Z=12722.130

**Comment by Predatoria** [comment]
Deleted the tree
