### ISSUE TITLE
[Bug] Fying fish.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1359]
_Originally written by **ANAT | 76561198280368949**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand:         Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 745
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **pteridactyle** 
Map: Ancestral_Plains

I was looking for food and i found a flying fish
Location: X=135932.625 Y=48029.195 Z=6074.622

**Comment by Trip-Trap** [comment]
Totally a feature
