### ISSUE TITLE
[Bug] Command SetGrowthLevel

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1365]
_Originally written by **Teeoo :p | 76561198241202054**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Console Command** 
Map: Rival_Shores

Indeed there is a new bug on the setgrowthlevel command.
When we want to setgrowthlevel "level" "ID", it doesn't work and grow the owner of the command.
That's means that we can't grow another player whitout giving admin role and that he does it himself.

**Comment by cleafspear** [comment]
this is working as intended.
