### ISSUE TITLE
[Major Bug] Velo managed to be in a group with Pteranodons

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#137]
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **A nested pteranodon.** 
Map: Rival_Shores

I dont know how it happened, but a velo by the steam username of Fae has managed to be in a pteranodon group on Lost Beasts #2.
They can communicate in group chat and everything.

**Comment by Trip-Trap** [comment]
Was an admin that made the mixed pack
