### ISSUE TITLE
[Bug] megalo slidding  instead of walking

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1372]
_Originally written by **Maverick[doza alt] | 76561199020430357**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD Ryzen 7 2700X Eight-Core Processor         
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **on my  acro  while watching  it   happen ** 
Map: Rival_Shores

happens  when   u  pick  up the meg  bb  thats under  .6 and  it  starts to slide around  on the ground

**Comment by Predatoria** [comment]
cannot reproduce
