### ISSUE TITLE
[Quality of life] Buff/debuffs who have scrolls are not scrollable

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1373]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.1062

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Intimidated Creature** 
Map: Rival_Shores

*Expected Results:* Being able to scroll when there is a scroll wheel.
*Actual Results:* The description only displays on hover and closes as soon as its not hovered over anymore.
*Replication:* Get the intimidation debuff, which has a scroll.

(probably just make the lists long enough to not require scroll, there is enough space)

**Comment by Predatoria** [comment]
Should be fixed next tester
