### ISSUE TITLE
[Quality of life] Severe frame drop while picking up objects among many other objects (and people)

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#138]
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Pteranodon** 
Map: Rival_Shores

Frames drop to a very frightening extent while I was picking up glowing mushrooms while there were many pteranodons and bones nearby.

Location: X=230202.766 Y=195973.609 Z=13537.840

**Comment by Trip-Trap** [comment]
#302
FPS drop issue when picking up objects
