### ISSUE TITLE
[Quality of life] hit box issue

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1387]
_Originally written by **greenbleach | 76561198862097364**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD Ryzen 7 2700X Eight-Core Processor         
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1050
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **smaller dinos and while i was on bigger dinos i saw my self abuseing these hit boxes** 
Map: Test_Performance

the hit boxes for all dinos are terrible please revise themhowever pteradons velos and smaller animals have pretty well desinged hit boxes but the bigger apexs have terrivble hit boxes and megalo expecially is tooooo big thjey can hit u when your at there tail and there looking folward

**Comment by Predatoria** [comment]
Not a bug
