### ISSUE TITLE
[Bug] stuck between rocks

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1390]
_Originally written by **CEO of Seagulls | 76561198956028385**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 620
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Velo** 
Map: Rival_Shores

While nesting i walked above a hole and suddenly got stuck in a very small hole with a rock above me.
Location: X=-205341.656 Y=24452.902 Z=22992.131

**Comment by Predatoria** [comment]
Fixed in another report.  Added many rocks
