### ISSUE TITLE
[Bug] Talent Points

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1391]
_Originally written by **Fenix | 76561199039273518**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **All types of dinos...** 
Map: Ancestral_Plains

I am unable to allocate more than one point for each talent. I'm not sure if it's just me or a bug.  I even get some +1 talents and still can only allocate one point.

**Comment by Predatoria** [comment]
Likely user error.  Cannot reproduce
