### ISSUE TITLE
[Bug] Cave effect getting stuck after leaving shade of tropeo mtn rocks

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1394]
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.1065

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Tropeognathus** 
Map: Rival_Shores

Location: X=225027.531 Y=194573.906 Z=3481.864
Reproduction might need just entering and exitting the shade of this point, or exitting with a animal in your character's mouth.

**Comment by Predatoria** [comment]
Should be fixed next tester patch
