### ISSUE TITLE
[Bug] Ory holes and non para eating

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1398]
_Originally written by **Egg Dog | 76561198029200412**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Eating while walking as a not- para** 
Map: Rival_Shores

When you press and hold "E" on a Ory hole as any herbie, you can walk and eat while walking as a para.

**Comment by Trip-Trap** [comment]
#779

**Comment by Trip-Trap** [comment]
#779
