### ISSUE TITLE
[Enhancement] Mosa grab-call

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#140]
_Originally written by **Bulbertianus | 76561198987079439**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **any land dino, even rexes** 
Map: Rival_Shores

Long story short, mosa is the worst thing in this game, period. You can be no mater how big, 1.5 or 2.0 or more, if 2 or more mosa go againts you, you are done. They grab you, and during the grab you make a 5 call, and you CANT DO ANYTHING! This period, enough to bring you down, a little, but enough. Then second mosa grabs you, another seconds without defense vs them (coz the call), and you are even deeper. Repeat this just few times, and death by drown without any bite from mosas.

Please remove the call while being grabbed, so you can instantly fight back.

**Comment by Predatoria** [comment]
This is not a bug.  The 5 call is intended.
