### ISSUE TITLE
[Quality of life] AFK Time-Out While Making Skins

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#141]
_Originally written by **PIE_USER | 272**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 4600
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **No creature - Player Cam** 
Map: UEDPIE_1_Test_Performance

*Expected Results:* 

While the player is making a skin, so long as they are active they should not be removed by the AFK time-out.

*Actual Results:* 

If the player stays on the dino selection screen for too long, they will be kicked for inactivity.

*Replication:* 

Enter the dino selection screen and fiddle around with skins until you get AFK-kicked.

*Suggested Fix*

While in the dino selection screen, mouse movement resets the AFK timer

**Comment by Thy-Vipe** [comment]
should be fixed
