### ISSUE TITLE
[Major Bug] Talent Points In Egg

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1418]
_Originally written by **Sawbus | 76561198025190854**_
Game Version: 1.1.1068

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Forest_Island

I was nested into the new birds and have been gaining constant talent points while incubating. Something to look into before deployment of this dino.

**Comment by Predatoria** [comment]
Should be fixed next tester patch

**Comment by cleafspear** [comment]
Verified fixed in tester
