### ISSUE TITLE
[Severe Bug] Crystals Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1419]
_Originally written by **Teeoo :p | 76561198241202054**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **All dinosaurs** 
Map: Rival_Shores

When we collect a orange crystal when we still press E and collect blue crystals these blue crystals be orange and we lost blue crystals

**Comment by Trip-Trap** [comment]
#659
