### ISSUE TITLE
[Major Bug] Camera Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#142]
_Originally written by **Anubis Deku | 76561199001075987**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **On TEoE server** 
Map: Rival_Shores

I loaded into the server and my camera will not stay stationary. It keeps rotating around my dino.

**Comment by Thy-Vipe** [comment]
Looks like a user error, closing unless we get more info.
