### ISSUE TITLE
[Bug] 3.2+ ory can't fit into own burrows

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#143]
_Originally written by **Detestation | 76561198019845935**_
Game Version: 1.1.947

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory was 3.2 and dug a burrow** 
Map: Rival_Shores

*Expected Results:* Ory fits into a burrow
*Actual Results:* Ory doesn't fit into a burrow
*Replication:* Grow Ory to 3.2 and make a burrow

**Comment by Predatoria** [comment]
I'm adding an experimental test.  Burrows shrink you to 2.0 if you're > 2.0.
