### ISSUE TITLE
[Bug] 3.0+ ory has camera problems

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#144]
_Originally written by **Detestation | 76561198019845935**_
Game Version: 1.1.947

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory** 
Map: Rival_Shores

*Expected Results:* Camera is behind ory
*Actual Results:* Camera clips under the belly
*Replication:* Zoom camera as far as possible and grow it to 3.0

**Comment by Predatoria** [comment]
Duplicate of issue 154.  It's fixed next tester patch.
