### ISSUE TITLE
[Major Bug] No creatures to select/spawn/etc

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1447]
_Originally written by **tjhomeboy | 76561199017675123**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) Iris(R) Plus Graphics
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Creature select screen** 
Map: Rival_Shores

no creatures show up, im just a floating pov

**Comment by cleafspear** [comment]
issue resolved in older patch.
