### ISSUE TITLE
[Quality of life] Cant wingbeat creatures while flying unless they are also flying

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1455]
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.1072

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Tropeognathus.** 
Map: Rival_Shores

I tried to wing beat a rex, and even though I was right inside his back I didn't hit him. I can only hit land animals unless I am also on land, same goes for aquatic creatures- I cant wing beat them while theyre darting in air, or if theyre close enough to the surface for me to reach them. Im not sure if this is intended or not, so I'm not reporting it as a bug.

**Comment by cleafspear** [comment]
working as intended
