### ISSUE TITLE
[Bug] 0 hunt points since tropeo patch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1463]
_Originally written by **Ayylien | 76561198138586766**_
Game Version: 1.1.1072

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Rival_Shores

0 hunt points show in trials as tropeo, haven't seen any other dinos with this problem.

**Comment by Trip-Trap** [comment]
Probably got their trials reset? not sure
