### ISSUE TITLE
[Quality of life] fish in the air

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1470]
_Originally written by **| VR | DekaGosso | 76561198448487377**_
Game Version: 1.1.1072

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 3
===================*
Map: Ancestral_Plains

I can't eat fish as a sea creature, because all fish in the air

**Comment by Trip-Trap** [comment]
<u< tide might be too strong on AP but fishs have always been flying on that map. Gonna close that issue
