### ISSUE TITLE
[Bug] strong bond dosent work

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1472]
_Originally written by **Peanut Butter GanGster? | 76561198151957441**_
Game Version: 1.1.1072

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3600X 6-Core Processor             
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1660
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

have strong bond inherited but effect doesent proc

**Comment by Trip-Trap** [comment]
Could not have mated, could not have had enough friendship, could have been related. Unknown variables
