### ISSUE TITLE
[Bug] Ory falling through burrow

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1482]
_Originally written by **Beenless | 76561198213334393**_
Game Version: 1.1.1072

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ory** 
Map: Rival_Shores

I dug a zone in the burrow, another ory was standing near the sloped wall as i dug that spot open and as that zone was opened the player fell through the map and was teleported to the burrow entrance outside.

**Comment by Trip-Trap** [comment]
#394
