### ISSUE TITLE
[Severe Bug] marine glide cheat

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#149]
_Originally written by **Bulbertianus | 76561198987079439**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **marines** 
Map: Rival_Shores

Not really sure if its a cheat or "just" a bug, but marines, specially mosas do it. They charge out from water to land, but not getting beached in whole period. Even glide sometimes several meters (up to hill or flat land) and during that period can grab other creatures.

Please fix marine land-glide and make them beached if doing so.

**Comment by Trip-Trap** [comment]
This state also make the mosasaur look beached to other clients when last tested. (making them assume it is safe to attack them, as a beached aquatic is a lot less dangerous than a sliding one) This state also does not give them the beached debuff, making them able to stay on land for a long period of time.

**Comment by Predatoria** [comment]
I'm deploying a potential fix for this in 1.1.952
