### ISSUE TITLE
[Bug] velo 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1496]
_Originally written by **Popo | 76561198864476325**_
Game Version: 1.1.1072

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Ancestral_Plains

velos left eye satus open when sleeping

**Comment by Trip-Trap** [comment]
feature
