### ISSUE TITLE
[Major Bug] sai tail hitbox

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#150]
_Originally written by **Bulbertianus | 76561198987079439**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **sai** 
Map: Rival_Shores

Sai tail hitbox even at 1.2+ size its too low. Acros and rexes can hold their head over it (specially with alt head up) and during that sai cannot hit it. Then they bite down and can hit. This is pure onesided fight.

Please make sai hitbox better vertically, to prevent hitbox abusing from big carnivers.

**Comment by Predatoria** [comment]
I'm hesitant to change this.  Sais are very difficult to kill.  This is more of a balance suggestion than a bug.
