### ISSUE TITLE
[Enhancement] AP load distance

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1506]
_Originally written by **Bulbertianus | 76561198987079439**_
Game Version: 1.1.1072

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **anything than rats** 
Map: Ancestral_Plains

Ap map loading the cave and other objects from any distance with any load distance settings, causing a really weird look even from land, and terrible shapes from bird view. Floating cave systems and cube waterspots really looks ugly, and only this map have this problem.

**Comment by Trip-Trap** [comment]
It's an tesselation issue wont be fixed
