### ISSUE TITLE
[Bug] Ory digging not cancelling right when attacked

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#151]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.947

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory** 
Map: Rival_Shores

*Expected Results:* Ory digging stopping when attacked/getting dmg while attacked and digging/stopping Ory from entering its burrow when it gets knocked back.
*Actual Results:* Ory is immune to dmg while diggin in the burrow. If digging an entrance the act is stopped when hit but will not receive damage. If Ory is picked up while entering the burrow, ory will finish entering the burrow and have the in-burrow hud. When put down its outside the burrow again.
*Replication:* Kill ory while it is entering a burrow, making an entrance and tunneling. Try to damage ory while it is entering a burrow, making an entrance and tunneling. Pick Ory up while it is entering a burrow.

**Comment by Predatoria** [comment]
I'm testing this in PIE. 

I do receive damage and stop digging a burrow when attacked while digging a new burrow entrance.

I do receive damage and stop entering a burrow when attacked from the surface.

I can reproduce the bad burrow state issue when grabbed while entering a burrow, but it is force-fixed when I am dropped.  I have fixed it to behave properly.

Fixed an unrelated bug where if you enter a burrow while grabbing another player, they are also set to be in a burrow

I can reproduce biting a player while they are leaving a burrow causes a jam.  Fixed that.

I can reproduce grabbing a player while they are leaving a burrow causes a state jam.  Fixed that.

Marking this as a multi-part bug that's ready for testing.
