### ISSUE TITLE
[Bug] thalasso-bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1512]
_Originally written by **KOlabZz | 76561198440679897**_
Game Version: 1.1.1072

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 4600
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Map: Rival_Shores

 i was near beach, and i have debaff
Location: X=148838.781 Y=207411.969 Z=1854.385

**Comment by Trip-Trap** [comment]
Was able to reproduce it with a meg. There is a steep drop after a shallow part. The trace might be off by a few meters.

**Comment by Trip-Trap** [comment]
#not a bug
