### ISSUE TITLE
[Bug] SeaShells Are to Heavy

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1515]
_Originally written by **Raphead | 76561198387202626**_
Game Version: 1.1.1072

*===== System Specs =====
CPU Brand: AMD Ryzen 5 1600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

Hey idk if this is intended or not but the sea shells if u pick them up they are rly heavy so could u maybe make them lighter since i dont think they should be so heavy if i pick like a few of them up they weigh like close to 780

**Comment by Predatoria** [comment]
They're based off food.  No easy way to fix this atm.
