### ISSUE TITLE
[Bug] Ichthy Swipe Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#152]
_Originally written by **TheRiversEdge | 76561198107871153**_
Game Version: 1.1.947

*===== System Specs =====
CPU Brand: AMD FX(tm)-8320 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ichthyovenator** 
Map: Rival_Shores

*Expected Results:* Ichthy swipe attack animates every time when used in succession (spammed)
*Actual Results:* Ichthy swipe attack will sometimes consume AP without animating
*Replication:* Spam the ichthy swipe attack (RMB)

**Comment by Predatoria** [comment]
Fixed next tester build
