### ISSUE TITLE
[Quality of life] Water Gap

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1520]
_Originally written by **Wolgan Renegade | 76561198127450399**_
Game Version: 1.1.1072

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Ancestral_Plains

I had swam into the big lake near the ocean durrin a storm and when it ended a big gap of water remained
Location: X=-148117.359 Y=-8158.603 Z=1121.066

**Comment by Predatoria** [comment]
This area is under the regular ocean high tide mark
