### ISSUE TITLE
[Major Bug] Map Gap

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1521]
_Originally written by **Taevali Too | 76561198006577267**_
Game Version: 1.1.1072

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Velo** 
Map: Rival_Shores

Hatchlings fall through this gap a lot, just a slight issue that needs fixing.
Location: X=215270.812 Y=39296.551 Z=22753.188

**Comment by Predatoria** [comment]
Covered with rocks
