### ISSUE TITLE
[Quality of life] Ory can't baby carry

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#153]
_Originally written by **Dr Nox | 76561198060480535**_
Game Version: 1.1.947

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Oryto** 
Map: Rival_Shores

Simply put, ory is unable to carry other creatures it should be able to.

**Comment by Predatoria** [comment]
Adding this next tester patch.
