### ISSUE TITLE
[Bug] Report BUG

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1536]
_Originally written by **Gre$hnik | 76561199083224528**_
Game Version: 1.1.1072

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

Добрій день , проблемма с анимацией и баг при поднятии динозавра из положения лежа при затоплении , то есть если вас затопило в лежачем положении и ві встали то ві не можете двигаться и умираете ...исправьте

**Comment by Trip-Trap** [comment]
"Good afternoon, there is a problem with animation and a bug when raising a dinosaur from a prone position during flooding, that is, if you are flooded in a supine position and you get up then you cannot move and die ... fix it"

**Comment by Trip-Trap** [comment]
#463
