### ISSUE TITLE
[Bug] Large oryctos have the velo butt bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#154]
_Originally written by **Dr Nox | 76561198060480535**_
Game Version: 1.1.947

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Orycto** 
Map: Rival_Shores

Large (2.0) Oryctos have the same bug velo had with their butts being in your face. Unpleasant.

**Comment by Predatoria** [comment]
Fixed next tester
