### ISSUE TITLE
[Quality of life] Ocean bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1546]
_Originally written by **Calmy | 76561198271752632**_
Game Version: 1.1.1072

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1660
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **always near ocean** 
Map: Ancestral_Plains

Location: X=-20263.664 Y=30902.393 Z=3017.914
Visual bug of the upper ocean layer.

**Comment by tinystarpaws** [comment]
Issue has been fixed with the new ocean system.
