### ISSUE TITLE
[Bug] Blurriness

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#156]
_Originally written by **AzzyTheAngel | 76561198088778413**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **velo hatchling.** 
Map: Rival_Shores

While in the caves I was hatched as a velo and hatched with blurriness that would not go away. It fixed after safelogging but recurred after being carried/jumped back up onto a ledge.
Location: X=4098.564 Y=224602.922 Z=9362.008

**Comment by Trip-Trap** [comment]
Duplicate #122
