### ISSUE TITLE
[Bug] Shadows appear on the water's surface

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#157]
_Originally written by **Detestation | 76561198019845935**_
Game Version: 1.1.948

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Graphics boi watching water's surface while palm trees casted a shadow on it** 
Map: Rival_Shores

*Expected Results:* Shadows appear under the water, on sand. Some reflections may apply on the surface.
*Actual Results:* Shadows appear on the water's surface
*Replication:* https://youtu.be/Zmw3qovXNY0

**Comment by Thy-Vipe** [comment]
Tied to 4.25 update, shadows should be both on water and underwater if not deep enough, not going to worry about it.
