### ISSUE TITLE
[Major Bug] Picking up items while in Spectate

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1595]
_Originally written by **Wolfalisk | 76561197988955479**_
Game Version: 1.1.1076

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Tested on most/all Dinos** 
Map: Ancestral_Plains

Bug found by Wolfalisk and TKirr of The Forgotten Realms.

While in spectate, it is possible to drink water and pick up gore, crystals, and other items. This action causes the following output in server logs in a very spammy fashion - very much bloated the log. Other players can see. This was possible intermittently prior to the most recent patch but it is now reproducable and constant.

[2020.10.29-02.03.15:706][850]LogSkinnedMeshComp: Warning: GetSocketByName(HeldObjectSocket): No SkeletalMesh for Component(CharacterMesh0) Actor(Playable_Entity_ObserverCam_C_2144588731)

**Comment by cleafspear** [comment]
fixed
