### ISSUE TITLE
[Bug] Empty bone weight still applies after it gets removed your mouth

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#160]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.948

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Carnivore** 
Map: Rival_Shores

*Expected Results:* When a bone rots in your mouth and drops to the floor, the weight will not continue to apply to your carry weight and your mouth will close.
*Actual Results:* When a bone rots in your mouth and drops (as you can not carry empty bones), the weight will continue to apply as if you are still carrying it and your mouth will be stuck in the open, unless you hit unjam.
*Replication:* Wait for a big gore to be as good as rotten. Pick up a stick from it with a carnivore and wait until it rots in your mouth.

**Comment by Predatoria** [comment]
Reproduced in PIE

**Comment by Predatoria** [comment]
Fixed next tester patch!
