### ISSUE TITLE
[Bug] Ichthy can attack twice within one arm swing animation

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#161]
_Originally written by **Dr Nox | 76561198060480535**_
Game Version: 1.1.948

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ichthyovenator** 
Map: Rival_Shores

*Expected Results:* Ichthy can only attack once to start the swing animation and not again during it.
*Actual Results:* Ichthy can attack during the animation, taking the ability but not causing an animation or sound to play, the current animation just finishing. (Don't know if the second attack does damage or not)
*Replication:* Spawn an ichthy, spam secondary attack on land.

**Comment by Trip-Trap** [comment]
Duplicate #152
