### ISSUE TITLE
[Bug] Dart animation does not replicate

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#162]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.948

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ichthy** 
Map: Rival_Shores

*Expected Results:* If your ichthy rolls, it rolls on other clients too.
*Actual Results:* Ichthys dart does not replicate for other clients.
*Replication:* Watch another player dart.

**Comment by Predatoria** [comment]
Fixed next tester patch
