### ISSUE TITLE
[Quality of life] Crowded Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1624]
_Originally written by **Queenie | 76561198841434722**_
Game Version: 1.1.1076

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600X Six-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2060
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **noticed as Rex but happened with every dino** 
Map: Rival_Shores

As soon as the packlimit is reached and you have a nest with eggs going on the Crowded icon will show right after the person in the egg reaches 0.7 out of 1.0. It does not cause discomfort but it is confusing as you think you are overpacking. As soon as this person hatches the icon disappears tho

**Comment by cleafspear** [comment]
this was resolved in an older patch
