### ISSUE TITLE
[Quality of life] Falling through a rock.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1628]
_Originally written by **Right Nipple | 76561198087784602**_
Game Version: 1.1.1076

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Orycto** 
Map: Rival_Shores

I was running across a rock bridge over the river at snowy mountain. I fell through the rock... and couldnt get out
Location: X=-164085.688 Y=-14421.891 Z=11213.168

**Comment by Predatoria** [comment]
Added rocks to cover the hole
