### ISSUE TITLE
[Bug] water placement

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1629]
_Originally written by **FORCESNESS | 76561199066015416**_
Game Version: 1.1.1076

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 520
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **trouble home ru/eu** 
Map: Rival_Shores

found a square shaped part of water sticking out of the ground and floating sort or like in the combat map
Location: X=140510.656 Y=47008.465 Z=4979.300

**Comment by Predatoria** [comment]
Fixed from a different report
