### ISSUE TITLE
[Bug] Bad Rock that capture you

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#163]
_Originally written by **Teglami | 76561197989405185**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: AMD Ryzen 5 1500X Quad-Core Processor          
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Spectator + Velo** 
Map: Rival_Shores

Just found that rock in the cave that doesn't let you go. In Spectator and as a dino you're trapped there.

Location: X=-189681.828 Y=20569.238 Z=25871.098

**Comment by Predatoria** [comment]
Fixed
