### ISSUE TITLE
[Bug] Eating While Flying

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1630]
_Originally written by **JasperW | 76561198961600564**_
Game Version: 1.1.1076

*===== System Specs =====
CPU Brand: AMD A8-6600K APU with Radeon(tm) HD Graphics   
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 750 Ti
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Tropeognathus** 
Map: Rival_Shores

Wheni hold 'E' to break/land as a Trop, somtimes my bird start doing the eating animation and noise instead, i have nearly died multipul times from this.

**Comment by Trip-Trap** [comment]
#1597
