### ISSUE TITLE
[Bug] Oryctodromeus Drink Prompt Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#164]
_Originally written by **TheRiversEdge | 76561198107871153**_
Game Version: 1.1.948

*===== System Specs =====
CPU Brand: AMD FX(tm)-8320 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Oryctodromeus** 
Map: Rival_Shores

*Expected Results:* Drinking prompt shows up when at the edge of a water source while playing oryctodromeus
*Actual Results:* Drinking prompt does not show up at all when playing oryctodromeus
*Replication:* Spawn as an oryctodromeus, find a drinkable water source and notice the lack of a prompt to drink

**Comment by Predatoria** [comment]
Fixed next tester build
