### ISSUE TITLE
[Bug] wasd keys mixed up?

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1643]
_Originally written by **Swiss.Wolf | 76561197967686011**_
Game Version: 1.1.1076

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 620
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Map: Rival_Shores

I was trying to heal from a crash as a tropeognathus, and once I got up the keybinds were all weird. In the controls settings, it says they're normal, but ingame they're mixed up and I have no idea if it's because my dino hit its head too hard or a bug.
Location: X=112371.063 Y=83268.625 Z=3701.112

**Comment by cleafspear** [comment]
issue appears to be related to the user entering screenshot mode.
