### ISSUE TITLE
[Bug] Eating animation does not cancel when "use" is no longer pressed after pick up

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#165]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.949

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ichthy** 
Map: Rival_Shores

*Expected Results:* Eating animation to cancel when "use" is no longer held.
*Actual Results:* If you pick up - for example - a baby by double tapping the use key it will play through the whole eating animation if you don't move.
*Replication:* Pick up something as ichthy. Note that the eating animation won't stop. Try the same thing as another carnivore. Note that the eating animation will stop. 
(similar to that: if you stop eating the eating sound does not get notified that it should stop and will finish playing out the sound even tho it will stop the eating animation)

**Comment by Predatoria** [comment]
Fixed next tester
