### ISSUE TITLE
[Bug] Elasmo bais glitch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1653]
_Originally written by **???MBH??? Demon | 76561198971115472**_
Game Version: 1.1.1076

*===== System Specs =====
CPU Brand:         Intel(R) Core(TM) i5-2320 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 760
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Elasmos** 
Map: Ancestral_Plains

Elasmos cannot eat sponge to gain bais making their comfort really low and hard to maintain

**Comment by Trip-Trap** [comment]
Elasmos eat sponges by attacking them not the eating key.
