### ISSUE TITLE
[Bug] Icons Stick to Center of Screen

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#166]
_Originally written by **Gavin | 76561198254999852**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Apato** 
Map: Rival_Shores

*Expected Results:* Icons should stay above the players and not stick in the middle of your screen.
*Actual Results:* Icons stick to the middle of your screen if you turn your camera around, to face away from the icons.
*Replication:* Join a group and turn your camera, watch the icon stick to the middle of your screen.

**Comment by Predatoria** [comment]
Fixed next tester patch

**Comment by Trip-Trap** [comment]
This actually still happens
