### ISSUE TITLE
[Bug] Rock meshing Ancestral Plains

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1664]
_Originally written by **TheRiversEdge | 76561198107871153**_
Game Version: 1.1.1077

*===== System Specs =====
CPU Brand: AMD FX(tm)-8320 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Tropeognathus on Ancestral Plains** 
Map: Ancestral_Plains

*Expected Results:* Creature stands on top of the rock
*Actual Results:* Creature stands inside of the rock
*Replication:* Go to the below coords

Location: X=-787.038 Y=-111276.250 Z=3865.281

**Comment by Predatoria** [comment]
I replaced these problematic rocks with others that have better collision in a different report.
