### ISSUE TITLE
[Bug] Sniffing sound only plays at the start for ichthy

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#167]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.949

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ichthy** 
Map: Rival_Shores

*Expected Results:* Sniffing to repeatetly play while holding the sniff button down.
*Actual Results:* Sniff sound only playing at the start for ichthy.
*Replication:* Spawn as ichthy and hold sniff.

**Comment by Predatoria** [comment]
Fixed next tester patch
