### ISSUE TITLE
[Quality of life] Inherits on Ptera

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1686]
_Originally written by **Queenie | 76561198841434722**_
Game Version: 1.1.1076

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600X Six-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2060
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

Talentree change! Inherits which you got in pearcing beak did not relocate like the talent. Now you will have, if you got this inherit before in pearcing beak, this inherit in bruiser.

**Comment by Trip-Trap** [comment]
#518

**Comment by cleafspear** [comment]
this is no longer valid since the changes to how we manage talents
