### ISSUE TITLE
[Bug] Escape menu + Character select bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#170]
_Originally written by **Indigo | 76561198257387648**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Menu (N/A)** 
Map: Rival_Shores

If you go to creature select and press escape quickly after reaching the creature select menu, you will be brought to the escape menu, essentially forcing you to quit to the server list as you can't press escape again and leave the menu.

**Comment by Predatoria** [comment]
I can reproduce this in PIE

**Comment by Predatoria** [comment]
Fixed next tester patch!
