### ISSUE TITLE
[Bug] Black void underwater

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#172]
_Originally written by **TheRiversEdge | 76561198107871153**_
Game Version: 1.1.949

*===== System Specs =====
CPU Brand: AMD FX(tm)-8320 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Any creature** 
Map: Rival_Shores

*Expected Results:* The edge of the map underwater should be a natural/blue color
*Actual Results:* The edge of the map underwater shows a dark, black void on higher settings (green on lower settings?)
*Replication:* Spawn in as any animal, view the edge of the map underwater

**Comment by Thy-Vipe** [comment]
Got a potential fix for it. Couldn't reproduce after it
