### ISSUE TITLE
[Quality of life] Healed broken wing

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1723]
_Originally written by **Acciliage | 76561198351045143**_
Game Version: 1.1.1076

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Tropeognathus** 
Map: Ancestral_Plains

My dino broke it's wing and after it's fully healed the dino keeps flying in a downward angle if I'm not pressing any buttons to keep it level.

**Comment by cleafspear** [comment]
bug has not been reproducible for many versions. closing as resolved
