### ISSUE TITLE
[Bug] Tropeo constantly flies down

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1724]
_Originally written by **Morpheus | 76561198141062241**_
Game Version: 1.1.1076

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7 CPU       Q 840  @ 1.87GHz
Vendor: GenuineIntel
GPU Brand: AMD Mobility Radeon HD 5800 Series
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

I can't take off very well because my tropeo keeps flying downwards regardless of the direction I'm facing. When I manage to get into the air, the tropeo will proceed to dive downwards unless I constantly spam spacebar and shift.

**Comment by Trip-Trap** [comment]
They could have had severe injury, not replicatable.
