### ISSUE TITLE
[Bug] Ptera Crashing

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#173]
_Originally written by **littleSiren | 76561198817402833**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics Family
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Ptera** 
Map: Rival_Shores

It seems like the Ptera has a Bug and randomly starts to freeze its movements so you crashing and mostly dying. I have serveral troubels to start/land or even flying. I heard other players got this issues to, but we dont know if its a bug or we are all just to stupid to fly...
Unstuck & Unjam doesnt help in this situation since your not fast enough or it doesnt react until you fall into water.
Please take a look at the ptera and also made the start mechaninc easier for players.

**Comment by Predatoria** [comment]
I'm not really sure what to make of this.  I've not seen this while playing as a ptera.
