### ISSUE TITLE
[Bug] stuck next to a rock

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1734]
_Originally written by **Teddybear | 76561198356321911**_
Game Version: 1.1.1076

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **carnivore** 
Map: Rival_Shores

I fell down from a rock and now I am stuck and cannot move

**Comment by cleafspear** [comment]
we need rock location
