### ISSUE TITLE
[Enhancement] map location mesh viual diffrent from collision

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1738]
_Originally written by **Cleafspear | 76561198077984700**_
Game Version: 1.1.1076

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **observer** 
Map: Rival_Shores

this location needs a bit of checking
Location: X=-216723.859 Y=-10507.988 Z=20248.916

**Comment by Predatoria** [comment]
Patched this up in a different report earlier.
