### ISSUE TITLE
[Bug] map location: jungle hidden cave, ceiling hole to mesh

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#174]
_Originally written by **Cleafspear | 76561198077984700**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

hole that can be entered by players to enter under the mesh
Location: X=115639.617 Y=85064.039 Z=5331.729

**Comment by Predatoria** [comment]
Fixed
