### ISSUE TITLE
[Bug] jungle surface mesh hole

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#175]
_Originally written by **Cleafspear | 76561198077984700**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

location where there are 3 triangels in the mesh that have no collision, you can fall through on to a rock below
Location: X=110341.047 Y=88280.383 Z=7504.488

**Comment by Predatoria** [comment]
Fixed
