### ISSUE TITLE
[Bug] Ichthy does not cancel the eating animation when it stops eating

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#176]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.950

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ichthy** 
Map: Rival_Shores

*Expected Results:* Eating animation to stop together with the sound when you stop eating, like megalo for example.
*Actual Results:* Ichthy will continue to play the eating animation, even if the sound already cancelled.
*Replication:* Spawn as ichthy, spawn in a gore, eat a bit from it and watch the animation continue to play but the sound cancel.

**Comment by Predatoria** [comment]
This was intended, but Ichthy's eat_end animation is a lot longer than the other animals.  I went ahead and just made it skip eat_end.
