### ISSUE TITLE
[Bug] Hopping arround at the water nearby

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1763]
_Originally written by **Baiware | 76561197961466320**_
Game Version: 1.1.1076

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Charackter hopping arround** 
Map: Ancestral_Plains

Location: X=59820.027 Y=130630.109 Z=3557.112

When im near this water, my Dino is hoping arround all the time

**Comment by Predatoria** [comment]
Not really sure what they mean.  Not enough info.
