### ISSUE TITLE
[Bug] Ory does not play call animation while standing still

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#177]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.951

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Orycto** 
Map: Rival_Shores

*Expected Results:* Call animations play while standing still.
*Actual Results:* Call animations dont play while standing still as Ory.
*Replication:* Spawn as Ory and use all 5 calls without moving. Note that none will play the animation.

**Comment by Predatoria** [comment]
Reproduced in PIE, fixed next tester patch
