### ISSUE TITLE
[Severe Bug] no crash damage

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1775]
_Originally written by **Epialess | 76561198884023720**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  
Vendor: AuthenticAMD
GPU Brand: AMD Radeon(TM) Vega 8 Graphics
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **combat server, tropeo** 
Map: Test_Performance

*Expected Results:* dive from very high as a tropeo on to the ground, take crash damage and injury
*Actual Results:* tropeo can dive from very high and take no damage or injury from crashing
*Replication:* diving on to flat ground without using e to land from high up
I have video to show this, my discord is Epialess#0334

**Comment by Trip-Trap** [comment]
#2399
