### ISSUE TITLE
[Bug] Ory call animations not playing

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#178]
_Originally written by **TheRiversEdge | 76561198107871153**_
Game Version: 1.1.951

*===== System Specs =====
CPU Brand: AMD FX(tm)-8320 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Oryctodromeus** 
Map: Rival_Shores

*Expected Results:* Ory calls should play their animation while standing idle
*Actual Results:* Ory calls do not play their animation while standing idle
*Replication:* Spawn as oryctodromeus, play calls

**Comment by Predatoria** [comment]
Duplicate of 177.
