### ISSUE TITLE
[Bug] water

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1784]
_Originally written by **the carl b0i | 76561199085041752**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Ancestral_Plains

so uh i have the water effect while on land

**Comment by Predatoria** [comment]
Fixed
