### ISSUE TITLE
[Bug] Green Hue?

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1788]
_Originally written by **brooke | 76561198386508556**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  
Vendor: AuthenticAMD
GPU Brand: AMD Radeon(TM) Vega 8 Graphics
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Apato** 
Map: Rival_Shores

Rare chance for a green hue to go over the screen. First time this has happened, but it happened during a storm for my friend and I, and continued if I stay in the same spot.

**Comment by Trip-Trap** [comment]
They likely got the cave overlay from shelterer since they are apato. Its green on high post processing
