### ISSUE TITLE
[Major Bug] Ory teleporting after digging tunnel entrance

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#179]
_Originally written by **TheRiversEdge | 76561198107871153**_
Game Version: 1.1.951

*===== System Specs =====
CPU Brand: AMD FX(tm)-8320 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Oryctodromeus** 
Map: Rival_Shores

*Expected Results:* Ory should enter its burrow after digging a tunnel entrance
*Actual Results:* Ory teleports to the map origin after digging a tunnel entrance
*Replication:* Spawn as oryctodromeus, dig a tunnel entrance

**Comment by Predatoria** [comment]
This was being caused by some stuff I added to handle being attacked while exiting a burrow.  I've changed it and it seems to have fixed the issue.
