### ISSUE TITLE
[Quality of life] Groupmate icons detaching

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#180]
_Originally written by **Gling | 76561198120397137**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **in a mixpacking herbie group with apas and sais** 
Map: Rival_Shores

Icons of my pack mates are detaching from their location and being dragged around by the edges of the screen and occasionally returning to the player

**Comment by Predatoria** [comment]
This is a duplicate, and has been fixed on tester
