### ISSUE TITLE
[Major Bug] Cave lighting 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1802]
_Originally written by **Brightheart | 76561198284410043**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

Apon enter a cave it is pitch black no light

**Comment by cleafspear** [comment]
cave lighting is redone
