### ISSUE TITLE
[Bug] TESTER, freezing upon selecting Oryctodromeus

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#181]
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.951

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Dinosaur Selection** 
Map: Rival_Shores

Select Oryctdromeus, there was a low tier wind storm going aswell. May be related to the specific area I selected it in aswell. I almost thought my game was gonna crash.
Location: X=87662.617 Y=41999.684 Z=3185.333

**Comment by Thy-Vipe** [comment]
Not a bug - no skin on ory causes ensure condition error.
