### ISSUE TITLE
[Severe Bug] Tester, teleported into ocean while digging a burrow as a baby

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#182]
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.951

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Oryctodromeus** 
Map: Rival_Shores

I was digging my first burrow on a hill by the forest marsh, upon finishing the digging process i was then teleported into the ocean a long ways away from the initial burrowing site and almost drowned.

**Comment by Predatoria** [comment]
Duplicate.  Should be fixed this tester patch.
