### ISSUE TITLE
[Quality of life] Tester, Hard to eat fish as Juvie Icthy

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#183]
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.951

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Icthyovenator** 
Map: Rival_Shores

As a fresh spawn it was dificult to actually hit the fish I was trying to bite.
Location: X=-59090.090 Y=55369.703 Z=4245.295

**Comment by Predatoria** [comment]
This should be a bit easier next patch

**Comment by Predatoria** [comment]
Wasn't officially tested / checked, but im going to close this.  It was easy to adjust.
