### ISSUE TITLE
[Bug] bug or feature

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1836]
_Originally written by **Bulbertianus | 76561198987079439**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **apa** 
Map: Rival_Shores

If an apa try to "pick up" or go into an ory nest, after that it can move and eat at the same time, same as paras do.

**Comment by Trip-Trap** [comment]
#779
