### ISSUE TITLE
[Bug] Cooldown on slots when login in

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#184]
_Originally written by **Dj90000 | 76561198148863833**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Choosing dinos right after login in to the server** 
Map: Rival_Shores

The moment I logged into the server one of my dino slots was greyed out and saying it had a cooldown of 00:00, no matter how much I pressed the button to spawn while selecting it, it did not let me spawn with that dino.

**Comment by Predatoria** [comment]
I'm not sure how to reproduce this.

**Comment by cleafspear** [comment]
we have not had this happen in quite a while since some of the save revamps, closing as no longer reproduceable
