### ISSUE TITLE
[Quality of life] River / Terrain clip

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#185]
_Originally written by **vulture | 76561198981285550**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

This part of the river on Rival Shores looks odd, as there's a sliver or water come out through the land.
Location: X=-158015.391 Y=-15416.556 Z=10914.206

**Comment by Predatoria** [comment]
Fixed
