### ISSUE TITLE
[Severe Bug] abusing food from babies

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1857]
_Originally written by **Bulbertianus | 76561198987079439**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **a baby** 
Map: Rival_Shores

Fresh babies compared to it's size, even without eating, gives a hugeeee carcas, making people ABUSE this, to grow themselves. By pooping babies, then eating them or feeding others with it.

**Comment by cleafspear** [comment]
this has been fixed it the latest public patch.
