### ISSUE TITLE
[Bug] Under world/rock glitch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#186]
_Originally written by **HeatedGold | 76561198137175296**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Velo** 
Map: Ancestral_Plains

Theirs a hole in the rock that you can go into as anything small and you wont be seen. As well as you can see everyone within the mountain radius.
Location: X=107933.008 Y=108047.266 Z=6401.173

**Comment by Predatoria** [comment]
Coordinates are wrong.  This leads to an open field.
