### ISSUE TITLE
[Bug] Fly under Map at Cave Entrance Bridge

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1865]
_Originally written by **Sykress | 76561198079797068**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

Location: X=111887.148 Y=137983.156 Z=15636.947

There is a a whole in the stone wall above the entrance to the cave system at bridge c:

**Comment by Predatoria** [comment]
Added rocks to block this
