### ISSUE TITLE
[Bug] Ory sliding away while leaving the burrow

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#189]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.952

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Orycto** 
Map: Rival_Shores

*Expected Results:* Ory leaving the burrow normally.
*Actual Results:* If you hold shift while leaving a burrow you will slide away in the "leave burrow" animation.
*Replication:* Spawn as Ory, make a burrow, enter the burrow, leave the burrow while holding shift.

**Comment by Predatoria** [comment]
This should be fixed next patch!  it was a bug injected due to another bug fix
