### ISSUE TITLE
[Bug] legging 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1891]
_Originally written by **Phoenix | 76561198255775513**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 620
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

i was flying in the air and it started lagging me back 3 times

**Comment by Trip-Trap** [comment]
Seems like lag yes.
