### ISSUE TITLE
[Bug] Bug chat

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1898]
_Originally written by **DelMax | 76561198422028529**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

Quand le chat et ouvert et il quelque chose ecrit dedan on ne peut plus courire

**Comment by Trip-Trap** [comment]
"When the cat is open and there is something written in it we can't run anymore"

Seems correct yes. Since you are typing in the chat, not sure what the issue is.
