### ISSUE TITLE
[Quality of life] Elasmo

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1899]
_Originally written by **Jelly Butter | 76561198079521342**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3600 6-Core Processor              
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Elasmo** 
Map: Rival_Shores

*Expected Results:* Elasmo should be able to press and hold E on coral and comfort plants
*Actual Results:* you have to bite them 
*Replication:* you cant press E on comfort things 

only way to eat them is to bite them for 20 minutes super annoying

**Comment by Trip-Trap** [comment]
This is intended.
