### ISSUE TITLE
[Enhancement] Ory sitting neck snap with 1 call

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#190]
_Originally written by **Spooky Spooks | 76561198040926907**_
Game Version: 1.1.952

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ory** 
Map: Rival_Shores

When you sit and 1 call with Ory its neck deforms in a very strange way, making it look like its almost snapping its neck. Its pretty jarring.

**Comment by Predatoria** [comment]
We haven't taken a closer look at Ory's weight painting and meshing and stuff yet.  This is present when the Ory is standing as well.
