### ISSUE TITLE
[Enhancement] Ichthy, Megalo and Ory stand up from their crouch when using a call

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#192]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.952

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ichthy, Megalo, Ory** 
Map: Rival_Shores

For sneaking around it might make sense to have the call also blend into the crouch animation, similar to sitting. So you can visually remain in crouching.

**Comment by Predatoria** [comment]
I changed this next tester patch
