### ISSUE TITLE
[Bug] Aquatics grab bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#193]
_Originally written by **Spooky Spooks | 76561198040926907**_
Game Version: 1.1.952

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Mosa, elasmo ** 
Map: Rival_Shores

When an aquatic is doing a call they can grab while calling with their ability. Could be used to bait people in and grab them when they think you cannot attack. Only works when its the creatures ability to grab, the normal e grab works as intended.

**Comment by Predatoria** [comment]
Not really a bug.  I'm not sure if we intend for it to be this way or not, but I won't  be changing it right now.

**Comment by Trip-Trap** [comment]
No other creature is able to grab while calling, its just elasmo and mosa.
