### ISSUE TITLE
[Quality of life] Dificulty eating and not getting obese

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#194]
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.952

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Oryctodromeus** 
Map: Rival_Shores

Tried to just eat some herbs, but while i ate my ory was able to eat ferns far from it and got a bit chungus despite that not being my intention

**Comment by Predatoria** [comment]
This isn't a bug.  Trace size now has a minimum size for foliage consumption.
