### ISSUE TITLE
[Bug] Camera Clipping into grey rocks

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1948]
_Originally written by **Catolotl | 76561198440141324**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

*Expected Results:* Having the camera stay outside of the rock, I'm a tropeo.
*Actual Results:* The camera clipped through a rock. Before, on a different dino (ory), the same thing happened with the ground. 
*Replication:* Not sure what this means, sorry.
Location: X=109252.602 Y=46882.672 Z=7767.552

**Comment by Trip-Trap** [comment]
The some of the grey rocks on rival shores (not sure if on AP too) dont have camera collision anymore atm. These one for example: (their tp location also has one of these)
![grafik](https://user-images.githubusercontent.com/56919683/99877829-37577500-2c01-11eb-8d89-dcee18b63b56.png)

**Comment by Predatoria** [comment]
I added camera collision to these rocks
