### ISSUE TITLE
[Bug] .7 Ory hovers above ground

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#195]
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.952

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Oryctodromeus** 
Map: Rival_Shores

I just noticed while working on my burrow and working around it my ory is now suddenly a few inches above ground. Maybe has something to do with the burrowing, because I didnt notice until now.

**Comment by Predatoria** [comment]
This wasn't growth-related, but the ory would get set to an improper offset if it dug a burrow entrance or exit.  This was a bug caused by a previous bug fix.  I've fixed it next tester patch.
