### ISSUE TITLE
[Major Bug] Snowy mountain doesnt seem to welcome burrows

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#196]
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.952

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Oryctodromeus** 
Map: Rival_Shores

at the start I can dig a burrow fine, but once i start trying to tunnel in it the area goes dark, my ory is floating, then im forcibly removed. At first I thought it was the hotspring, but when i tried to dig further away from the puddle I had the same result.
Location: X=-196227.641 Y=41299.266 Z=36795.195

**Comment by Predatoria** [comment]
Should be fixed next tester patch.
