### ISSUE TITLE
[Bug] Cave effect

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#197]
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.952

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Icthyovenator** 
Map: Rival_Shores

The darkness and ambience of being in a cave comes in if you go to creature select and pick a different dinosaur before your oryctodromeus is forced out of its burrow.

**Comment by Predatoria** [comment]
Should be fixed next tester patch.
