### ISSUE TITLE
[Bug] Ichty and Huntpoints

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1974]
_Originally written by **Queenie?? | 76561198982592849**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600X Six-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2060
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

From hunting Ichtys do not get many huntpoints....is that a bug or wanted?

**Comment by Trip-Trap** [comment]
Depends on what they are and what growth etc. Closing this for not enough info.
