### ISSUE TITLE
[Bug] Hacking rock

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#198]
_Originally written by **DarkPhoenix23 | 76561198112524993**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2070
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **yes rival shores** 
Map: Rival_Shores

Rock floating must die kill it with fire
Location: X=77150.695 Y=135471.047 Z=-2222.998

**Comment by Predatoria** [comment]
Fixed
