### ISSUE TITLE
[Bug] UI Vanished

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#199]
_Originally written by **{?????????} Yuuya | 76561198237228962**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: AMD Ryzen 3 2200G with Radeon Vega Graphics    
Vendor: AuthenticAMD
GPU Brand: AMD 15DD Graphics
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Apato** 
Map: Rival_Shores

I accepted an Apato egg and my UI stopped appearing, all group nametags appeared as Invalid, their avatars as transparent boxes, and when I pressed I they vanished and won't come back. I can't talk, but I can see others talking in Global. I can't see how far my egg has progressed, and all the info is O is 'Text Block'

**Comment by Predatoria** [comment]
Sounds like a nasty bug, but I really don't have enough to go off of here to reproduce this and fix it.
