### ISSUE TITLE
[Bug] Sound Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1992]
_Originally written by **BossHog | 76561197969239706**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Acro** 
Map: Rival_Shores

Standing in the middle of the desert and i can hear the ocean as if it was right next to the dino in game. Should sound further away or not all based on how far iam from the ocean or any water source for that matter.

**Comment by Trip-Trap** [comment]
Same person same report
#2021
