### ISSUE TITLE
[Severe Bug] glitch death

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#200]
_Originally written by **StarPowerSDS | 76561198973065327**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **glitch** 
Map: Ancestral_Plains

i was a baby velo and i was set on the ground and i glitched through the cave and was all of a sudden in the middle of the ocean at the bottom

**Comment by Predatoria** [comment]
I have no idea how to reproduce this.
