### ISSUE TITLE
[Bug] Digging down sometimes leaves floor so you can't go to lower level

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#201]
_Originally written by **Detestation | 76561198019845935**_
Game Version: 1.1.953

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory** 
Map: Rival_Shores

*Expected Results:* Ory digs down and burrow updates properly
*Actual Results:* Ory digs down but new burrow doesn't remove the ceiling so you can't actually access that level at all
*Replication:* Go to this location and dig down. https://youtu.be/89UOcwmB70k
Location: X=170506.234 Y=42648.559 Z=5751.971

**Comment by Predatoria** [comment]
This was caused by setting tunnel nodes to be stored in local space instead of world space.  I fixed it next patch.
