### ISSUE TITLE
[Bug] wedged between rocks

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2010]
_Originally written by **vluckie | 76561198884286208**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 570 Series
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Ancestral_Plains

was trying to get away from storm and hide from predetors and i got stuck inbetween a rock and a moutain and cant get out
Location: X=-91527.977 Y=-91001.195 Z=7094.043

**Comment by Predatoria** [comment]
Flattened terrain out here
