### ISSUE TITLE
[Quality of life] Trials

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2014]
_Originally written by **Queenie?? | 76561198982592849**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600X Six-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2060
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ichty** 
Map: Rival_Shores

The Trials on my Dinos get reset from time to time. Noticed while my dino was 1.6 but the age was only 29 minutes

**Comment by Trip-Trap** [comment]
#2110 
Same person same issue.
