### ISSUE TITLE
[Bug] Animation Error on Mega

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#202]
_Originally written by **Rexy Deku | 76561198950550896**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **A mega drinking water from any water source.** 
Map: Rival_Shores

When drinking water, the tip of the tongue goes thru the roof of the mouth and appears outside of the mega model. It showed up as a hatchling, and didn't go away even as you grow.

**Comment by Predatoria** [comment]
Fixed next tester!
