### ISSUE TITLE
[Enhancement] Ichthy elongating

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#203]
_Originally written by **TheRiversEdge | 76561198107871153**_
Game Version: 1.1.954

*===== System Specs =====
CPU Brand: AMD FX(tm)-8320 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ichthyovenator** 
Map: Rival_Shores

*Expected Results:* Ichthy's torso remains unchanged when 3 calling underwater
*Actual Results:* Ichthy's torso elongates when 3 calling underwater
*Replication:* Spawn as ichthyovenator, enter water, 3 call

**Comment by Predatoria** [comment]
This is just a problem with the entire animation.  I probably will just ignore this.
