### ISSUE TITLE
[Severe Bug] fell through the world and died

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#204]
_Originally written by **spacebutters | 76561198236965714**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Velociraptor** 
Map: Rival_Shores

playing velociraptor, jumped into the air and fell through the world when i landed. drowned.

**Comment by Trip-Trap** [comment]
No replication/coordinates given
