### ISSUE TITLE
[Bug] Can see through the cave walls and through the terrain

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2044]
_Originally written by **The Zebra | 76561198202161752**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Pacy 1.5+ to be exact** 
Map: Rival_Shores

When sitting on this rock and zoomed in, you can clip your cammera through the walls and see whats outside the cave.

Location: X=-214151.984 Y=24257.275 Z=22524.404

**Comment by Predatoria** [comment]
No easy fix for this right now.  Going to close it.
