### ISSUE TITLE
[Bug] Scent

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2067]
_Originally written by **BossHog | 76561197969239706**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Rex** 
Map: Rival_Shores

No scent when sniffing. Cant pickup players scent trails even if they were right infront of me and walking. 
I belive the scent feature is broken and works 50% of the time.

**Comment by Trip-Trap** [comment]
#2027 
Same person, similarl report
