### ISSUE TITLE
[Major Bug] Issues with momentum down hills for para

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#207]
_Originally written by **IndigoBlue | 76561198083026152**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Ancestral_Plains

Para will not gain any speed at all going down a hill

**Comment by Predatoria** [comment]
Fixed next tester patch
