### ISSUE TITLE
[Quality of life] Fish floating in the desert

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2077]
_Originally written by **Meesert | 76561198069505202**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: AMD Ryzen 5 1400 Quad-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Trex** 
Map: Rival_Shores

There is a fish floating in the desert
Location: X=80048.977 Y=163394.828 Z=3032.231

**Comment by Trip-Trap** [comment]
Always has been :gun:
#1359
