### ISSUE TITLE
[Bug] Larger creatures gain momentum/speed slower

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#208]
_Originally written by **IndigoBlue | 76561198083026152**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Ancestral_Plains

The larger in growth a creature is the slower it will gain speed going down a hill

**Comment by Predatoria** [comment]
This is intended functionality.  The weight stat is directly a part of this behavior.
