### ISSUE TITLE
[Bug] Crouch bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2089]
_Originally written by **Aiyana | 76561198845247296**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: AMD Ryzen 5 4600H with Radeon Graphics         
Vendor: AuthenticAMD
GPU Brand: AMD Radeon(TM) Graphics
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Megalosaurus ** 
Map: Ancestral_Plains

Location: X=57633.684 Y=123844.813 Z=4643.304. I was lying down on a hill and pressed ctrl (which is my crouch key) and the camera angle changed even thought i was not crouching. This is not a major issue, although fixing it would be good.

**Comment by Trip-Trap** [comment]
Cant reproduce
