### ISSUE TITLE
[Bug] Stone that gets you stuck

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#210]
_Originally written by **Rinnaja | 76561198052742270**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 5500
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Map: Rival_Shores

Stehe in einen Stein fest auf der Karte Rival Shores und kommen ohne Admin hilfe nicht mehr raus

**Comment by Trip-Trap** [comment]
No coordinates, not replicatable
