### ISSUE TITLE
[Major Bug] Trials

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2110]
_Originally written by **Queenie?? | 76561198982592849**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600X Six-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2060
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ichty** 
Map: Rival_Shores

Trials reset after playing and logging out like wtf

**Comment by Trip-Trap** [comment]
A replication we have for that problem atm came by Anatze. She switched computers and would play with the same computer. Each time she switched the trials would reset on all of her creatures.

**Comment by cleafspear** [comment]
fixed
