### ISSUE TITLE
[Severe Bug] call while grab

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#213]
_Originally written by **Bulbertianus | 76561198987079439**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **as mosa target** 
Map: Rival_Shores

The mosa's main problem is still in the game. When you get grabbed you make a call, and during than you can't do anything and multiple mosa can throw you over to the next mosas, makes you deep down to drown, without any chance to fight back.

Please REMOVE the call during mosa grab! Or allow bite while calling.

**Comment by Predatoria** [comment]
This complaint is so common.  I thought it'd be immersive, but I'll just disable the distress call.
