### ISSUE TITLE
[Bug] Ichthyovenator: Sneaky Talent Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#214]
_Originally written by **Mrs. X | 76561198366522159**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA Quadro P5000
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **as Ichthy with 2/3 sneaky talent.** 
Map: Rival_Shores

With the new model of this dinosaur, currently sneaky talent is not working. The more talents invested, 2/3 or even 3/3, no noise reduction activates.

**Comment by Predatoria** [comment]
Tested in PIE.  It has a very profound and obvious effect.  I cannot reproduce any issue.
