### ISSUE TITLE
[Bug] "your egg is ready!" notif beind spammed

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#215]
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Icthyovenator** 
Map: Rival_Shores

Mated once, got one egg ready, when that egg was ready i mated again and after that started being spammed with the notif of my first egg being ready.

**Comment by Predatoria** [comment]
Should be fixed next tester patch
