### ISSUE TITLE
[Bug] Пропали минуты в испытаниях.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2152]
_Originally written by **???????????????????? | 76561198931941796**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 750 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

После обновления. Почти у всех моих друзей пропали минуты наигранные на динозавре.

**Comment by cleafspear** [comment]
[Bug] Missing minutes in tests.
After update. Almost all of my friends have lost their dinosaur minutes.

**Comment by cleafspear** [comment]
#2110 related
