### ISSUE TITLE
[Bug] Ichthy sound issues

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#217]
_Originally written by **Rexy Deku | 76561199001701496**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Rival_Shores

After eating, the Ichthy still makes sound of it eating. It should end after the animation but it doesn't.

**Comment by Predatoria** [comment]
Not a bug.  I had to cut the eat animation short due to tester feedback.  We don't have an easy way to do this currently.
