### ISSUE TITLE
[Bug] players that have the same display name will share the ID and profile picture

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#218]
_Originally written by **Cleafspear | 76561198077984700**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

*Expected Results:* players that have the same name while on the same server should be visually distinct on the tab menu/commands
*Actual Results:* when multiple players that share the exact same in game name join, they will share the same id and profile picture as the last person to join. usage of commands require usage of the steam id only to work
*Replication:*  have multiple players with the same exact name join and open the tab menu.

**Comment by Predatoria** [comment]
Should be fixed next tester patch
