### ISSUE TITLE
[Bug] cant breath

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#219]
_Originally written by **Acroom | 76561198271703096**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: AMD Ryzen 5 1600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Kronosaurus** 
Map: Ancestral_Plains

I cant breath as the kronosaurus.
Location: X=48888.695 Y=-260195.969 Z=7282.171

**Comment by Predatoria** [comment]
This location is floating above the ocean plane.  I'm not sure why they wouldn't be able to breathe, but I cannot reproduce any issues with Krono / Aquatic breathing.
