### ISSUE TITLE
[Bug] Itchy animation glitch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#221]
_Originally written by **The Fast Zebra | 76561198202161752**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Itchy** 
Map: Rival_Shores

When double taping "e" to pick up something as an itchy and you let the animation play out then crouch, you can enter a weird animation glitch where you are seen running, but at a slow walk speed.

**Comment by Predatoria** [comment]
Fixed next tester patch

**Comment by Trip-Trap** [comment]
You are unable now to stay in crouch or toggle to crouch when picking up things while crouched, exept if you are para.
