### ISSUE TITLE
[Bug] Digging sound isn't playing

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#222]
_Originally written by **Soals | 76561198378851871**_
Game Version: 1.1.956

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Orycto** 
Map: Ancestral_Plains

*Expected Results:* Ory playing its dig sound while digging
*Actual Results:* Sound for digging is missing.
*Replication:* Spawn and dig as Ory

**Comment by Predatoria** [comment]
Fixed next tester patch
