### ISSUE TITLE
[Quality of life] Stuck Point

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2220]
_Originally written by **Greiner | 76561198054680601**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **132** 
Map: Rival_Shores

*Expected Results:* 
*Actual Results:* 
*Replication:* 
Location: X=246018.641 Y=280399.438 Z=12477.577
Location: X=246018.641 Y=280399.438 Z=12477.577

**Comment by Predatoria** [comment]
Found a spot where cave mesh goes above the ground.  I fixed it.
