### ISSUE TITLE
[Quality of life] Guy is cheating

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2227]
_Originally written by **??? ??? | 76561198120962889**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Deathmatch** 
Map: Test_Performance

PlayerName:Jhon Doe, SteamID:76561198967894935
he darts like 8-9 times on crono on max charge without stoppin
After he killed me he darted another time, so i think he have something

**Comment by Thy-Vipe** [comment]
This person is most likely using the hack tool from these chinese people. We have a fix for this.

**Comment by Trip-Trap** [comment]
Closing this for now
