### ISSUE TITLE
[Bug] old model Ichti

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#223]
_Originally written by **!??????????^^ | 76561198167708012**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 3GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

After restarting the server, there was 1 egg left and the player entered it. Player was born with the old model actionator and with the old skin.

**Comment by Predatoria** [comment]
Should be fixed next tester patch
