### ISSUE TITLE
[Bug] Leaving and entering burrows places you wrong at first

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#226]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.957

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Orycto** 
Map: Ancestral_Plains

*Expected Results:* Ory being put on top of the burrow or into the burrow when entering or exiting.
*Actual Results:* Ory will be places first on top of the burrow when entering, then teleported into the burrow. Same with leaving. It will be put on top of the exit first and only after on top of the entrance.
*Replication:* Make a burrow and enter&exit it.

**Comment by Trip-Trap** [comment]
https://media.discordapp.net/attachments/678696803683663893/726752026339442748/beastsofbermuda._Screenshot_2020.06.28_-_12.52.36.59.png?width=1118&height=629

**Comment by Trip-Trap** [comment]
![grafik](https://user-images.githubusercontent.com/56919683/85945498-71686780-b93e-11ea-8bea-d6a6b13f9363.png)

**Comment by Trip-Trap** [comment]
Nm, it only seems to happen to an "older save" ory, a fresh one I made doesnt do this.
