### ISSUE TITLE
[Bug] Game kicks me out

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#227]
_Originally written by **roomi | 76561197987106223**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 590 Series
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **performance test** 
Map: Forest_Island

Dear BoB team! When I play on the Beasts of Asgard performance test level, as soon as I press and hold the Q button to smell around, my computer restarts. The first time it happened, not even Steam could log in for a few minutes. It never happened before. Thank you for your care! Yours sincerely: Roomi

**Comment by Predatoria** [comment]
Not a clue what to do with this one.
