### ISSUE TITLE
[Bug] Ungrouped Friend Buff

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#228]
_Originally written by **Vias | 76561199047537366**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Survival** 
Map: Ancestral_Plains

As an ungrouped para, I'm getting a "Near Friends" buff next to a mixpacked (admin) apa. Unsure if this is normal.
Location: X=194483.328 Y=59125.543 Z=14293.194

**Comment by Predatoria** [comment]
The Near Friends buff just means they're receiving positive comfort.  This is intended.  Next patch, however, ungrouped herbivores will stress one-another out.
