### ISSUE TITLE
[Bug] Baby Snatcher Breaking.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#229]
_Originally written by **?????d??t???Teawynage | 76561198405825456**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Pteradon & Velo mix-pack.** 
Map: Rival_Shores

We ran in too a bug within our mixpack on Lost Beasts #2. A Velo in our Ptera/Velo mixpack wasn't able to drop me after picking up me and a hatchling Velo at the same time. 

> Velo /w Baby Snatcher
> Snags both Hatchling Velo & .5 Ptera. 
> Puts Hatchling Velo Down

Which leads to being unable to Unstuck/Unjam his self when holding a .5 Pteradon.

> Had to relog too fix the bug.

**Comment by Predatoria** [comment]
I won't be able to reproduce this in PIE, but I did add a server-side check in the grab code that should prevent this.  It sounds hard to reproduce.  I'll mark it as potentially fixed.

**Comment by Trip-Trap** [comment]
Ill mark this as fixed till it gets reported again.
