### ISSUE TITLE
[Bug] Inerits displayed everytime logging onto a saved creature

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#232]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.957

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Saved Creatures** 
Map: Ancestral_Plains

*Expected Results:* Inerhits-Messages only showing up when a creature hits the relevant growth.
*Actual Results:* Every time you log in with a saved creatures all your gained inherits until that growth will be displayed on the first server tick.
*Replication:* Make a 1.2 creature. Return to save slots. Spawn in as that creature. Note that all your inerhits will be displayed on the first server tick.

**Comment by Predatoria** [comment]
Easy fix / oversight in the code.  I've fixed it next tester.

**Comment by Predatoria** [comment]
Trying another fix at this next patch

**Comment by Predatoria** [comment]
Finally think I found and fixed all this for next patch.

**Comment by Predatoria** [comment]
Finally fixed I hope
