### ISSUE TITLE
[Quality of life] Itchy drinking animation glitch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#233]
_Originally written by **The Fast Zebra | 76561198202161752**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Itchy** 
Map: Rival_Shores

As an Itchy, if you drink water, the tounge can been seen going through the head.

**Comment by Predatoria** [comment]
Fixed this next tester.  Gonna have to scrutinize Akshat's animations more closely.  This one even did it on the Adult ichthy.

Same issue / solution as Megalo
