### ISSUE TITLE
[Bug] Icon Glitching

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#234]
_Originally written by **Gavin | 76561198254999852**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Apato** 
Map: Rival_Shores

*Expected Results:* Icons stay above all players at all times.
*Actual Results:* Icons glitch to the center or corner of the screen.
*Replication:* Join a group and move your camera around.

**Comment by Trip-Trap** [comment]
Pretty sure we fixed that last patch or this patch.
