### ISSUE TITLE
[Major Bug] ur moms vv

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2361]
_Originally written by **Antler | 76561198382534092**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1650 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **i died and ur mom peed on me  ff f fg fbdbfghgfhfg hgf gh fhh fg** 
Map: Ancestral_Plains

so ur mom ate my poop salad and i fricked her good

**Comment by cleafspear** [comment]
spam report,
