### ISSUE TITLE
[Major Bug] rightasrain fell through ground

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#237]
_Originally written by **Daruvik | 76561197994232174**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: AMD Ryzen 9 3900X 12-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1080 Ti
GPU Driver Info: Unknown
Num CPU Cores: 12
===================*
Context: **Velociraptor near portal mountain** 
Map: Rival_Shores

rightasrain was a velociraptor trying to jump up the mountain with the portal on it, and slid down the mountain and fell through the map, and died from it.

**Comment by Predatoria** [comment]
No coordinates.  I won't be able to find or fix this.
