### ISSUE TITLE
[Enhancement] Rock Mesh

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#238]
_Originally written by **Stormy H Temptess | 76561198163272695**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 970
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

Location: X=87987.141 Y=-91912.266 Z=3358.016
The rock mosh here is a little awkwards I can fit my whole small meg below it and be Unseen.

**Comment by Peter22FIN** [comment]
I don't know how to fix this one. It seems like these types of rocks are using old models and textures anyway. I don't know what can cause this kind of collision problem. Is the problem in scaling?

**Comment by Predatoria** [comment]
These specific rocks have very poor collision meshes.  I replaced them with SM_Cliff_05, which is a very similarly shaped rock with better collision.
