### ISSUE TITLE
[Major Bug] Unable to eat or use abilities as baby elasmo, oxygen at zero

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#239]
_Originally written by **Smol Gwennie (*???????*) | 76561198027675835**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2060 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Elasmosaur** 
Map: Ancestral_Plains

Rebinding did not fix the issues and it caused me to starve to death as a fresh nest baby elasmo.

**Comment by Predatoria** [comment]
Cannot reproduce elasmo not being able to eat while out of air.  Not being able to attack / consume fish is normal.  Not a bug.
