### ISSUE TITLE
[Bug] Foliage weight

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#240]
_Originally written by **vapidwhisper | 76561198850680053**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 620
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Para** 
Map: Rival_Shores

picking up foliage to eat, in my case smaller ferns, and then dropping them causes the "healed for x weight" notification to pop up anytime someone eats or grabs the dropped foliage

**Comment by Predatoria** [comment]
Fixed this next tester patch.
