### ISSUE TITLE
[Major Bug] Collision destection meshing

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2404]
_Originally written by **Saikoro | 76561198289530919**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx  
Vendor: AuthenticAMD
GPU Brand: AMD Radeon(TM) RX Vega 10 Graphics
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **An Ory, i wanted to see the view** 
Map: Ancestral_Plains

This Rock face cliff, I was on top and hovered over the land then fell straight through. 
Location: X=13171.332 Y=-82715.016 Z=6537.985

**Comment by Predatoria** [comment]
These assets have poor collision.  No easy fix beyond not using them on future maps.  I'm going to close this.
