### ISSUE TITLE
[Bug] Ory able to dig in attack mode

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#242]
_Originally written by **Spooky Spooks | 76561198040926907**_
Game Version: 1.1.959

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

When Ory is in attack stance they can press z to dig upwards one tile. It does not give the player any dirt when they dig like this.

**Comment by Predatoria** [comment]
Fixed this for next patch
