### ISSUE TITLE
[Bug] Ory landing while standing spazzes legs

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#244]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.959

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Orycto** 
Map: Ancestral_Plains

*Expected Results:* When landing have the feet stay on the ground
*Actual Results:* If Ory lands standing its feet will go up and down on the ground.
*Replication:* Spawn as ory and hit jump. Observe it's landing.

**Comment by Predatoria** [comment]
We'll need to get Akshat to do the same treatment for the ory legs that he did for the jumps on the other animals.

**Comment by Predatoria** [comment]
I changed this for next patch.  Should be fixed.

**Comment by Peter22FIN** [comment]
Now right arm is broken https://youtu.be/mm00lI6Huts

**Comment by Predatoria** [comment]
Fixing it
