### ISSUE TITLE
[Severe Bug] theres a little hole that you can go under the map

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#247]
_Originally written by **cluelesspredator55 | 76561198386082808**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **i went to go hide and i saw it i saw that xD** 
Map: Rival_Shores

undermapping spot to go in there
Location: X=103649.141 Y=138255.938 Z=-194.541

**Comment by Trip-Trap** [comment]
Can still get in att the bottom

**Comment by cleafspear** [comment]
still present on 1130

**Comment by Predatoria** [comment]
Placed a rock there, fixed!
