### ISSUE TITLE
[Quality of life] Glitched off cliff and died

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2470]
_Originally written by **ashaul | 76561199013871455**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand:         Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 650
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Para** 
Map: Rival_Shores

I was walking up a hill, then i glitched off and lost my 1.1 para

**Comment by Trip-Trap** [comment]
Server lag issue
