### ISSUE TITLE
[Bug] ory entering a burrow and reciving knockback from a tornado

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#248]
_Originally written by **Cleafspear | 76561198077984700**_
Game Version: 1.1.959

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory** 
Map: Ancestral_Plains

*Expected Results:*  when the ory is in the process of entering a burrow, and starts reciving knockback from a tornado, it shoud cancel the burrow entering action
*Actual Results:* you will finish the enter burrow action but will be above the mesh. you cannot dig a burrow or perform any dig actions while in this state. 
*Replication:* dig a burrow and have a tornado approch you, right before when you start getting knockback, enter the burrow. you will visually fly off but after the fade out, you will appear above the mesh. but with the burrow fog.

**Comment by Predatoria** [comment]
This also sort of happens if you get knocked back from other sources such as apato trample, though I still entered the burrow properly.  I'm putting some code on this that is similar to what happens if you receive regular damage, but for knockback damage.  It should fix it.
