### ISSUE TITLE
[Bug] Ory able to enter borrow while digging another borrow

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#249]
_Originally written by **Spooky Spooks | 76561198040926907**_
Game Version: 1.1.960

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ory** 
Map: Ancestral_Plains

When digging a borrow entrance next to another entrance you can press e to enter an existing borrow while still digging the new one.

**Comment by Predatoria** [comment]
should be fixed next tester
