### ISSUE TITLE
[Bug] killing

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2497]
_Originally written by **beasts of dinos | 76561199064887723**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **as acro** 
Map: Test_Performance

in deahtmatch server milkshakes lacie kept killing me more then twince and also soembody else spawnkilled.

**Comment by cleafspear** [comment]
issue is a player report, not a bug. closed
