### ISSUE TITLE
[Bug] Burrow entrances made in this location sometimes dont spawn a bottom

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#250]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.960

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Orycto** 
Map: Ancestral_Plains

https://media.discordapp.net/attachments/606210258817515562/728742557403578388/unknown.png?width=1118&height=629

Dig burrowentrances in this landscape dip here.

Location: X=-31595.496 Y=-6010.065 Z=15329.803

**Comment by Predatoria** [comment]
Fixed next patch!

**Comment by Predatoria** [comment]
I remember confirming this during a test session with Cleafspear.  Closing it.
