### ISSUE TITLE
[Bug] mosa S grade thrash damage

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2506]
_Originally written by **Cleafspear | 76561198077984700**_
Game Version: 1.1.1095

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **mosa** 
Map: Rival_Shores

*Expected Results:* thrashing a packmember with S grade friendship should not cause damage
*Actual Results:* thrashing a packmember with S grade friendship causes damage and friendship loss
*Replication:*  thrash a packmate with s-grade friendship

**Comment by Predatoria** [comment]
Fixed it next tester patch!
