### ISSUE TITLE
[Bug] Tab Menu Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2508]
_Originally written by **Marine | 76561198060143556**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: AMD FX(tm)-8350 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **As any dino** 
Map: Rival_Shores

*Expected Results:*  Actions Menu to work properly when pressing "Tab"
*Actual Results:* No "Actions or any drop down on UI appears occasionally
*Replication:* Pressing Tab sometimes will show no UI "Actions" drop down

**Comment by Trip-Trap** [comment]
Pretty sure thats intentional. Hitting tab once opens the menu without interactions availble and twice enables actions.

**Comment by Thy-Vipe** [comment]
That looks like normal behaviour indeed.
