### ISSUE TITLE
[Bug] When Ory crouches it does not play the digging animation 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#251]
_Originally written by **Spooky Spooks | 76561198040926907**_
Game Version: 1.1.960

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ory** 
Map: Ancestral_Plains

Crouch down in a tunnel. Walk up to a wall and tunnel into it like normal. You'll se no animation plays when digging.

**Comment by Predatoria** [comment]
Fixed next patch.
