### ISSUE TITLE
[Bug] Solo ory groups have 2 members automatically

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#252]
_Originally written by **Detestation | 76561198019845935**_
Game Version: 1.1.960

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory** 
Map: Ancestral_Plains

*Expected Results:* Group should only have one member
*Actual Results:* It has two members
*Replication:* Spawn as ory and make a group alone
https://youtu.be/p6OZ9MctIl8

**Comment by Peter22FIN** [comment]
Groups that have more than 2 orys show 2 too

**Comment by Predatoria** [comment]
Fixed it next patch!  The 2 was coming from the 'player group count' widget not finding Ory's icon, and not executing code that set the widget's counter.  It defaults to 2 if the code fails because it's just the default.
