### ISSUE TITLE
[Bug] Velo sometimes not playing sounds when entering ory borrow

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#253]
_Originally written by **Spooky Spooks | 76561198040926907**_
Game Version: 1.1.960

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Velo** 
Map: Ancestral_Plains

As a velo enter an Ory borrow, sometimes the sound effect of digging in does not play. This bug happens when the velo has 0/3 sneaky.

**Comment by Predatoria** [comment]
fixed next tester patch.  Sound ref got set for ory only by accident
