### ISSUE TITLE
[Major Bug] Elasmo able to bite Ory while its inside its burrow 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#254]
_Originally written by **Spooky Spooks | 76561198040926907**_
Game Version: 1.1.960

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Elasmo** 
Map: Ancestral_Plains

As elasmo you can come onto land, press your ability key to lock onto the ory inside of the ground. You will not be able to pick them up, but if you bite when the Elasmo is locked onto the ory you an damage and kill it.

**Comment by Predatoria** [comment]
That is so spooky.  Fixed it!
