### ISSUE TITLE
[Bug] flying

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#255]
_Originally written by **Duckinbulldog18 | 76561199013476408**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1660
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **tara** 
Map: Rival_Shores

couldnt get off the ground to try and fly with danger around

**Comment by Predatoria** [comment]
Probably injured / unaware of how injury effects flight.
