### ISSUE TITLE
[Bug] Leaving group causes borrow icons to vanish 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#256]
_Originally written by **Spooky Spooks | 76561198040926907**_
Game Version: 1.1.961

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ory** 
Map: Ancestral_Plains

When you are an ory with a borrow down and you click leave group all borrow entrance icons will vanish. As soon as you start digging a new entrance the old borrow entrance icons will appear again.

**Comment by Predatoria** [comment]
Fixed it next patch!
