### ISSUE TITLE
[Bug] Unable to dig borrows at 5,000 Z, 15,000 Z, etc

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#257]
_Originally written by **Spooky Spooks | 76561198040926907**_
Game Version: 1.1.961

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ory** 
Map: Ancestral_Plains

*Expected Results:* 
Being able to dig borrow in open, unobscured land
*Actual Results:* 
Digging between 5,000 z - 5,030 / 5,020 z, 15,000 - 15,030 / 15,020 Z. etc. Prevents the ory form placing down a borrow.
*Replication:* 
Go to any of the Z cords and attempt to borrow.

**Comment by Predatoria** [comment]
This is a duplicate.  Has been fixed next patch.
