### ISSUE TITLE
[Major Bug] no sound

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#258]
_Originally written by **AriAnn141 | 76561198260549683**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 5500
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Map: Rival_Shores

there will be sound on the homescreen but once im in game i cant hear any audio :(

**Comment by Predatoria** [comment]
Not sure how to reproduce this, but hopefully Vipe's config variable rework will flush this out.

**Comment by Trip-Trap** [comment]
Vipe did the rework. Closing this report for now.
