### ISSUE TITLE
[Severe Bug] cheat or bug discomfort injection

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#260]
_Originally written by **Bulbertianus | 76561198987079439**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **sai** 
Map: Rival_Shores

Sadly can't explain too well, but how can a 1.1-1.2 acro with 18 bleed damage cause 20-30 comfort INSTANTLY by ONE bite on a 1.5 sai while an other 1.5 sai next to it on S rank. The other sai had 90+ comfort the whole time, so it cannot be just intimidation effect. It's more looks like as a discomfort injection via cheat/hack or critical game abuse.

This happened on the "Lost Beast 2" server. No player name can be given :/

**Comment by Predatoria** [comment]
Not a clue where to start with this one.  I suspect it's just balance issues / user error / stuff like that, rather than an actual bug.  I'm going to close this.
