### ISSUE TITLE
[Bug] Lying or sleeping

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#261]
_Originally written by **Robert | 76561197992906293**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **yes** 
Map: Rival_Shores

When I lie down and sleep next to someone, everyone sees me lying or sleeping, but when they get in the water and come back, they already see me standing, even though I'm still lying or sleeping.
It gets in the way when we're trying to stay hidden.

**Comment by Predatoria** [comment]
Sounds like a net relevance issue.

**Comment by Predatoria** [comment]
It is.  I can reproduce this in PIE.

**Comment by Predatoria** [comment]
It's been fixed.  bIsSitting and bIsLaying need to replicate with the initial bunch.  They're currently set with multicasts.
