### ISSUE TITLE
[Bug] Spontaneous egg breaking

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2620]
_Originally written by **queen_peach | 76561199103264443**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

Multiple times eggs were broken in a nest with no one attacking or using special abilities near them. It sounded like the eggs were breaking away from where the broken eggs were found, if that's relevant.

**Comment by Predatoria** [comment]
Duplicate
