### ISSUE TITLE
[Bug] Eggs breaking out of nowhere

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2621]
_Originally written by **???{BS} Petra | 76561198147583936**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: AMD Athlon(tm) II X4 630 Processor
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1060 3GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **nesting** 
Map: Rival_Shores

I was sitting with eggs in my nest and then they just cracked withiout anyone biting them its a bug of some sort.

**Comment by Katze-eng** [comment]
It's happens because of the one player destroying the eggs when turning it's internet off

**Comment by Predatoria** [comment]
Probably low comfort.
