### ISSUE TITLE
[Bug] Ptera in para heard

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#264]
_Originally written by **Spooky Spooks | 76561198040926907**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 960
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Para** 
Map: Ancestral_Plains

Just saw a ptera in a para heard. I have no idea how they did it, but it was patched that bug its back again.

**Comment by Trip-Trap** [comment]
No way of knowing how it got there or how to reproduce.

**Comment by Predatoria** [comment]
It was probably admin command related.  Unless we hear of a bug with a more direct description of players grouping when they shouldn't be able to without the assistance of admins forming the group, I'm going to close this.
