### ISSUE TITLE
[Quality of life] Mate request refused recently

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#265]
_Originally written by **Lt. Windsor | 76561197985416607**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Doesn't matter which creature.** 
Map: Rival_Shores

Me and a friend have both refused a mate request from one another, once, by mistake and can't send request to each other regardless the creature and we have waited almost 2 days. And I couldn't find any solution for this matter or how long you are supposed to wait.

**Comment by Thy-Vipe** [comment]
The timer is supposedly about 15 minutes, and should reset when a server restarts regardless. Unless the timer to block  these is no longer ticking, which is entirely possible, I'm not sure how this would be happening.

**Comment by cleafspear** [comment]
system completly redone
