### ISSUE TITLE
[Enhancement] talent points

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2654]
_Originally written by **laniesparty2013 | 76561198877024192**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

wont let me upgrade swift claws over 1

**Comment by Trip-Trap** [comment]
Could have not enough points or were missing 2/3 on attached talents
