### ISSUE TITLE
[Bug] Cannot be Female

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#266]
_Originally written by **Hotdog | 76561198298189256**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8600 CPU @ 3.10GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Apato** 
Map: Rival_Shores

Every time I try to spawn a Female Apato it will make me a male whenever I spawn in.

**Comment by Predatoria** [comment]
I heard this mentioned in tester chat.  Unfortunately, I have absolutely no idea how to reproduce it.

**Comment by Predatoria** [comment]
Closing this due to not being able to reproduce it.
