### ISSUE TITLE
[Bug] missing mesh collision, mesh visable.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#268]
_Originally written by **Cleafspear | 76561198077984700**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

location has a hole that you can jump through to get behind the mesh. the visiual mesh is there but is missing its collision componet.
Location: X=226460.000 Y=196772.891 Z=9156.413

**Comment by Predatoria** [comment]
Placed a rock, should be fixed
