### ISSUE TITLE
[Major Bug] UE4 Issue with water reflection not working unless using TAA.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#27]
_Originally written by **Vipe | 76561197998584510**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: AMD Ryzen 9 3950X 16-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2080 Ti
GPU Driver Info: Unknown
Num CPU Cores: 16
===================*
This is a note for later. We disabled Screen space reflections on water for now, due to UE4 issue as follows:
https://issues.unrealengine.com/issue/UE-93360

-Water flickers if not using TAA. Hopefully they'll address this soon.

**Comment by Predatoria** [comment]
We pushed a patch addressing this stuff this morning.  Can we mark this as fixed?  @Trip-Trap
