### ISSUE TITLE
[Major Bug] update on the mosa state jam 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#270]
_Originally written by **Dr Nox | 76561198060480535**_
Game Version: 1.1.962

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Mosasaurus** 
Map: Test_Performance

It seems to be caused when an ichthy repeatedly darts out of your mouth while you thrash them. Maybe ask in test requests for more replication?

**Comment by Trip-Trap** [comment]
From above mentioned issue 269:

Expected Results: Mosa should be able to bite/call after killing something using thrash
Actual Results: Mosa is unable to bite/call after killing something using thrash.
Replication: Grab something and thrash it to death as mosa.
