### ISSUE TITLE
[Bug] No collision tree

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#272]
_Originally written by **Teglami | 76561197989405185**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: AMD Ryzen 5 1500X Quad-Core Processor          
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

*Expected Results:* collision
*Actual Results:* no collision
*Replication:* when you walk to the tree you can walk through

Location: X=209124.641 Y=38786.297 Z=21996.320

**Comment by Trip-Trap** [comment]
Same bug that has been reported previously on testers and there is no known fix for it at the momen.
If you get knockback at any point in your play session you are able to glitch through trees.

**Comment by Thy-Vipe** [comment]
Is that a map specific bug or a gameplay one? that looks like some asset missing collision, here?

**Comment by Trip-Trap** [comment]
This is a gameplay bug. This could happen to any tree asset. Basically if a player receives knockback they can glitch through trees, pred was unable to find a solution for that iirc

**Comment by cleafspear** [comment]
for this specific bug, its an asset missing its collision

**Comment by Predatoria** [comment]
These specific palms were marked as not woody in the foliage table.  I've fixed it and they should all now have collision.
