### ISSUE TITLE
[Bug] Snowy Pit Trap

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2738]
_Originally written by **TheGayestSammy | 76561198883407332**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Pentium(R) CPU 4417U @ 2.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 610
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Ory** 
Map: Rival_Shores

Slid into the little cranie by the waterfal at Snowy and I was stuck, I've tried everything. Jumping on the rocks, attempting to dive under the water, and even having someone punt me. Im stuck stuck. Im an Ory.

**Comment by Predatoria** [comment]
Added a few rocks to fix up what I believe to be the hole
