### ISSUE TITLE
[Quality of life] Lurdu mouth issues

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#274]
_Originally written by **Cuddles27 | 76561198288299039**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 760
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

The lurdus upper teeth are attatched to the bottom jaw

**Comment by Trip-Trap** [comment]
Known. Won't be fixed, till Lurdu gets its remodel.
