### ISSUE TITLE
[Major Bug] Wipe of creatures after buying the game

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#276]
_Originally written by **Cynro | 76561198088782554**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: AMD Ryzen 5 1600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 960
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Anything** 
Map: Ancestral_Plains

So to be short, I played this game for a few days using my friends copy with the steam family, today i decided i wanted to play from my account and brought the game for my self, when i joined again none of my creatures were there, joined every server i had been playing on and everything was empty, I thought it would be important to report this!

**Comment by Trip-Trap** [comment]
This is intended behaviour. The creatures save on the owned account, not on the alt.
