### ISSUE TITLE
[Major Bug] disconnecting players that wait the timer in Return to Menu have pawn remain in game

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#277]
_Originally written by **Cleafspear | 76561198077984700**_
Game Version: 1.1.964

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

*Expected Results:* when waiting out the "return to menu" timer the pawn should be removed from play within 1-2 seconds of the player disconnecting
*Actual Results:*  after waiting the timer and sucessfully disconnecting, the pawn will remain in play for 50 seconds-1 minute
*Replication:* when in non admin standard play and with 2 clients- have one client disconnect by returning to menu while in view of the second client, waiting out the timer. when the client disconnects, start a timer, the pawn will dissapear within 50 seconds to 1 minute after the player safe logging.

**Comment by Thy-Vipe** [comment]
Is that a 1:1 ? What I am suspecting first hand is the timer being handled client side instead of server side. This part of the project is pretty old, it might be doing stuff like that.

**Comment by cleafspear** [comment]
this is a 1:1, was able to confirm it again on the current released tester version.

**Comment by cleafspear** [comment]
issue resolved after testimg on 1130
