### ISSUE TITLE
[Bug] ory lag-hit detection sphere too small, rejects hits from far 50% of tail

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#278]
_Originally written by **Cleafspear | 76561198077984700**_
Game Version: 1.1.964

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **ory vs velo/ory** 
Map: Rival_Shores

*Expected Results:* attacking ory on the tail should only possibly trigger jag hit-reject when attacking the far tip of the tail
*Actual Results:* you can bite the tail of the ory from the tip of the tail to about halfway to the base and the hits will register to the local player but ge rejected by the server and not be replicated to the other client.
*Replication:*  with 2 cleints, enable hitbox view and start biting the ory, working the bite hit-sphere up the tail. you will find the ory will not take damage untill the far edge of the bite sphere is halfway up the tail

**Comment by Predatoria** [comment]
Fixed next tester
