### ISSUE TITLE
[Bug] Alt is only moving the head for client and not server side

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2782]
_Originally written by **Desknight | 76561198138190538**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **As an apato** 
Map: Rival_Shores

Rarely when using alt it only moves it clientside and not serverside which is very detrimental to apatos allowing them to get hit from far away when their head is nowhere near the opponent.
I have no idea how to replicate it and it seems practically random.
It lasts permanently until you use unjam or rejoin the server.

**Comment by Trip-Trap** [comment]
#3056
