### ISSUE TITLE
[Bug] eggs left in a burrow that is destroyed in a flood will remain under the map mesh

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#279]
_Originally written by **Cleafspear | 76561198077984700**_
Game Version: 1.1.964

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Egg** 
Map: Rival_Shores

*Expected Results:* when the eggs are in a burrow state, have them teleported to the nearest surface entrance if the burrow node they rest on becomes flooded
*Actual Results:* when the node floods and is destroyed, the eggs are left under the mesh untill either the flood raises high enough for the eggs to exit the mesh or they are hatched, leaving the hatched player under the mesh
*Replication:*  build a burrow and lay some eggs within the burrow, perferrably at a low point. force a flood that is high enough to destroy the burrow, the eggs will be left where the burrow and nest was, and will float to the surface of the flood, given time.

**Comment by Predatoria** [comment]
This should be fixed next patch!
