### ISSUE TITLE
[Major Bug] Skins not saving reliably

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#28]
_Originally written by **Vipe | 76561197998584510**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: AMD Ryzen 9 3950X 16-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2080 Ti
GPU Driver Info: Unknown
Num CPU Cores: 16
===================*
Context: **Any** 

*Expected Results:* Skin save properly when creating and saving skins
*Actual Results:*  Skins do not always save, and it seems random
*Replication:* Unknown for the most part.

**Comment by Thy-Vipe** [comment]
Should be fixed - closing until further notice.
