### ISSUE TITLE
[Bug] Ory burrowing issue

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#280]
_Originally written by **HibiscousDragon | 76561198130963972**_
Game Version: 1.1.964

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics Family
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Ory** 
Map: Rival_Shores

Dug a burrow near a cave entrance, got stuck inside the flat rock at cave entrance. could not dig or move, but could enter and exit
Location: X=145125.000 Y=189375.016 Z=3278.542

**Comment by Predatoria** [comment]
I made the burrow placement requirements a bit more stringent to disallow placements like these now

It now gives the error  'The dirt here is too hard to dig through' in this specific spot.  Other areas seem to be burrowable.
