### ISSUE TITLE
[Bug] Burrow entrance error

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#281]
_Originally written by **HibiscousDragon | 76561198130963972**_
Game Version: 1.1.965

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics Family
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Ory** 
Map: Rival_Shores

*Expected Results:* Burrow is placed and useable
*Actual Results:* Half the burrow is placed and cannot be interacted with
*Replication:* Unknown, happed from within tunnel on 2.0+ ory

**Comment by Predatoria** [comment]
This should be fixed next patch
