### ISSUE TITLE
[Bug] new group bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#282]
_Originally written by **GOOBA GOOBA | 76561198386082808**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

this might be a bugg or weird but sometimes when wwe start a new group people are already in group when they log in group they were in group and we didn't invite him or her we just wanted to start a new one it happened multiple times aswell. 

So how to reproduce this bug i think is when you have to be in group before then you start a new group and you get on it's like a 50/50 they will be in group not. I  think that how to reproduce it because this happened like 20 times in this update.

**Comment by Predatoria** [comment]
I know what's going on.  Should be fixed next patch!
