### ISSUE TITLE
[Bug] Ptera

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#283]
_Originally written by **Martijn | 76561197970762634**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand:        Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 980
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Ancestral_Plains

playing on my ptera and water stays at 100% for several minutes now already

**Comment by Predatoria** [comment]
It was probably raining.  Likely user error / misunderstanding the mechanics
