### ISSUE TITLE
[Enhancement] bird vs nado

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#284]
_Originally written by **Bulbertianus | 76561198987079439**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **ptera** 
Map: Rival_Shores

Make tornado ignore ptera, same as it not target apas.
Reason: Pteras used to "lure" the nado away, ruining some game elements of... the elements.

**Comment by Predatoria** [comment]
Easy change.  I went ahead and did it.
