### ISSUE TITLE
[Major Bug] Falling under the map

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#285]
_Originally written by **Pinks | 76561198223367248**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand:         Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Velo** 
Map: Ancestral_Plains

Jumped on a big rock by cave entracnce -the one by the bridge over a river with waterfalls. Falling in one of the cracks in the rock caused breaking under the map and drowning.

**Comment by cleafspear** [comment]
closed due to not enough information
