### ISSUE TITLE
[Bug] Egg in a burrow can click leave burrow button and teleport away from parents

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#287]
_Originally written by **Detestation | 76561198019845935**_
Game Version: 1.1.967

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory** 
Map: Rival_Shores

*Expected Results:* You should not be able to have leave burrow button as an egg and escape parents
*Actual Results:* You have the button and clicking it will teleport you to a spawn point alone
*Replication:* Lay eggs in burrow, posses one and click leave burrow button

**Comment by Predatoria** [comment]
Easy fix.  Fixed next tester patch
