### ISSUE TITLE
[Bug] Switching save from an egg that is in burrow mode forces the next dino into burrow state

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#288]
_Originally written by **Detestation | 76561198019845935**_
Game Version: 1.1.967

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory** 
Map: Rival_Shores

*Expected Results:* Switching dino from burrow egg should apply non-burrow state
*Actual Results:* Switching dino from burrow egg applies burrow state
*Replication:* Possess an egg, parent moves the egg into the burrow so the egg is in burrow mode, switch from the egg into other dino

**Comment by Peter22FIN** [comment]
That state doesn't clear up with unjam or by switching the character and when ever player exits the burrow world is in darkness. View seems to be stuck on that egg and if you carry it, the egg is like lantern.

**Comment by Peter22FIN** [comment]
https://youtu.be/fAm34OQwmjw

**Comment by Peter22FIN** [comment]
Egg also chirps when ever the other dino makes a call (1, 2, 3, 4, 5)

**Comment by Peter22FIN** [comment]
Killing the egg cures the blindness

**Comment by Predatoria** [comment]
Should be fixed next patch!
