### ISSUE TITLE
[Quality of life] Player list should sort alphabetically

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#29]
_Originally written by **DJZ | DJZ's ID*_
Game Version: 1.1.938

*===== System Specs =====
irrelevant
===================*
*Expected Results:* Tab menu sorts the players alphabetically by name
*Actual Results:* Tab menu sorts players by ingame ID instead of name
*Replication:* Spawn in, open the tab menu and look at the players

**Comment by Predatoria** [comment]
Working on a fix for this!
