### ISSUE TITLE
[Major Bug] Hole in map

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#290]
_Originally written by **The Fast Zebra | 76561198202161752**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Pacy** 
Map: Rival_Shores

When walking into the side of the cliff here, you can go into a hole that can't be seen from the outside.
Location: X=-88835.039 Y=328552.938 Z=16228.925

**Comment by Trip-Trap** [comment]
cant find it, assume its fixed then
