### ISSUE TITLE
[Quality of life] Raining in cave

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#291]
_Originally written by **Neko-Chan666 | 76561199029037154**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **while it is raining** 
Map: Rival_Shores

when it is raining, it is raining in the cave 
Location: X=-166588.344 Y=19736.193 Z=23238.438

**Comment by Predatoria** [comment]
Can't fix this very easily.  Won't be addressing.
