### ISSUE TITLE
[Quality of life] Unable to locate meat

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2933]
_Originally written by **Khost | 76561197983348762**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Mosasauros** 
Map: Rival_Shores

Everytime I use the smell on the Mosasaurous, it detects nothing to eat including fish nor does it detect any onther creatures. A sea creature would still be able to detect prey such as a shark does.

**Comment by Trip-Trap** [comment]
Fish smelling is not doable in with the new ocean, and i assume they thought scent clouds would appear in water?
