### ISSUE TITLE
[Major Bug] lag and bug 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2936]
_Originally written by **Reaper | 76561198348778021**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

a second time i have lagged through a rock and lost a 1.0 trope

**Comment by Trip-Trap** [comment]
Lag so closing this
