### ISSUE TITLE
[Major Bug] flood

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#294]
_Originally written by **lilcheese | 76561199013589566**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: AMD Ryzen 5 1400 Quad-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 960
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

so i was logging for a flood then when the water touched me the timer went back to 59 seconds then bc of that i lost my 1.43 sai and the timer had 3 secs left

**Comment by Trip-Trap** [comment]
Not a bug, if you get moved, be it by knock back or my water rising the timer will reset.
