### ISSUE TITLE
[Bug] megalosaurus

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#295]
_Originally written by **[??] KOlabZz [??] | 76561198440679897**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 4600
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **original version(don't public test)** 
Map: Rival_Shores

when my friend bite me in head or tail. Damage don't go to me.

**Comment by Predatoria** [comment]
Fixed next public patch and fixed on tester.  Lag tolerance has been too small.
