### ISSUE TITLE
[Bug] Zooming In For Nothing 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2958]
_Originally written by **Albatross_WingsOFFire | 76561199046378579**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **In a cave climbing rocks to get away from a flood.** 
Map: Rival_Shores

As a velo it will zoom in to where you can't see anything but feathers in radmon places near rocks. It makes it hard to see when trying to climb the rocks.

**Comment by Trip-Trap** [comment]
Would need to know which rocks.
