### ISSUE TITLE
[Quality of life] HUD negatives effects.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#296]
_Originally written by **piu piu rektail | 76561198929616982**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 3GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

pls add a negative effects icons to the HUD, is annoying checking the menu evertime.

**Comment by Predatoria** [comment]
This is planned, but nontrivial
