### ISSUE TITLE
[Quality of life] rexes and acros teaming

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#2961]
_Originally written by **techninja85 | 76561198057614688**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **as an apatosaurus** 
Map: Ancestral_Plains

there was these acros and one rex and they already had food and they killed my apato

**Comment by Trip-Trap** [comment]
Not a bug o<o
