### ISSUE TITLE
[Quality of life] Water clipping through terrain

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#298]
_Originally written by **The Fast Zebra | 76561198202161752**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Megalo** 
Map: Rival_Shores

When the pond here ontop of the jungle island is very full, the water clips through the ground
Location: X=193516.250 Y=42348.906 Z=17384.047

**Comment by Predatoria** [comment]
Edited the landscape mesh.  Fixed!
