### ISSUE TITLE
[Bug] Palm Tree Issues

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#299]
_Originally written by **Gavin | 76561198254999852**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Herbivore (Para)** 
Map: Rival_Shores

*Expected Results:* All palm trees should be able to be picked up or knocked down.
*Actual Results:* Some palm trees aren't able to be picked up or knocked down.
*Replication:* Attempt to pick up or knock down palm trees (Jungle Island on RS)

**Comment by Predatoria** [comment]
I fixed a few different palm trees recently.  Given this is not specific to which palm tree is causing the problem, I'll assume it's fixed and close this.
