### ISSUE TITLE
[Bug] Velo Butt Cam

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#30]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Velo** 

*Expected Result* Being able to zoom your camera out fully on a 2.2 velo.
*Actual Result* If you zoom your camera out too far the camera will get stuck in your belly. You have to zoom in again to be able to get out of your belly.
*Replication* Spawn as velo. Set your growth to 2.2. Zoom out the camera slowly. Note that after a certain point the camera will be stuck beneath your velos belly.

(has been like this since before 1.1.919)

**Comment by Trip-Trap** [comment]
Fixed, see issue #31 instead
