### ISSUE TITLE
[Quality of life] Map Hole

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#300]
_Originally written by **EchoAlien | 76561198015374176**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand:        Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 970
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Pachy** 
Map: Rival_Shores

A player managed to shove themselves into an area I didn't even know existed, and when I teleported to them to get them out, I had problems getting out of there with the spectate cam LOL. I fished around to try to get where I think was the exact entrance to the area where they get stuck, a rock would probably do the trick.
Location: X=-205688.219 Y=25573.424 Z=23451.551

**Comment by Trip-Trap** [comment]
i hope i looked at the right location. looks fixed
