### ISSUE TITLE
[Bug] Reflect Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3012]
_Originally written by **Diablo | 76561198450263549**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 3GB
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Sai** 
Map: Rival_Shores

I can still be hit while using my reflect ability even when it's up

**Comment by Trip-Trap** [comment]
Can happen for rep delay, not enough otherwise if they were hit in the middle of having the shield up
