### ISSUE TITLE
[Bug] don´t see Pictures of the team mate in 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3022]
_Originally written by **Broken Name | 76561198019756783**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 970
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **I don´t see  thee Pictures of my team mates(rudel)** 
Map: Rival_Shores

don´t see Pictures of the team mate in

**Comment by Trip-Trap** [comment]
Could have icons disabled
