### ISSUE TITLE
[Quality of life] Mega's hitbox

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#303]
_Originally written by **Fertseshoy | 76561198236289692**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **as ptera** 
Map: Test_Performance

The second attack of megas is broken. It sometimes does double damage, especially to pteras, which ends as broking pteras model and rolling it on the ground. I also think megas' have too big hitbox to their second attack.

**Comment by Predatoria** [comment]
Not related to megalo.  It's a ptera-specific issue, which I believe we fixed on tester already.
