### ISSUE TITLE
[Bug] Plant Satiation Issue

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#304]
_Originally written by **Desknight | 76561198138190538**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Eating plants as herbivore** 
Map: Rival_Shores

Eating different types of plants at once causes it to give you satiation from one of the random plants. If you eat a tree and a bush it sometimes gives you zero satiation due to the bush not giving satiation even though you ate a tree at the same time.

**Comment by Predatoria** [comment]
Fixed it next tester
