### ISSUE TITLE
[Enhancement] Rex Call

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3047]
_Originally written by **Jaw | 76561198106584025**_
Game Version: 1.1.1099

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 950
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Rex ** 
Map: Islatitania

Rex Location Call is not sync with his anymation

**Comment by Trip-Trap** [comment]
New sounds arent in yet
