### ISSUE TITLE
[Bug] Grades being one above

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#305]
_Originally written by **Jxck | 76561198799229491**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

So everytime I get a grade with someone, it'll be like you've just earned c grade with this person, but when you go into the tab menu, it shows as B grade.

**Comment by Predatoria** [comment]
Fixed next tester
