### ISSUE TITLE
[Quality of life] flooding

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#306]
_Originally written by **ArkWatch | 76561199024238113**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 620
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

im trying to spawn as a megalosaur but the flooding is way too hight that i keep drowning each time i spawn in even with aqua infinity 3/3 i ccant make it to the top

**Comment by Predatoria** [comment]
Won't be fixing this.  It's just part of the game / bad luck for the player right now.
