### ISSUE TITLE
[Major Bug] Broken Hitbox

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3063]
_Originally written by **Diablo | 76561198450263549**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 3GB
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Saichania** 
Map: Rival_Shores

As the Sai literally anything can hit my tail but I can't hit it.

**Comment by Trip-Trap** [comment]
Possible solution on it on tester. Last tail segment was removed.
