### ISSUE TITLE
[Enhancement] better ocean graphics please

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3079]
_Originally written by **iifluffy_kawaii | 76561198851198762**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) Iris(R) Plus Graphics
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

ocean is still to my computer wont move and really bad ocean graphics on my lenovo laptop

**Comment by Trip-Trap** [comment]
Intel card. Known, cant be changed.
