### ISSUE TITLE
[Bug] Lurd teeth moving

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#308]
_Originally written by **Gling | 76561198120397137**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **calling as a lurd** 
Map: Rival_Shores

During all the calls the lurd's teeth detach from it's skull and float freely around it's mouth.

**Comment by Predatoria** [comment]
This will be fixed when we rework lurdu.
