### ISSUE TITLE
[Quality of life] stuck/glitched gore

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3097]
_Originally written by **vZulu | 76561198220680681**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: AMD Ryzen 9 4900HSS with Radeon Graphics        
Vendor: AuthenticAMD
GPU Brand: AMD Radeon(TM) Graphics
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **forest** 
Map: Forest_Island

gore was spawned, but was pawned underneath the map
Location: X=-112855.516 Y=-43522.309 Z=7261.550

**Comment by Trip-Trap** [comment]
command issue
