### ISSUE TITLE
[Bug] Velo Butt Cam 2.0

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#31]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Velo** 

*Expected Results:* Camera staying normal when sitting or sleeping as a velo.
*Actual Results:* If you are over 2.2 your camera will disappear in your velos belly if you zoom out too far, if you are in sitting or sleeping.
*Replication:* Spawn in a velo, grow it to 2.2 lie down. Zoom in and out as far as you can get with the camera

**Comment by Trip-Trap** [comment]
Updated to major bug, as this will happen to velos at 1.0 already. This makes it difficult to rest and look around when the camera is fully zoomed out, making their vision limited while trying to gain back hp.

**Comment by Trip-Trap** [comment]
Got fixed with the camera fix from patch Patch 1.1.940. Recheck issue after crouch camera gets readded
