### ISSUE TITLE
[Major Bug] floating water bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3109]
_Originally written by **Liam Sutte | 76561198021873543**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: AMD Ryzen 9 5900X 12-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 3070
GPU Driver Info: Unknown
Num CPU Cores: 12
===================*
Context: **playing as 1.16 velo climbing hill toward water source in jungle** 
Map: Rival_Shores

*Expected Results:* not being able to drink from it, just visual glitch
*Actual Results:* was able to fully drink and treat section of floating water as if it were the swamp water source
*Replication:* able to drink from floating water multiple times on same velo
Location: X=140704.797 Y=46917.570 Z=4912.690

**Comment by Predatoria** [comment]
Duplicate.  Fixed in another report.
