### ISSUE TITLE
[Bug] 100 shelter on a open rock

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#311]
_Originally written by **Stormy H Temptess | 76561198163272695**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 970
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

Up top of this rock face:
Location: X=-38805.570 Y=-2744.846 Z=13595.552

You get 100% shelter, at least as a velo , Just standing out on the open.

**Comment by Predatoria** [comment]
The collision on those is awful.  I can't do much about it other than not use them on future maps.
