### ISSUE TITLE
[Bug] Injury's speed slow down not applying correctly 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#312]
_Originally written by **IndigoBlue | 76561198083026152**_
Game Version: 1.1.975

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Tested on acrocanthosaurus** 
Map: Rival_Shores

When you take a large chunk of injury instantly, you will not lose any speed due to the injury slow down until either a server tick occurs, or you stop or start sprinting

Tested by using setstats to give myself 100 injury while using autorun to sprint as I entered the command

**Comment by Predatoria** [comment]
This is only console command-specific.  Taking in-game injury works properly.  I'm going to close this since it's only happening with the console command.
