### ISSUE TITLE
[Major Bug] floating water sliver x3

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3127]
_Originally written by **Liam Sutte | 76561198021873543**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: AMD Ryzen 9 5900X 12-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 3070
GPU Driver Info: Unknown
Num CPU Cores: 12
===================*
Map: Rival_Shores

*Expected Results:* fixed
*Actual Results:* not fixed, still able to drink from it withough depleting the resource
*Replication:* 3rd time now on apa
Location: X=139679.250 Y=47024.688 Z=5502.108

**Comment by Predatoria** [comment]
Fixed in another report.
