### ISSUE TITLE
[Bug] I can't switch my Dino

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#313]
_Originally written by **(MH)Dewp101 | 76561198952601497**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

So i clicked Creature Select to change my dino and i had to wait 50seconds. When it hit 43seconds it restarted back to 50sseconds and it keeps doing it over and over

**Comment by Predatoria** [comment]
I bet the player was swimming while trying to log out.  Either that, or under attack.

**Comment by Predatoria** [comment]
Either way, I can't seem to reproduce this regardless.
