### ISSUE TITLE
[Bug] Too old to swap skins message pops up in Creature Creation

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#315]
_Originally written by **Detestation | 76561198019845935**_
Game Version: 1.1.976

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **with new Creature Creation UI** 
Map: Rival_Shores

*Expected Results:* You should not see "Too old to swap skins" message in Creature Creation
*Actual Results:* After switchin between species the message pops up on the right upper corner
*Replication:* Go to Creature Creation, click any species and then choose any other species instead.
https://youtu.be/JBRl8OGUWrQ

**Comment by Predatoria** [comment]
Fixed next tester
