### ISSUE TITLE
[Bug] Taking an egg and spawning as any other creature before parent accepts the egg gives you default skin

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#316]
_Originally written by **Detestation | 76561198019845935**_
Game Version: 1.1.976

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Egg/Hatchling** 
Map: Rival_Shores

*Expected Results:* You should always inherit parent's skin or get a mix
*Actual Results:* You can hatch with default skin
*Replication:* Ask to get into an egg. While it's waiting for respond quickly select any other creature and hit start. When you get accepted you will have default skin.

**Comment by Peter22FIN** [comment]
Also caused this: https://sentry.io/organizations/sastrei-studios/issues/1746002700/?project=1501648&query=is%3Aunresolved

**Comment by Peter22FIN** [comment]
https://sentry.io/organizations/sastrei-studios/issues/1746002700/events/b5d61980d8db447490a28ea8dc1089bc/?project=1501648&query=is%3Aunresolved
Timing needs to be perfect. Very tricky to replicate.

**Comment by Predatoria** [comment]
I put a fix for this next tester.  Start button disables while a pending request to join a nest exists.
