### ISSUE TITLE
[Enhancement] Pachy animation error

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#318]
_Originally written by **sXENO | 76561198126672892**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 960
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

While they are sitting, Pachys have a weird tremble on their neck, probably because a mistake on the neck curves, trying to make the breathing on the idle animation

**Comment by Predatoria** [comment]
Fixed next tester
