### ISSUE TITLE
[Bug] Elusiveness Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#319]
_Originally written by **kittentoes | 76561198059673414**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: AMD Ryzen 5 1600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Elasmo** 
Map: Rival_Shores

*Expected Results:* For the cloak to break when attacking/eating fish.
*Actual Results:* The cloak does not break when attacking or eating fish, it only breaks during sprinting.
*Replication:* I don't know if it's the same for 1/3 Elusiveness, but it is for 2/3 Elusiveness.

**Comment by Predatoria** [comment]
Not a bug.  Intended functionality.
