### ISSUE TITLE
[Major Bug] Ancestral plains having bad performance (worse)

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#32]
_Originally written by **Vipe | 76561197998584510**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: AMD Ryzen 9 3950X 16-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2080 Ti
GPU Driver Info: Unknown
Num CPU Cores: 16
===================*
Ancestral plains runs about ~20 FPS lower than Rival shores. This might be due to LOD issues and needs looking into.

**Comment by Trip-Trap** [comment]
An outtake of the client log from Ancestral Plains:
![grafik](https://user-images.githubusercontent.com/56919683/84711681-2aa26700-af67-11ea-8526-b5f4f9139d7e.png)

**Comment by Thy-Vipe** [comment]
@Predatoria  Trip Trap's post is what I was referring to. This is likely causing issues and frame drops on cooked.

**Comment by Predatoria** [comment]
FPS seems to have significantly improved on tester, observed by myself, TripTrap, and Detestation.  Closing and marking as fixed!
