### ISSUE TITLE
[Bug] Can't move forward

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#322]
_Originally written by **BETJurassicAN | 76561198152087650**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Beasts of Bermuda** 
Map: Rival_Shores

I remapped my controller and now the forward key says none now. Hope you get this and it gets fixed. Have a wonderful day.

**Comment by Predatoria** [comment]
Potentially force-fixed by Vipe next tester patch

**Comment by Trip-Trap** [comment]
Non testable. Will close this issue for now as it has not appeared to have happened so far.
