### ISSUE TITLE
[Bug] Ory standing in air when placing dirt back

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#323]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.978

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Orycto** 
Map: Rival_Shores

*Expected Results:* Ory playing the dirt animation where it stands.
*Actual Results:* When Ory is filling up a tunnel it will be put slightly above ground, same is true for digging but that one is less noticable. Filling up the tunnel makes Ory noticably stand in the air.
*Replication:* Spawn as Ory, start digging a tunnel. Swing the camera to watch ory from the side while doing this. Now fill up the tunnel and watching from the side you can see Ory stand in air.

**Comment by Predatoria** [comment]
This is intentional.

**Comment by Predatoria** [comment]
Actually, I've been working on another bug related to ory falling out of its burrow and believe to have a better solution than this.  I'm marking this as potentially fixed, though it's also a duplicate of issue 331.
