### ISSUE TITLE
[Quality of life] Sai pick up animation

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#325]
_Originally written by **The Fast Zebra | 76561198202161752**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Sai** 
Map: Rival_Shores

*Expected Results:* Sai eating animation playing when picking up objects while moving
*Actual Results:* Sai doesn't play the eating animation when picking stuff up while moving
*Replication:* Spawn in as sai, try to pick up something while moving

**Comment by Trip-Trap** [comment]
Pachy&ory&lurdu seem to have this problem as well

**Comment by Predatoria** [comment]
Fixed all four next tester patch
