### ISSUE TITLE
[Quality of life] Not a bug, but could be an improvment.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3255]
_Originally written by **CookieMushroom | 76561198086062052**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

I don't know anywhere else to put this so i wrote it here, sorry.

should put a fanction that helps slow down while flying, it's quite hard to land while flying fast.
so like flapping fowered to slow down, that's all i got tbh,
please consider this

**Comment by Trip-Trap** [comment]
Use key "e" is for breaking. Might need something later that makes it easier for new players to understand the controls
