### ISSUE TITLE
[Bug] Some burrow nodes not diggable

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#326]
_Originally written by **Peri.exe | 76561198048552921**_
Game Version: 1.1.979

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GT 1030
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ory on Public test** 
Map: Rival_Shores

This happens near rocks. There is no red highlight, and it doesn't say the ground is too hard. When I burrow, it played the animation and consumes ability, but the nose doesn't get dug

**Comment by Predatoria** [comment]
Wondering if this is user error.  I saw some players being confused trying to use ability key to dig, and the UI currently doesn't prompt the player if they're trying to place a node on top of a node.  Going to close this due to lack of information.
