### ISSUE TITLE
[Bug] Leaving water Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3268]
_Originally written by **BossHog | 76561197969239706**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

When leaving water with trop holding shift space bar the trop gets stuck below the surface.. specially when holding gore.
Location: X=-93248.281 Y=355016.250 Z=3823.222

**Comment by Trip-Trap** [comment]
Usually costs too much stam to take off, which probably was the problem here.
