### ISSUE TITLE
[Major Bug] Ory burrow exit into rock

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#327]
_Originally written by **The Fast Zebra | 76561198202161752**_
Game Version: 1.1.979

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Ory** 
Map: Rival_Shores

When making an exit above a rock that does not phase underground, the ory can burrow an exit/entrance inside the rock. When the ory exits the burrow through that entrance/exit, you are inside the rock. You can walk out of the rock to escape it.

**Comment by Predatoria** [comment]
Fixed next tester
