### ISSUE TITLE
[Bug] Clone Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3275]
_Originally written by **Crispy Christy! | 76561198988669162**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **So i made me a realistic albino skin until i pressed start! then i saw i was still on the species selection so i selected velo again then i spawned as my old albino one! and a clone appeared wich was the velo that i pressed on when i saw i didnt spawn in! ** 
Map: Rival_Shores

*Expected Results:* 
*Actual Results:* 
*Replication:* 
Location: X=31597.758 Y=242315.562 Z=5352.794

**Comment by cleafspear** [comment]
this clone issue has been resolved
