### ISSUE TITLE
[Bug] ORY ERROR

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#328]
_Originally written by **sXENO | 76561198126672892**_
Game Version: 1.1.979

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 960
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **DEV TEST - Ory** 
Map: Rival_Shores

Max burrows per player is bugged. There is actually no limit. If you first make burrows on the surface and then connect them underground, there is no limit (i made a 13 entrance tunnels solo)

**Comment by Predatoria** [comment]
This is unfortunately a chunking issue I'm likely not going to bother fixing.  I may just change the wording on the talent or something.
