### ISSUE TITLE
[Bug] desert cave entrance hole

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3284]
_Originally written by **disaster strikes | 76561198040981157**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2070 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **mega, .9ish, on the Rival Shores map** 
Map: Rival_Shores

if you go to the desert cave entrance and climb up the right side of the ramp and hop ontop of the slab thats above the entrance, you will sometimes fall through a hole and end up under the map.

**Comment by Predatoria** [comment]
I'm not sure where this area is, and cannot find an issue in the desert cave.
