### ISSUE TITLE
[Bug] Combat: Died while entering burrow

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#329]
_Originally written by **Shain | 76561198142835886**_
Game Version: 1.1.979

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: AMD Radeon R7 250 Series
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **orycto** 
Map: Rival_Shores

An itchy attacked me and I entered a burrow. They killed me as I entered, and my gore ended up inside the burrow!

**Comment by Predatoria** [comment]
Attacks stop you from entering a burrow, but with good timing, there will be a disagreement on two separate clients.  Won't fix this.
