### ISSUE TITLE
[Quality of life] Global density invisible to eggs/adults

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3297]
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.1108

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Apatosaurus ** 
Map: Rival_Shores

It'd be nice to be able to adjust it when you log in as a adult creature who cant edit the skin, the bar is invisible when you cant edit your skin.

**Comment by Trip-Trap** [comment]
Pretty sure thats intended, skin customization is off after 0.8 and nestling should not be able to turn off their skin with it
