### ISSUE TITLE
[Quality of life] revinded

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#33]
_Originally written by **RaZingxProoZ | 76561198106156975**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: AMD FX(tm)-8350 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 970
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
i logged before the restart
i was a 1.1 acro and now i am back at .98

**Comment by Thy-Vipe** [comment]
**Note** Not a bug / server save ticks every 7 minutes by default, and certain servers overwrote this setting to be longer.
