### ISSUE TITLE
[Bug] Falling through map as ory

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#330]
_Originally written by **Death | 76561198228120624**_
Game Version: 1.1.979

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: Radeon (TM) RX 480 Graphics
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Ory** 
Map: Rival_Shores

I was building up in a hole with dirt next to a log and i guess it glitched out and fell into the void of the world then landed in water until i was then tele'd back up to the surface.

**Comment by Predatoria** [comment]
Duplicate of 334.
