### ISSUE TITLE
[Bug] orycto

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#331]
_Originally written by **KOlabZz | 76561198440679897**_
Game Version: 1.1.979

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 4600
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **public test** 
Map: Rival_Shores

когда ты закапываешь нору, ты поднимаешься в воздух.

**Comment by Predatoria** [comment]
Not a bug.  This is intentional / necessary.

**Comment by Predatoria** [comment]
Actually, I changed how this works to try and fix another bug.  This shouldn't happen any longer.
