### ISSUE TITLE
[Bug] Got stuck in a rock while digging a hole.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#332]
_Originally written by **AtlaS | 76561198059548065**_
Game Version: 1.1.979

*===== System Specs =====
CPU Brand: AMD Phenom(tm) II X6 1055T Processor
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

I was digging a big hole and after I dug one of the segments, a large rock appeared right on top of me and I got stuck in it...
Location: X=-77401.500 Y=72612.844 Z=7354.320

**Comment by Predatoria** [comment]
Should be fixed next tester
