### ISSUE TITLE
[Bug] Crashing in burrow

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#333]
_Originally written by **Death | 76561198228120624**_
Game Version: 1.1.979

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: Radeon (TM) RX 480 Graphics
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Rival_Shores

Crashing in your burrow makes you fall through the world.

**Comment by Predatoria** [comment]
Kind of confused by this.  Do they mean a literal clientside crash?
