### ISSUE TITLE
[Bug] Ory falling out of borrow into underground mesh

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#334]
_Originally written by **Renieken | 76561198042502397**_
Game Version: 1.1.979

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 980 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ory** 
Map: Rival_Shores

while attempting to dig a burrow to the top of the ptera mountain i fell out of the borrow and landed on one of the circle rock meshes that clip into the terrian and got stuck in burrow mode while outside a burrow 
Location: X=230147.406 Y=201806.625 Z=6463.939

**Comment by Predatoria** [comment]
Should be fixed next tester patch.  This one was tough.

**Comment by Trip-Trap** [comment]
Only issues with falling out of a burrow atm are connected to other orys digging beside you. Will close this one
