### ISSUE TITLE
[Quality of life] If you die in a burrow the burrow "view" is removed and you can see underneath the map.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#336]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.980

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Death in Burrow** 
Map: Rival_Shores

*Expected Results:* If you are in the death screen for the burrow state view to still be active.
*Actual Results:* Burrow state view will be set to false.
*Replication:* Make a burrow, go into that burrow, die in that burrow.

**Comment by Predatoria** [comment]
Implemented a work-around next tester patch
