### ISSUE TITLE
[Bug] acro roar can be fired twice turing the inital roar

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#337]
_Originally written by **Cleafspear | 76561198077984700**_
Game Version: 1.1.980

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **acro** 
Map: Rival_Shores

*Expected Results:* while roaring as an acro, you should not be able to start a second roar effect untill the first one is compleated (brought to mt by lazulie)
*Actual Results:*  if you have 3/3 intim roar and 3/3 persistance at 1.2 growth, you can get the roar to fire twice within quick succession of 1 roar
*Replication:* with a 1.2 acro, set your growth to 1.2, intimidating roar to 3/3 and persistance to 3/3. go to a target and spam your ability key. you will on occasion start 2 roars within quick succession, doing double stamina damage to the target.

**Comment by Predatoria** [comment]
I'm confused.  There's no reason why players cannot currently use the roar twice in a row to drain more stamina, and with these talents the cost just gets to be less than half of your ability, allowing use of this twice in a row.

This isn't a bug.

**Comment by cleafspear** [comment]
oh, the issue is you can fire the roar within about half a second from the same player.
aka the montage is not setting in time so the action can be performed twice before its restricted.

**Comment by Predatoria** [comment]
I think this was fixed and forgotten
