### ISSUE TITLE
[Bug] Baby information dosen't go away

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#338]
_Originally written by **LuminecentEyes | 76561198039125456**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **When I sniffed my hatchling** 
Map: Rival_Shores

When you have a hatching and sniff them with 3/3 gp sometimes the kids info won't go away, not too big of a deal but can get a little annoying.

**Comment by Trip-Trap** [comment]
duplicate #348
