### ISSUE TITLE
[Bug] cave jam location

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3381]
_Originally written by **Cleafspear | 76561198077984700**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **velo 1.2** 
Map: Rival_Shores

the rock on the wall can jam a player when walked into, effects small creatures.
Location: X=-190842.766 Y=16915.342 Z=25901.346

**Comment by Predatoria** [comment]
Added more rocks to block this location
