### ISSUE TITLE
[Bug] Certain palm tree model inedible to .7+ apa, can't walk through or knock it over

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3383]
_Originally written by **Tricksy | 76561198036250511**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **a 1.1 male apa** 
Map: Rival_Shores

*Expected Results:* Be able to eat and/or knock over any and all trees, including palm trees, over .7 growth as apa
*Actual Results:* Cannot eat or knock over certain palm trees. Some palm trees can be eaten and knocked over, some cannot
*Replication:* Be a .7+ apa, eat as many palm trees as possible, notice some palm trees say they can be eaten but cannot be eaten or knocked over, regardless of your size or the tree's size. I was 1.1+ apa testing this at desert oasis on Rival Shores.
Location: X=63731.078 Y=220934.500 Z=5850.111

**Comment by Predatoria** [comment]
Just fixed these, they should now be edible
