### ISSUE TITLE
[Major Bug] Dark sphere around your creature have loop holes

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#339]
_Originally written by **Anatze | 76561198302304278**_
Game Version: 1.1.982

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **all creatures in a burrow** 
Map: Rival_Shores

When your creature stand in a burrow, you can change your resolution like "FOV 120" in console and then you can see outside of your black sphere

**Comment by Predatoria** [comment]
Fixed next tester patch
