### ISSUE TITLE
[Severe Bug] your game is dog

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3391]
_Originally written by **IckyStickyOils | 76561198328586334**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 750 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

FIX your  game- the fact it flooded and i was sitting then floods me where i start floating i couldnt stop sitting under water then i drowned- your dev team is dog your game is dog and you guys never fix anything.

**Comment by Trip-Trap** [comment]
o7 good day sir/mam
