### ISSUE TITLE
[Quality of life] Sudden drop in FPS on Rival Shores

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#34]
_Originally written by **????????????e ????????????? | 76561198144202180**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 4600
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Herbivore** 

Many of my friends and i have noticed and tested that whenever someone picks up any sort of plant (tree, fern, etc.) there's a slight stutter/drop in fps. fps drops have also been noticed randomly at the snowy area on rival shores.

**Comment by Trip-Trap** [comment]
Duplicate #40
