### ISSUE TITLE
[Bug] Ory clips through some rock and stones

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#340]
_Originally written by **Detestation | 76561198019845935**_
Game Version: 1.1.982

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory** 
Map: Rival_Shores

*Expected Results:* Creatures can't go inside rocks
*Actual Results:* Ory can easily just walk into some rocks and hide with 100% shelter
*Replication:* Following location has great rocks to test with https://youtu.be/BrOcOlEELG8
Location: X=-172020.578 Y=47524.336 Z=30687.449

**Comment by Predatoria** [comment]
Fixed it next tester.  Rocks in video were using simple collision and it had a lot of holes in it
