### ISSUE TITLE
[Quality of life] Lurdos are fishkillers

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#341]
_Originally written by **felix-schulz1 | 76561198144855414**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3600 6-Core Processor              
Vendor: AuthenticAMD
GPU Brand: Radeon RX Vega
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **everytime with lurdo players** 
Map: Rival_Shores

Lurdos has much too high swimming speed and are trying to kill every water creature.

**Comment by Predatoria** [comment]
Please don't use the in-game bug tracker for balance suggestions.
