### ISSUE TITLE
[Bug] Krono can call while charging a lunge

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#342]
_Originally written by **IndigoBlue | 76561198083026152**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Ancestral_Plains

If you broadcast after starting to charge a lunge, the call sound will blot out the sound of the lunge charging, making it extremely hard to tell if a krono is starting to lunge

**Comment by Predatoria** [comment]
I'll change it.
