### ISSUE TITLE
[Bug] Dirt clump appearing on exit/entrance whenever there is digging inside the burrow

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#343]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.985

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Orycto Burrowing** 
Map: Ancestral_Plains

*Expected Results:* Entrance or exit not being filled with the dirt used to animate digging out or filling in burrow.
*Actual Results:* Dirt clump appearing whenever there is digging inside the burrow on the exit/entrance.
*Replication:* Dig an entrance. Have one ory stand on the entrance and another dig inside the burrow. Watch it happen.

**Comment by Predatoria** [comment]
I'm not really sure what you mean here.

**Comment by Trip-Trap** [comment]
Turns out this only happens if you are the owner of the burrow. So you made an entrance and start digging inside it. Another player standing outside of it will see these dirt clumbs forming on the entrance.
Here what I mean:
https://www.youtube.com/watch?v=w2oVbosCXR4

**Comment by Predatoria** [comment]
I see it now.  I've fixed it.
