### ISSUE TITLE
[Major Bug] All-female egg glitch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#344]
_Originally written by **The Frog Archer | 76561198201256457**_
Game Version: 1.1.985

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Ancestral_Plains

*Expected Results:* 50/50 split between male and female babies
*Actual Results:* Way to get 100% Female ory
*Replication: Go into an ory egg and before hatching press B. You should always hatch as a female and get the female nesting prompt
Location: X=-147341.609 Y=-8489.048 Z=5590.843

Could be a major balancing glitch with people wanting all female

**Comment by Predatoria** [comment]
I've been able to get males doing this.  Nonetheless, I'll disable the nest key while in an egg just in case.

**Comment by Trip-Trap** [comment]
*probably* fixed
