### ISSUE TITLE
[Quality of life] Rain overlay while in burrow

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#346]
_Originally written by **The Fast Zebra | 76561198202161752**_
Game Version: 1.1.985

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Ory ** 
Map: Ancestral_Plains

*Expected Results:* Rain should not be seen while inside a burrow
*Actual Results:* Rain can be seen on the screen while inside the burrow
*Replication:* Have a storm, go inside the burrow, rain can be seen

**Comment by Predatoria** [comment]
Fixed next tester patch
