### ISSUE TITLE
[Bug] Herbs behaving strange when put down

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#347]
_Originally written by **Shain | 76561198142835886**_
Game Version: 1.1.985

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: AMD Radeon R7 250 Series
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **orycto public test (orycto)** 
Map: Ancestral_Plains

When I pick up a flower and put it down on some ground surfaces they look like they "replant" themselves and become unable to be picked up oor eaten. When I put the plants down inside burrows or on rocks, they behave normally.
Location: X=109814.750 Y=-135443.719 Z=4390.231

**Comment by Predatoria** [comment]
This is a duplicate we confirmed fixed already
