### ISSUE TITLE
[Severe Bug] Invisible Velo

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#349]
_Originally written by **??? Jerr's ??? Mods ??? | 76561198353867105**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx  
Vendor: AuthenticAMD
GPU Brand: AMD Radeon(TM) RX Vega 10 Graphics
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Beasts of Bermuda** 
Map: Test_Performance

I died while I was on the character points screen as a Velo, and now I can't see the velociraptor anymore. It's invisible. I reinstalled my game and deleted my game files, but still no luck.

**Comment by Trip-Trap** [comment]
Another person had that problem. They were able to get the model back by deleting their safe folders and verifiyng. Closing this report for now
