### ISSUE TITLE
[Bug] Fuzziness after the latest pacth even when the command is used.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#35]
_Originally written by **A Tanga in the woods | 76561198072009229**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **After patch** 

Updated the game, Settings : Anti aliasing  - Low    Method = None
The command posted in announcements isn't working anymore, it did work before the patch thouh. When the flickering was happening.

**Comment by Trip-Trap** [comment]
The anti aliasing commands do not work anymore after they got put back as settings. I believe that is intended, correct me if not.

**Comment by Predatoria** [comment]
After the patch we deployed this morning, one should be able to disable AA through the in-game UI for graphics options.  I'm able to properly disable my AA in-game now and the blurriness goes away.  Should this be closed?

**Comment by Trip-Trap** [comment]
The options work. Will close this issue as fixed.
