### ISSUE TITLE
[Bug] Hovering over a saved skin applies it but doesn't save it on the character

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#350]
_Originally written by **Detestation | 76561198019845935**_
Game Version: 1.1.991

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **with skins** 
Map: Rival_Shores

*Expected Results:* When exiting O screen the dino should always have the skin that is saved on creature and visible to others
*Actual Results:* Hovering over a skin applies it to you but doesn't save it, meaning when ever you switch characters you get the previous skin.
*Replication:* Take any dino, apply any skin and hit start. Go to O screen and hover over any saved skin and hit O to exit the screen. Hitting O and checking your colors you can see that it applied the saved skin BUT when you go to character selection and back to that dino you see that it didn't save the skin on the dino. Growing to 0.8 locks the old skin even if you have fake saved skin applied to you.
https://youtu.be/NtOvCiWO6Go
https://youtu.be/nhvFdWdzyq0

**Comment by cleafspear** [comment]
this will need looking into, still relevant on the current patch 1.1.1050

**Comment by cleafspear** [comment]
fixed.
