### ISSUE TITLE
[Bug] white rectangle graphical glitch upon death

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3500]
_Originally written by **00 | 76561198042400990**_
Game Version: 1.1.1113

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **after death, ory and rex by a rex** 
Map: Rival_Shores

After dying, a white rectangle shows up on screen in the lower left corner, behind the buttons of "character," "search groups," and "options."

**Comment by TeaTimeJess** [comment]
Known issue, was not able to reproduce on v. 1.1.1116 by starving

**Comment by Trip-Trap** [comment]
Can't reproduce it. From the sound of it it only happens on the death screen. We updated the picture behind the options, so it might not be loading for some people?

**Comment by Predatoria** [comment]
This has been confirmed fixed on tester, I believe.
