### ISSUE TITLE
[Quality of life] Rex Op

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3505]
_Originally written by **Gavin | 76561198254999852**_
Game Version: 1.1.1113

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Rex** 
Map: Rival_Shores

Rex does 1,500 dmg at 1.2 with its special ability meanwhile Apato does around 1,300 at 1.4 (which doesn't even matter because the 1.2 damage cap.) That is a big problem.

**Comment by TeaTimeJess** [comment]
Not a bug - v. 1.1.1116 reworked.
