### ISSUE TITLE
[Bug] Clone any dino with creature creation

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#351]
_Originally written by **Detestation | 76561198019845935**_
Game Version: 1.1.991

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Clone** 
Map: Rival_Shores

*Expected Results:* There should only be one dino per player
*Actual Results:* You can have a duplicate ghost dino
*Replication:* Go to dino creation and select any dino and any skin and hit start. Go to save selection (hope that you get same location where you are currently) and click new slot. Create the duplicate but instead of hitting start hit the back arrow and select your previous creature instead.
https://youtu.be/LAl4sT6zX_M

**Comment by Peter22FIN** [comment]
Crash caused by clones: https://sentry.io/organizations/sastrei-studios/issues/1827825241/events/8bf2d531e6ba4421b039f995dcc58f65/

**Comment by Predatoria** [comment]
Fixed next tester

**Comment by Predatoria** [comment]
Not sure if this ever got tested or not.  Nonetheless, I'm pretty sure it's fixed.
