### ISSUE TITLE
[Quality of life] Tree Coliding

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3516]
_Originally written by **Inferno Wolf | 76561198446141660**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: AMD FX(tm)-8120 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GT 1030
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Pteranodon** 
Map: Ancestral_Plains

I was flying and then I got stuck in a tree then died from ashort fall

**Comment by TeaTimeJess** [comment]
Map AP - not testable, but not a bug as tree collision is intended.
