### ISSUE TITLE
[Bug] Apatosaurus tail whip hitbox hits too high

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#352]
_Originally written by **Stimky | 76561198219851059**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2060 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Flying over an apatosaurus, as a pteranodon** 
Map: Rival_Shores

I was flying above an Apatosaurus, when they used their tail whip action. I was hit by the tailwhip despite being realistically out of reach height wise from their tail

**Comment by Trip-Trap** [comment]
Could have been due to lag. Admitedly the end tail-hit-box is a bit large for the tail tip.
![grafik](https://user-images.githubusercontent.com/56919683/90159744-1e812d00-dd91-11ea-8f20-70a659912fe2.png)

**Comment by Trip-Trap** [comment]
Might have been due to lag too. Closing for now
