### ISSUE TITLE
[Major Bug] invs velos

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3526]
_Originally written by **{DoNuT}kframe74 | 76561198848231078**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: AMD A6-7310 APU with AMD Radeon R4 Graphics    
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GT 720
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

i took a velo egg when i hatched i was invs and my parents were two then when i reloged i couldnt move

**Comment by Trip-Trap** [comment]
Should be fixed now that the new patch is out. Will close this report
