### ISSUE TITLE
[Quality of life] Icthy Shimmer bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#353]
_Originally written by **Ra'va | 76561198039772275**_
Game Version: 1.1.993

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Icthy** 
Map: Rival_Shores

Claws and spikes colour region seems to be stuck on brown for me

**Comment by Trip-Trap** [comment]
Either can't reproduce or was fixed in the recent patch
