### ISSUE TITLE
[Quality of life] No Burrow Icon

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#354]
_Originally written by **Rexy Deku | 76561198950550896**_
Game Version: 1.1.994

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Playing Ory** 
Map: Rival_Shores

I logged the Ory I was on (the one that originally made the tunnel entrance) to go to creature select, made a new ory, and spawned in. When I was added back to the group that I was a part of, I could no longer see the icon for the burrow entrance.

**Comment by Trip-Trap** [comment]
This is normal as that Ory is not the original owner of that entrance so does not have the icon. Idk if intended or not tho. Will not close this issue for now.
