### ISSUE TITLE
[Quality of life] Ory Burrow Icon

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#355]
_Originally written by **Rexy Deku | 76561198950550896**_
Game Version: 1.1.994

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Rival_Shores

(This is in addition to the other report on it) My other group mate no longer can see the burrow icon either. My other ory was the party leader and was the on that made the original burrow entrance. I don't know if that has anything to do with it.

**Comment by Trip-Trap** [comment]
Same issue just further info #354
