### ISSUE TITLE
[Quality of life]  skill windows, character settings, and other pop-ups

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#356]
_Originally written by **Pineapple Pie | 76561198069731250**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: AMD FX(tm)-6300 Six-Core Processor             
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1660 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 3
===================*
Map: Rival_Shores

Переделайте эти окна, чтобы они не открывались на весь экран и не терялось управление. Сделайте как в мморпг, чтобы было много маленьких окошек и было видно перосонажей

**Comment by cleafspear** [comment]
translation by google
[Quality of life] skill windows, character settings, and other pop-ups

Redesign these windows so that they don't open in full screen or lose control. Make it like in MMORPG so that there are many small windows and characters are visible

**Comment by cleafspear** [comment]
closed but saved for consideration
