### ISSUE TITLE
[Bug] spawnkilling

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3560]
_Originally written by **Dinogirl | 76561199064887723**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **as rex** 
Map: DM_Caldera

gida (short for the name) spawnkilled me 2 times justk illed me a third time

**Comment by TeaTimeJess** [comment]
Not a but - moderator issue.

**Comment by cleafspear** [comment]
not a bug
