### ISSUE TITLE
[Major Bug] piles of ccrystals despawning

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#358]
_Originally written by **Squish Bee | 76561199038664058**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

I'm not quite sure what could be causing this. But after collecting a large pile of crystals, and leaving them there for a bit, the whole pile despawns.

**Comment by Predatoria** [comment]
I'm not sure if the player just left them there for half an hour or something.  That would cause them to despawn, but is intended behavior.
