### ISSUE TITLE
[Bug] Using tab in the Creature Creator menu makes the cursor disapper, only relogging fixes it

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#359]
_Originally written by **Renieken | 76561198042502397**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 980 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **creature creator** 
Map: Rival_Shores

*Expected Results:* 
Returning to the game after alt-tabbing for a moment while in the creature creator, being able to keep interacting with the interface
*Actual Results:* 
After returning to the game after alt tabbing for a moment the in-game cursor was stuck on the camera and was unable to return to interacting with the interface
*Replication:* 
Alt-tab while in the creature creator menu.

**Comment by Trip-Trap** [comment]
using the "tab" key (which is used to show the player list) makes the cursor disappear and its not possible to bring it back by hitting tab again.
