### ISSUE TITLE
[Quality of life] Sensivtivity problem ingame

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#36]
_Originally written by **0verload | 76561198318156808**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
this used to happen before as well: i will change my sensitivity but then if i take an egg or log on a different dino my sensitivity will go back to default and yes i do click on apply but it doesnt change anything

**Comment by Predatoria** [comment]
Sounds to me like the setting isn't saving or loading properly.  I'm going to investigate.

**Comment by Predatoria** [comment]
I spoke with Vipe.  He says he plans to redo our config variables in the future, and to ignore this for now.

**Comment by Predatoria** [comment]
Vipe pushed a fix for this next tester patch
