### ISSUE TITLE
[Bug] hole in the map 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#361]
_Originally written by **king dong | 76561198211808745**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 3GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **oryctodromeus** 
Map: Rival_Shores

Location: X=224508.344 Y=282772.125 Z=4411.779

at the entrance to a specific cave in the archipelago behind the desert island there's a hole where you can get under the map.

**Comment by Trip-Trap** [comment]
Seems to be fixed
