### ISSUE TITLE
[Bug] invizible velo

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3629]
_Originally written by **littengamer1112 | 76561198992690060**_
Game Version: 1.1.1085

*===== System Specs =====
CPU Brand: AMD A8-7410 APU with AMD Radeon R5 Graphics    
Vendor: AuthenticAMD
GPU Brand: AMD Radeon R5
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

so i was playing on wwd i spawn in as a velo and i cant see my velo

**Comment by Trip-Trap** [comment]
fixed with new patch
