### ISSUE TITLE
[Quality of life] burrow dirt in trees?

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#363]
_Originally written by **disaster strikes | 76561198040981157**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2070 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **just saw it near a burrow, cant explain LOL** 
Map: Rival_Shores

not sure if intentional but found dirt in the trees near a burrow
Location: X=-81479.117 Y=85763.953 Z=7010.667
Location: X=-81479.117 Y=85763.953 Z=7010.667

**Comment by Predatoria** [comment]
Not really a bug, but there should be less of this now that dirt paddies spawn less frequently.
