### ISSUE TITLE
[Bug] Flood spawn

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#364]
_Originally written by **Stormy H Temptess | 76561198163272695**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 970
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

During a mega extinction flood all the new spawn players are getting Shoved far under the map.

**Comment by cleafspear** [comment]
fixed on tester
