### ISSUE TITLE
[Bug] Cant Dock the Battle Log

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#365]
_Originally written by **Cosmo! | 76561198978323393**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 620
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ptera, Rival Shores.** 
Map: Rival_Shores

Well, i undocked my battle log bc ive never used it before, and i couldnt re-dock it.

**Comment by Trip-Trap** [comment]
#1072
