### ISSUE TITLE
[Bug] Ory Death Tunnels

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#366]
_Originally written by **DJ XenoRaptor | 76561198017204754**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD FX(tm)-8300 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Beasts of Bermuda** 
Map: Rival_Shores

*Expected Results:* Ory babies won't die whilst being dropped inside the burrows
*Actual Results:* An Ory hatchling died as soon as they were dropped by the parent Ory whilst inside the burrow
*Replication:* Same result, hatchling lived for a split second longer than before but died regardless

**Comment by Trip-Trap** [comment]
#297
