### ISSUE TITLE
[Bug] Falling out of Burrow

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#367]
_Originally written by **Wolgan Renegade | 76561198127450399**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Rival_Shores

When I dig in my burrow to expand it and when someone is near the spot I'm digging at, they drop through the map

**Comment by Trip-Trap** [comment]
Especially happens with diagonal pieces. Someone can stand one stair bit bellow you or near you for a side piece where it will go, and they have the potential to fall through.

**Comment by Trip-Trap** [comment]
#380

**Comment by Trip-Trap** [comment]
#394
o<o dont mind me labeling this duplicate for the 3rd time
