### ISSUE TITLE
[Bug] New players unable to pick up foliage without resetting keybinds

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#368]
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Oryctodromeus** 
Map: Rival_Shores

My friend just bought the game, we spent a good several hours trying to figure it out until we tried just resetting keybinds.

**Comment by cleafspear** [comment]
was fixed with the settings rework patch
