### ISSUE TITLE
[Bug] stuck in a burrow

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#369]
_Originally written by **Egg Dog | 76561198029200412**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **After login from a hardlog** 
Map: Forest_Island

I hardlogged in my burrow as ory. after i logged back in the game thinks im not in a burrow, so i cant dig my way out or force leave the burrow

**Comment by cleafspear** [comment]
this was fixed with the newer burrow detection logic
