### ISSUE TITLE
[Bug] white box in pause menu after death

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3697]
_Originally written by **hazelnut | 76561198071727475**_
Game Version: 1.1.1124

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6402P CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: DM_Caldera

went into pause menu after dying to respawn, white box covering bottom left side of screen behind "character", "search groups", and "options" on UI

**Comment by Trip-Trap** [comment]
#3500
