### ISSUE TITLE
[Bug] skins not saving

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3698]
_Originally written by **hazelnut | 76561198071727475**_
Game Version: 1.1.1124

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6402P CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: DM_Caldera

made skin for new rex, old skins from before update are still there (converted) but can't save new skins

**Comment by Trip-Trap** [comment]
Should be fixed with new hotfix
