### ISSUE TITLE
[Bug] Acros S grade still does bleed damage

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#37]
_Originally written by **CallMeDakotaz | 76561198245440648**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **As soon as we reached S grade** 

Acros can still inflict bleed on eachother when reached to S grade

**Comment by Predatoria** [comment]
Reproduced and fixed in PIE.  Marking as needs testing!

**Comment by Predatoria** [comment]
Confirmed as fixed on tester
