### ISSUE TITLE
[Bug] Falling through the world when exiting a burrow

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#370]
_Originally written by **Screaming Weed | 76561198354076618**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 4600
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ory** 
Map: Rival_Shores

When exiting the burrow as on ory, you sometimes fall through the world. You don't die due it to glitching and forcing you back onto the surface, but it is a scare.

**Comment by Trip-Trap** [comment]
#380
