### ISSUE TITLE
[Severe Bug] BS spawn location

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3703]
_Originally written by **CrazyAzzCamper | 76561198088322468**_
Game Version: 1.1.1124

*===== System Specs =====
CPU Brand: AMD Ryzen 7 2700X Eight-Core Processor         
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **ptera** 
Map: Rival_Shores

spawned in on a ptera 3 miles above the map, and died before i could dive to an acceptable altitude

**Comment by Trip-Trap** [comment]
Not enough info to do anything here. Ptera fresh spawn locations are at acceptable alittudes. This person must have logged out there.
