### ISSUE TITLE
[Quality of life] skin messed up

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3707]
_Originally written by **[D.C] <blank> | 76561198385155962**_
Game Version: 1.1.1124

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

this new update has changed my sais skin and changed quite a few colors and i am unable to change them back

**Comment by Trip-Trap** [comment]
#3499
