### ISSUE TITLE
[Bug] Bug de m,ovimento do jogador

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3708]
_Originally written by **gabsantos2504 | 76561198431022901**_
Game Version: 1.1.1124

*===== System Specs =====
CPU Brand: AMD FX(tm)-8300 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GT 1030
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

Querido admistrador eu tive um bug que eu nao andanod pra direita e nem pra esquerda so pra tras

**Comment by Trip-Trap** [comment]
"Sehr geehrter Administrator, ich hatte einen Fehler, bei dem ich nicht nach rechts oder links zurück gehe"
