### ISSUE TITLE
[Bug] Ory Tunnel Exit Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#371]
_Originally written by **Valhalla | 76561198969278910**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2060
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Ory** 
Map: Rival_Shores

For me, when I was exiting our burrow I could press space while pressing E and jump to go through the mesh and fall through the world until I splashed and it tossed me back up as if I just exited the cave. The first time it happened we were on Forest Island and I fell through and hit the cave system below the upper waterfall pond. My camera stayed as if I were in a burrow (dark as hell), and contiued to treat it like I was in a burrow until I entered the burrow again. (Had to be lead up to the burrow because I couldn't see where I actually was lmao. I have video evidence of it if needed.

**Comment by Trip-Trap** [comment]
#380
