### ISSUE TITLE
[Bug] Velo climbing bug on Rival Shores

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#372]
_Originally written by **Aragul | 76561198060480535**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Velociraptor** 
Map: Rival_Shores

*Expected Results:* Velo should be able to attach to sheer cliffs that are part of the terrain mesh by pressing E 
*Actual Results:* Velo cannot directly attach to the terrain but can attach to the terrain by using the climb-jump.
*Replication:* Spawn as Velo, climb a tree near a cliff and jump to the cliff. Note you properly attach to the cliff. Now try to directly climb the cliff by using E. You will not properly attach.

**Comment by Trip-Trap** [comment]
Reproducable still.

**Comment by cleafspear** [comment]
fixed during the velo recode
