### ISSUE TITLE
[Quality of life] broken bias

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#373]
_Originally written by **Cain | 76561198202061715**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD FX(tm)-8150 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **itchty, bird. havent tested on others** 
Map: Ancestral_Plains

When picking up bias (known on sponge and flowers) they dissapear when dropped. Weither it be in the same spot or if you moved while grabbing they dont drop to the ground.

**Comment by Trip-Trap** [comment]
#364

**Comment by Trip-Trap** [comment]
Wrong ref ...
