### ISSUE TITLE
[Bug] white box on Esc menu

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3733]
_Originally written by **ghoststorm31 | 76561198817874761**_
Game Version: 1.1.1124

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **tyranosarus** 
Map: Rival_Shores

white box appears in escape menu when using the tyranosaur dino thingy

can provide a screenshot of it if you need it.
Discord: ghoststorm31#8088

**Comment by TeaTimeJess** [comment]
Known Texture Issue

**Comment by Trip-Trap** [comment]
#3500
