### ISSUE TITLE
[Bug] Saving Rex Skin - Bugged

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3735]
_Originally written by **Saber | 76561198312477858**_
Game Version: 1.1.1124

*===== System Specs =====
CPU Brand: AMD Phenom(tm) II X6 1090T Processor
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Nothing happens in game, but in the skin coloring HUD the skin won't save.** 
Map: Rival_Shores

There is an Error pop-up when I try to save my rex's skin telling me I can't do that.

**Comment by TeaTimeJess** [comment]
Tried with each skin as a fresh spawn character and within the skin change menu after spawning, could not reproduce.
