### ISSUE TITLE
[Bug] falling thru the map

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#374]
_Originally written by **ParadoxHarvestel2 | 76561198356496138**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: ** Juvinile Orycto** 
Map: Rival_Shores

I stood next to a adult ory as a .2 while it was digging a burrow, fell thru the map, hit the water, then teleported to jungle from snowwy

**Comment by Trip-Trap** [comment]
#394
