### ISSUE TITLE
[Bug] Lurd stomp animation bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3749]
_Originally written by **D3adlyR3aper | 76561198880415303**_
Game Version: 1.1.1124

*===== System Specs =====
CPU Brand:         Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: AMD Radeon R7 250 Series
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Lurdu** 
Map: Rival_Shores

*Expected Results:* 
*Actual Results:* 
*Replication:* 
Location: X=-217086.000 Y=-12351.000 Z=20149.928

**Comment by TeaTimeJess** [comment]
Not enough information, looked over the animation in general but couldn't see any glaring issues.

**Comment by Trip-Trap** [comment]
Lurdu gets an remodel&reanimation
