### ISSUE TITLE
[Bug] Ory Crashing In Burrow

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#375]
_Originally written by **???GOTI??? SpooksHena | 76561198314539087**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3600 6-Core Processor              
Vendor: AuthenticAMD
GPU Brand: Radeon RX 5500 XT
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory** 
Map: Rival_Shores

If a ory crashes in a burrow, they spawn back in under the map and die.

**Comment by Trip-Trap** [comment]
If you crash in a burrow and immediatly log back in the burrow will fail to load in time sometimes.

**Comment by Trip-Trap** [comment]
#382
