### ISSUE TITLE
[Severe Bug] Broken scent

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3753]
_Originally written by **Gator The two | 76561199116718950**_
Game Version: 1.1.1124

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 5500
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Map: Ancestral_Plains

Scent clouds dont appear unless you look the opposite way, even gore scent doesnt appear if you look directly at it, player scent does not appear at all.

**Comment by TeaTimeJess** [comment]
Unable to reproduce, may be related to the game settings issue that has already been addressed?

**Comment by Trip-Trap** [comment]
I assume its that yes, will close this until it appears again after the next public patch
