### ISSUE TITLE
[Bug] Orycto plant bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#376]
_Originally written by **hood | 76561198092313755**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

As 1,2+ orycto, picking up plants and putting them down resulted in them being impossible to eat or pick up again (ferns). Later, another orycto managed to pick up the plants.

**Comment by Predatoria** [comment]
Fixed, duplicate
