### ISSUE TITLE
[Major Bug] Ory tunnles respawning items randomly

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#378]
_Originally written by **Forbidden Ketchup | 76561198280903918**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD Ryzen 3 1200 Quad-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2060
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ory** 
Map: Rival_Shores

every 10-20 secs items in the tunnles dug by an ory seems to respawn and shuffle around, also seems to refill areas your digged out. i have a video if you need
Location: X=-76578.672 Y=94480.023 Z=2609.924

**Comment by Trip-Trap** [comment]
#362
