### ISSUE TITLE
[Bug] FPS drop

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3784]
_Originally written by **Gavin | 76561198254999852**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Rex** 
Map: Ancestral_Plains

*Expected Results:* When using ability for Rex, fps should not drop.
*Actual Results:* When using ability for Rex, fps drops.
*Replication:* Charge up Rex ability and use it.

**Comment by TeaTimeJess** [comment]
Attempted to reproduce by spawning in as a rex and using the ability. Attempted in a few locations on the test map at .4 size and 1.2 size. No large FPS drop occurred so may need more information. Resting FPS was 95, usage FPS was 93. 
I did notice FPS drops regarding rotating the camera, however this was unrelated to the use of Rex ability as it occurred even without the ability being charged.
