### ISSUE TITLE
[Bug] The weird Bug!

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3786]
_Originally written by **peaches4721 | 76561198172250201**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: AMD FX(tm)-6300 Six-Core Processor             
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1060 3GB
GPU Driver Info: Unknown
Num CPU Cores: 3
===================*
Context: **It happend while playing.** 
Map: DM_Caldera

Cant respawn,Cant relog,Chat isn't working. i think we crashed the game.

**Comment by TeaTimeJess** [comment]
Need more information to attempt to reproduce.

**Comment by cleafspear** [comment]
this appears to be a server crash/restart. closing due to lack of info
