### ISSUE TITLE
[Bug] Moving while hitting Burrow making key

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3796]
_Originally written by **Ra'va | 76561198039772275**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3600 6-Core Processor              
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory** 
Map: Rival_Shores

Noticed when i was running around i accidentally hit the Ability key as an Ory and the Burrow digging entrance UI popped up and was stuck there until i made an actual burrow.

**Comment by TeaTimeJess** [comment]
Unable to reproduce. Possibly need more information?
Spawned as an Ory and used the ability key to start the burrow UI. In all stages I was able to move freely to interrupt the burrowing and continue it at will or start it elsewhere.

**Comment by Trip-Trap** [comment]
Cant reproduce either
might have been a lag spike in that moment, that can sometimes prevent you from cancelling burrowing.
