### ISSUE TITLE
[Bug] Name icon gettting stuck

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#381]
_Originally written by **??? TheOnceTrueKing ??? | 76561198262587445**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD FX-8370 Eight-Core Processor               
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ory** 
Map: Ancestral_Plains

The name plate in groups gets stuck in the corner of my screen then doesnt move for a while

**Comment by Trip-Trap** [comment]
Had this happen to me too a few times too while playing ory but could not figure out what it was. But it could possibily have something to do with burrow&character netrelevancy.

**Comment by Trip-Trap** [comment]
Was fixed a while ago
