### ISSUE TITLE
[Major Bug] Ory crash and tp 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#383]
_Originally written by **??????Asena?????? | 76561198952082002**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory** 
Map: Rival_Shores

so when an ory crashes on a server inside a burrow it tps them to another burrow on the map, not where they were and in this case as hatchling to another island.

**Comment by Trip-Trap** [comment]
Likely related to #437
