### ISSUE TITLE
[Bug] Ory Idle animation issue

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#384]
_Originally written by **??? TheOnceTrueKing ??? | 76561198262587445**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD FX-8370 Eight-Core Processor               
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ory** 
Map: Ancestral_Plains

When ory is in an idle animation and you hold alt after it stands, it's hands go into it's body along with it's arms

**Comment by cleafspear** [comment]
still present within 1139
animation blending would have to be reworked for the looks

**Comment by Predatoria** [comment]
More trouble than it's worth to fix this.

**Comment by Predatoria** [comment]
Actually, got an easy fix for this
