### ISSUE TITLE
[Major Bug] Friendshipgrade

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#385]
_Originally written by **Kappataen | 76561198110534590**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD Ryzen 7 1700X Eight-Core Processor         
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Ancestrial Plains as Oro** 
Map: Ancestral_Plains

Burrows somehow either dont show or remove the friendship buff and its not back when you dig up.

**Comment by Trip-Trap** [comment]
I think this change is missing from the patch note. I remember Pred saying about removing the friendship buff in burrows to prevent camping in there iirc. But i havent found it in the patch notes but i could have missed it.

**Comment by Predatoria** [comment]
It's only for non-ory's.  I remember testing this mechanic on tester and seeing it work properly.  Going to close this issue for now, unless it comes up on public.
