### ISSUE TITLE
[Quality of life] Rex sprint

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3851]
_Originally written by **< Deer Trash > | 76561198401875106**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: AMD Ryzen 7 3800X 8-Core Processor             
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2060
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Rival_Shores

Rex sprint doesn't work all the times, me personally have not managed to get it to work

**Comment by TeaTimeJess** [comment]
Not enough information to attempt to reproduce, haven't had issues when using normally.
