### ISSUE TITLE
[Bug] Potato Poisoning

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#387]
_Originally written by **Belphegor | 76561198066613611**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 4600
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Orycto** 
Map: Rival_Shores

*Expected Results:* Sasiation from eating potatos as orycto
*Actual Results:* Gaining negative bias and food poisoning when eating potatos as an orycto
*Replication:* Eat a potato underground as an orycto

**Comment by Trip-Trap** [comment]
Probably accidentally ate a mushroom that was close by. Potatos dont give neg bias. Will close this issue
