### ISSUE TITLE
[Quality of life] Stutter when eating foliage

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#39]
_Originally written by **Madame Toffee | 76561198144202180**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 4600
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Herbivore** 

Noticed a slight stutter when herbivores (observed when an apato was eating trees especially) eat foliage, especially noticeable when any apato of any size eats trees.

**Comment by Trip-Trap** [comment]
Possibly related to issue #34

**Comment by Trip-Trap** [comment]
Duplicate
