### ISSUE TITLE
[Bug] If I teleport on 5000000 on z axis, char is disappeared

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#390]
_Originally written by **Pineapple Pie | 76561198069731250**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD FX(tm)-6300 Six-Core Processor             
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1660 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 3
===================*
Map: Ancestral_Plains

If I teleport on 5000000 on z axis, char is disappeared

**Comment by Trip-Trap** [comment]
:saijoy: not a bug. U just teleported out of the map, congrats
