### ISSUE TITLE
[Bug] Sky Art

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#391]
_Originally written by **CosmicGhost | 76561198170621081**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD A8-9600 RADEON R7, 10 COMPUTE CORES 4C+6G  
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Apatosaurus** 
Map: Ancestral_Plains

Apparently when Ory's dig burrows under trees the dirt pods depositied out stick to the tree branches, when the tree is eaten by an Apato the dirt pods stay frozen in the sky. Location: X=-264198.063 Y=-140358.953 Z=6512.237

**Comment by Trip-Trap** [comment]
#363 Duplicate
