### ISSUE TITLE
[Quality of life] carry drop insta death bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#392]
_Originally written by **Demi-chibi | 76561199022372057**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Oryctodromeus ** 
Map: Rival_Shores

died glitching under map under water due to parent was holding me

**Comment by Trip-Trap** [comment]
#206
