### ISSUE TITLE
[Enhancement] pond has no exit (we are STUCK!!!!)

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3921]
_Originally written by **deathsong1218 | 76561198974768447**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **fell in to watering hole** 
Map: Forest_Island

*Expected Results:* 
*Actual Results:* 
*Replication:* 
Location: X=9773.363 Y=-133916.828 Z=10792.403
groups of land dinos keep geting stuck

**Comment by Predatoria** [comment]
Added ramp to water source
