### ISSUE TITLE
[Bug] Entry into map.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#393]
_Originally written by **kiyi | 76561198064020901**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ptera** 
Map: Rival_Shores

*Expected Results:* Walking into a rock should stop your character.
*Actual Results:* You can walk through the rock to get inside the map.
*Replication:* Walk through the rock as a smaller dinosaur.

Smaller dinosaurs can walk through a rock in order to get into the map at this location.
More useful for pteras than velos, since flying is required to make use of it.

Location: X=12048.656 Y=224058.609 Z=6553.945

**Comment by Trip-Trap** [comment]
Can still get into the map at the same exact location

**Comment by Predatoria** [comment]
Should have this one fixed this time.
