### ISSUE TITLE
[Bug] burrows   deleting them  selfs  while ur in  them

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#399]
_Originally written by **dozasaurus | 76561198312453894**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD Ryzen 7 2700X Eight-Core Processor         
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **new ory** 
Map: Rival_Shores

was   digging  our burrow  with my  friend  and   it   deleted   it  self  and  kicked  ous   out  of  our   burrow

**Comment by Predatoria** [comment]
Likely got flooded.  I doubt it actually deleted.  We haven't ever seen such a thing happen.
