### ISSUE TITLE
[Major Bug] Fell through map and drowned

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#400]
_Originally written by **??? TheOnceTrueKing ??? | 76561198262587445**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD FX-8370 Eight-Core Processor               
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ory** 
Map: Ancestral_Plains

I was trying to get into a server several times and it kept kicking me out i had gotten into a burrow and it spawned be in before the burrow, i feel through the map

**Comment by Trip-Trap** [comment]
#382
