### ISSUE TITLE
[Bug] Bridge collissions buggy

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#401]
_Originally written by **Aragul | 76561198060480535**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Orycto 0.3** 
Map: Rival_Shores

Location: X=-164357.469 Y=-15701.718 Z=11549.567
Walk across the bridge as a small dino.

**Comment by cleafspear** [comment]
issue resolved with rework of the camera
