### ISSUE TITLE
[Quality of life] Water shader glitch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#402]
_Originally written by **The Fast Zebra | 76561198202161752**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Itchy** 
Map: Rival_Shores

*Expected Results:* When standing in water, water should look the same as swimming in it.
*Actual Results:* Water is lighter and clearer when standing in it and darker when swimming in it.
*Replication:*  1.) Stand in water
                         2.) Put camera underwater and water is lighter
                         3.) Swim in the water
                         4.) Put camera underwater and the water is darker

**Comment by Predatoria** [comment]
This is a bug in many games.  Putting the camera at the waterline doesn't engage the underwater screen post processings, and we don't know how to split-screen it.
