### ISSUE TITLE
[Major Bug] Teleport death Ori

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#403]
_Originally written by **OwlsGoHoot | 76561198044642233**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 960
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Teleported down into the water which caused me to drown before I could get to the top** 
Map: Ancestral_Plains

Was just walking around as an Ori, hopped down a short cliff which teleported me into water and drowned me.

**Comment by Predatoria** [comment]
It's the grab bug.  I need to fix this but it's a royal pain.

**Comment by Predatoria** [comment]
Actually... It's not.  I actually have no idea what happened here.
