### ISSUE TITLE
[Bug] Poofing Flowers Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#404]
_Originally written by **Snakebird | 76561198000326906**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand:        Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 780 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ptera near lagoon** 
Map: Ancestral_Plains

I vacuumed up a field of flowers, and when I dropped it, they all disappeared. I did this again in another location. Hopefully this YouTube link works here.

https://youtu.be/S4l-WhyvyQ0

**Comment by Predatoria** [comment]
I believe this is related to another foliage glitch I just fixed where they'd get stuck non-interactable sometimes.  Going to mark this as potentially fixed.
