### ISSUE TITLE
[Quality of life] Apato able to eat toxic mushrooms from Burrow

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#405]
_Originally written by **CosmicGhost | 76561198170621081**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD A8-9600 RADEON R7, 10 COMPUTE CORES 4C+6G  
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Apatosarus ** 
Map: Ancestral_Plains

Upon eating plants/trees as an apato from above a hill bellow a burrow, i am also able to eat the glowing mushrooms inside the burrows from bellow and result in food poisining dropping comfort.
Location: X=-266584.063 Y=-139947.656 Z=6332.214

**Comment by Predatoria** [comment]
Fixed next patch!
