### ISSUE TITLE
[Bug] Ory combat mode in burrow

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4053]
_Originally written by **Egg Dog | 76561198029200412**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

I sended the same bug report few days ago. but now its 100% sure that its a bug that other orys have too.

when you switch in a burrow to combat mode as an ory, it will automatic switch back to dig mode randomly and you dont even see the dirt inventory when it does that, so you end up diging in a fight

**Comment by Trip-Trap** [comment]
Can reliably reproduce this on testers.
Upon server tick it automatically switches you back to burrow stance but without the HUD

**Comment by Trip-Trap** [comment]
#3769
