### ISSUE TITLE
[Quality of life] velo animation arm bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4055]
_Originally written by **Mutedmirth | 76561198046014700**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: AMD A8-9600 RADEON R7, 10 COMPUTE CORES 4C+6G  
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **velo** 
Map: Ancestral_Plains

*Expected Results:* Arms to be at the side when crouched or sitting
*Actual Results:* Ares crossed underneath them
*Replication:* Just the velo model I think

**Comment by Trip-Trap** [comment]
Animation issue itself, wont get fixed
