### ISSUE TITLE
[Bug] Weird killing bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#406]
_Originally written by **Sundavar | 76561198202184552**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ory** 
Map: Ancestral_Plains

I was trying to jump up a burrow tunnel. First it knocked me back with injury, next time i tried i got up but instantly died. I don't know where this came from.

**Comment by Predatoria** [comment]
I honestly have no idea what to make of this.  Maybe there was a pachy inside they didn't see or something.  I don't really have enough information to investigate this further.
