### ISSUE TITLE
[Bug] чому так?

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4070]
_Originally written by **Roma Englishman | 76561198009908091**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1650 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Ancestral_Plains

Чому так? Меня катает на рикси, я мил руки
Location: X=101639.719 Y=-204916.109 Z=4165.244

**Comment by Trip-Trap** [comment]
"Why so?"
"Why so? Ricksie rides me, I love hands"
*no clue closing this*
