### ISSUE TITLE
[Quality of life] Water clips through map

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#408]
_Originally written by **The Fast Zebra | 76561198202161752**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Itchy** 
Map: Rival_Shores

Water clips through the ground here

Location: X=140595.703 Y=47208.465 Z=5113.803

**Comment by Predatoria** [comment]
Fixed next tester patch
