### ISSUE TITLE
[Bug] infinite dirt?

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#409]
_Originally written by **Pierce Hawthorne | 76561198385155962**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

ive noticed that you can place and dig the same piece of dirt to fill your dirt meter

**Comment by Predatoria** [comment]
This is intended.  Otherwise, you cannot ever actually fill tunnels that you dug otherwise due to dirt dumping out when you exit.
