### ISSUE TITLE
[Bug] Disconnecting in Burrow Trapping Player

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#410]
_Originally written by **Voxous | 76561198020131549**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Animals that can enter burrows** 
Map: Rival_Shores

My client disconnected while I was digging in a burrow, and on logging back on, I was still under ground, but it was being treated as tho I was above ground, not allowing me to switch to dig stance or use the leave burrow button.

unstuck did not help

**Comment by Predatoria** [comment]
I may have a fix for this.  It's hard to really reproduce this kind of thing in PIE, but I believe the force-fix I'm adding for other burrow-related state issues will also catch this, and I modified the code a bit to check for this OnPossessed.

**Comment by Predatoria** [comment]
Should be fixed, confirmed fixed on tester
