### ISSUE TITLE
[Bug] Transpasable rock

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4125]
_Originally written by **Pala (DiosPaladin) | 76561198127868592**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 970
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Rival_Shores

in the snow mountain in a cave, there is a small hiding place it have a transpasable rock only in one side make you stuck in
Location: X=-205667.875 Y=24900.906 Z=22578.791

that is the place.

**Comment by Predatoria** [comment]
I can't seem to find this spot.
