### ISSUE TITLE
[Bug] misplaced rock on AP

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4129]
_Originally written by **Bulbertianus | 76561198987079439**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **anything than rock** 
Map: Ancestral_Plains

Just look at this tiny pebble here:
Location: X=-40808.910 Y=9089.762 Z=13003.912

**Comment by Predatoria** [comment]
Cannot find anything wrong at this location
