### ISSUE TITLE
[Major Bug] Ory Combat in burrow Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4138]
_Originally written by **Eve Stargaze | 76561198137104876**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: AMD Ryzen 5 1600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1060 3GB
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory** 
Map: Rival_Shores

When ory switches to attack stance it only lasts for 10 seconds tops then it switches you to dig stance with out a pop up message OR indecating it with the jar on the left. you have to hit the change stance button 3 times before its corrected.

**Comment by Trip-Trap** [comment]
#3769
