### ISSUE TITLE
[Major Bug] Ory combat burrow bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4139]
_Originally written by **Eve Stargaze | 76561198137104876**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: AMD Ryzen 5 1600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1060 3GB
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory** 
Map: Rival_Shores

https://www.youtube.com/watch?v=ZfiRITjII7s

I already made one but heres the video if it works

**Comment by Trip-Trap** [comment]
#3769
