### ISSUE TITLE
[Bug] Baby Stats Not going away

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4147]
_Originally written by **BossHog | 76561197969239706**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Trope** 
Map: Rival_Shores

When i sniff to see babys stats... "Food,water...ect "  It stays suspended on the screen and does not disapear..

**Comment by Trip-Trap** [comment]
#4149
