### ISSUE TITLE
[Enhancement] Rain under water.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#415]
_Originally written by **Drakslang | 76561198193635813**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Mosa in a growth storm.** 
Map: Ancestral_Plains

Dino: Mosa
During: A growth storm
Issue: When I put my camera above the water and then back under the water there is a chunk of rain that is still there behind me. It moves to wherever I put my camera back under the water.

Location: X=-111783.055 Y=-157692.141 Z=5312.379

**Comment by Predatoria** [comment]
Fixed it next patch!
