### ISSUE TITLE
[Bug] Apatos getting stuck on this rock

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4159]
_Originally written by **Dagoth will dagoth | 76561198819503280**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8400T CPU @ 1.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Ancestral_Plains

So when i was growing my 1.2 apato i got stuck on the terrain and unstuck and unjam didnt work at all and logging normally only force respawn being a option 
Location: X=125295.586 Y=155835.422 Z=10680.754

**Comment by TeaTimeJess** [comment]
Unable to test due to map being AP.

**Comment by Predatoria** [comment]
Smoothed the offending area out
