### ISSUE TITLE
[Quality of life] Seaweed on land

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#417]
_Originally written by **The Fast Zebra | 76561198202161752**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Itchy** 
Map: Rival_Shores

Seaweed spawns on land here
Location: X=83903.992 Y=83425.344 Z=3791.421

**Comment by Trip-Trap** [comment]
Location: X=80905.477 Y=83107.523 Z=3831.059

There is still see weed

**Comment by cleafspear** [comment]
seaweed no longer present as of 1139. closing
