### ISSUE TITLE
[Bug] Friendship bug.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#419]
_Originally written by **Drakslang | 76561198193635813**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Any dinosaur.** 
Map: Ancestral_Plains

I'm not sure how you can reproduce it as it only affects some people, I know it's affects others but most people it works for. 

When I set my friendship in options, to "All Events" and "Combat Log & On-screen" it does not work and goes back to both these being blank.

**Comment by Predatoria** [comment]
Will be fixed with Vipe's config rework
