### ISSUE TITLE
[Bug]  velo jumping glitch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#42]
_Originally written by **ama.cujin | 76561198380878489**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 620
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **2020 june as velo** 

So i was joining for the first time today. and i went to go get water as a velo to a nearby water. and on the way. i realized i couldnt jump very high. like only 5 velos high at 1.2 growth :/ and this jum p was at full holdign space bar and every thing shift and no shift doesnt change it. so i reloged and still happend? and i have 3/3 powerful legs so how come its not working?

**Comment by Predatoria** [comment]
It sounds to me like the jump key hold time wasn't working properly, and it was acting like the jump had a hold time of 0 seconds.  Nonetheless, I'm not sure how to reproduce this.
