### ISSUE TITLE
[Major Bug] Inherit System with Latest Patch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#420]
_Originally written by **Thlayli | 76561198027621606**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3600 6-Core Processor              
Vendor: AuthenticAMD
GPU Brand: Radeon RX 570 Series
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

The inherit system in the latest patch seems to be bugged. People are not getting the inherits that they should be. Sometimes no inherits per tick whatsoever with pretty large parents.

**Comment by Predatoria** [comment]
I've personally been playing and have not experienced any issues getting inherits.  I believe this is just poor RNG.  This code has not been changed.
