### ISSUE TITLE
[Quality of life] saved skin dissapear

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#421]
_Originally written by **Egg Dog | 76561198029200412**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **it happens randomly. somethimes the skin stay for a while in my "saved skin" and dissapear soon or later** 
Map: Forest_Island

when i save a skin on any dino, it will delete itself randomly  soon or later sadly

**Comment by Trip-Trap** [comment]
#461 Removed all other duplicate except this one. Will reassign Vipe in that report where all others are refered to atm
