### ISSUE TITLE
[Severe Bug] Dropping out of the sky

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#423]
_Originally written by **ashaul | 76561199013871455**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand:         Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 650
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ptera** 
Map: Ancestral_Plains

i was flying then my  1.0 ptera just starting going down, and eventually died

**Comment by Predatoria** [comment]
Not sure what to make of this.  Ptera seems to behave fine for me.
