### ISSUE TITLE
[Bug] Picking up food then losing it

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#426]
_Originally written by **AbbeyPiePlayz | 76561198353348394**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 3GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

every time i try to pick up a leg the leg in my mouth well alway go away idk why but i done it like 5 time and the leg in my mouth always went away.

**Comment by Trip-Trap** [comment]
This is due to a rotting carcass. If you pick a leg up from it it will insta rot and the bone drop out of your mouth.
