### ISSUE TITLE
[Bug] cave bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4270]
_Originally written by **LoveDragon91 | 76561198971725654**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **to a friend ** 
Map: Rival_Shores

so in the pt tower in the back of the cave theres a rock where velos can get into and if not lucky can glitch under the map

Location: X=232040.734 Y=195384.625 Z=13634.277

**Comment by Predatoria** [comment]
Added rock here
