### ISSUE TITLE
[Bug] Lurdusaurus

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4280]
_Originally written by **UrAveragePlagueDoctor | 76561198296341970**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand:         Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

The teeth for lurdusaurus arent connected to anything and hover and phase through the jaw when lurdu roars

**Comment by Trip-Trap** [comment]
yisyis
