### ISSUE TITLE
[Major Bug] Egg Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#429]
_Originally written by **Aslaya | 76561198284410043**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

Everytime I go to get into an egg from the dino selcet screen it dose not let me in the egg but takes me to a screen where there is nothing but map

**Comment by cleafspear** [comment]
appears this issue cannot be reproduced in any way on 1139.
