### ISSUE TITLE
[Bug] burrow exit "hitbox"

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#430]
_Originally written by **Egg Dog | 76561198029200412**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **in a burrow** 
Map: Forest_Island

i can use my burrow exit 3 block under it and 1 block next to it

**Comment by cleafspear** [comment]
this is due to the exit capsule being so long and fairly large under the exit. working as intended
