### ISSUE TITLE
[Bug] Baby stats sniff 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#431]
_Originally written by **Egg Dog | 76561198029200412**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Baby stats UI bug** 
Map: Forest_Island

when i sniff my baby'S stats the stats dont disapear anymore till i close the game and join back.

it happens right after i logged back in again on my baby. the stats also static, so they just show what i sniffed at the 1 momment

**Comment by Trip-Trap** [comment]
#348
