### ISSUE TITLE
[Bug] Visualy hiding gores

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#432]
_Originally written by **Kappataen | 76561198110534590**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD Ryzen 7 1700X Eight-Core Processor         
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Ory AP Map in a burrow** 
Map: Ancestral_Plains

You can visualy hide gores in burrows by placing dirt on them. I think you shouldnt be able to place dirt on gores. They wont despawn if you place dirt on them *

**Comment by Trip-Trap** [comment]
U can do that with anything u pick up.
