### ISSUE TITLE
[Bug] not letting me change color of dino

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4327]
_Originally written by **BTMxGODFATHERxX | 76561199104280590**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: AMD Ryzen 3 3100 4-Core Processor              
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2070 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **yes** 
Map: Ancestral_Plains

not letting me change color of dino 
Location: X=-84803.805 Y=31989.852 Z=14630.044

**Comment by TeaTimeJess** [comment]
Not enough information.
