### ISSUE TITLE
[Enhancement] Scroll arrow on eggselect

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#434]
_Originally written by **Kappataen | 76561198110534590**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD Ryzen 7 1700X Eight-Core Processor         
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Eggselect Menue** 
Map: Ancestral_Plains

Add a scroll arrow on the eggselect list for laptops without mouswheel

**Comment by Trip-Trap** [comment]
Noted
