### ISSUE TITLE
[Enhancement] HACKS

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4346]
_Originally written by **Implecta | 76561198274793989**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: AMD Ryzen 7 2700X Eight-Core Processor         
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2070
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **BITCHES BE BONKERS** 
Map: Rival_Shores

Someone is using smell hacks and they keep picking me up and putting me in water. Somehow they know how much water and food I have.

**Comment by cleafspear** [comment]
theres not enough info on this.
if this was a hatchling or a megalo, this is normal behavior.
