### ISSUE TITLE
[Major Bug] Burrow hatchling teleport

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#437]
_Originally written by **Kappataen | 76561198110534590**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD Ryzen 7 1700X Eight-Core Processor         
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Ory AP Map in a burrow** 
Map: Ancestral_Plains

My Ory hatchlings got teleported to a random burrow across the map after logging back in

**Comment by Predatoria** [comment]
This is intentional behavior, as if a player hasn't used a burrow yet, they port out to a random terrestrial spawn.
