### ISSUE TITLE
[Bug] Stuck in Ory digging animation

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#439]
_Originally written by **embug | 76561198055496636**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 5600
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

I dont really know how this happened. I was putting dirt in a spot and then I lagged, got stuck in this animation, and can't move.

**Comment by Trip-Trap** [comment]
#395
