### ISSUE TITLE
[Major Bug] Comfort Flowers falling through ground when dropped.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#442]
_Originally written by **Tabbed Dragon | 76561199028966375**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Pachy** 
Map: Rival_Shores

Was playing a Pachy; Comfort Flowers dropped through ground instead of dropping properly. Possible because I was over an Ory tunnel. Video: https://www.youtube.com/watch?v=BL2ftBFBgAU&feature=youtu.be

**Comment by Trip-Trap** [comment]
#404
