### ISSUE TITLE
[Bug] Talent points reset then undo

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#443]
_Originally written by **TamerOfAll | 76561198119656666**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

I'm playing an Ory, sleeping in my burrow, when my talent points reset and then undid the reset going back to what I had. This isn't something game changing, but a bugs a bug.

**Comment by Predatoria** [comment]
Thinking it may be related to the fix we deployed for inherits.
