### ISSUE TITLE
[Bug] Skin Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#444]
_Originally written by **ama.cujin | 76561198380878489**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 620
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **When i started using a moderator as a screen happening ever sense** 
Map: Ancestral_Plains

Ok, so im using a moderator to use as a screen because my laptop screen is broken.Ever sence ive been using it no matter my graphics all skins look blurry to me including my own.Its really annoying when im crafting my skin because it  blends colors and i cant see the shape its just all blur with color. And id be really happy if you  fixed it so i could properly see other skins and make 1 ^-^ alot of people dont get this glitch but im 1 of the few. It happens constantly and there use to be a fix for me when i went into options and turned from windowed to fullscreen. Thanks alot ^-^

**Comment by cleafspear** [comment]
this is a known issue with intel intergrated graphics and cannot be fixed due to the gpu not having enough ram to load the hi resolution textures used on creatures. this is a hardware limitation, not software
