### ISSUE TITLE
[Major Bug] Internet abuse

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#448]
_Originally written by **Anatze | 76561198302304278**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **any creature** 
Map: Rival_Shores

*Expected Results:* any changes you did in game without internet connected should not effect the game

*Actual Results:* you can duplicate things, get full fat on apato from 1 fat plant, get full fat 3.0 rex by eating 0.1 velo meat, kill the eggs from a distance and etc

*Replication:* turn off your internet for a 5-7 ish secods and try to eat some tiny meat chonk as a big creature, or eat fat plant as a herbi without internet on

**Comment by cleafspear** [comment]
verified fixed after testing on 1130

**Comment by Predatoria** [comment]
I thought I fixed this.  Not sure how it's still getting through. It requires a client->server->client conversation to eat now.

**Comment by cleafspear** [comment]
this is fixed
