### ISSUE TITLE
[Bug] Rain inside cave

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4494]
_Originally written by **BossHog | 76561197969239706**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Sai** 
Map: Rival_Shores

Raining inside the cave..
Graphics/animation 
Location: X=-50245.648 Y=28686.297 Z=3172.871

**Comment by Predatoria** [comment]
Changed rain particles next patch
