### ISSUE TITLE
[Severe Bug] Stuck in a cave

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4512]
_Originally written by **ConcreteMan123 | 76561198122520084**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3400G with Radeon Vega Graphics    
Vendor: AuthenticAMD
GPU Brand: AMD 15D8:C8
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **forest map** 
Map: Forest_Island

Stuck at the entrance of a cave, cant move in any direction. I cant crouch and walk away and the unstuck doesn`t help.
Location: X=-39942.270 Y=-142962.781 Z=4231.709

**Comment by Predatoria** [comment]
Fixed this in another ticket
