### ISSUE TITLE
[Bug] Over-crowded

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#452]
_Originally written by **Da'len | 76561198968321466**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Rex** 
Map: Ancestral_Plains

The server allows 3 rexes to a group, yet with 3 rexes we all get the over-crowded debuff.

**Comment by Trip-Trap** [comment]
If this was on official it would be the issue on the configs. Cant reproduce otherwise
