### ISSUE TITLE
[Bug] Snowy cave walls 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4535]
_Originally written by **Shanks | 76561198280472833**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3600 6-Core Processor              
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2080 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **A trope** 
Map: Rival_Shores

I can get in the snowy cave by the walls

**Comment by TeaTimeJess** [comment]
Not enough information in terms of location, checked entrances and added a location in map-issues, but unsure if this is the issue the user is mentioning. (Copied over to discord for images.)

Spawned as a trope
Attempted to press through walls at entrances of Snowy Cave.
Hole found in ( -148390 23382 18230) 
Walk through wall found in (-183190 22458 26682)

**Comment by Predatoria** [comment]
Put rocks on both of these holes
