### ISSUE TITLE
[Major Bug] Ory Burrow Nodes Changing States Every Tick

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#454]
_Originally written by **Pancakes the Worm with Candy | 76561198129945444**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory** 
Map: Rival_Shores

*Expected Results:* Once a Node is Dug, it will stay in the same state indefinetly, even on reload. EX: a Node with leaves will stay a node with leaves 

*Actual Results:* Nodes constantly change states every tick, and eventually, after a few minutes, it stops. Nodes are interactable so crystals, potatoes, or mushrooms that spawn on them can be eaten. The Nodes  state changes do not apear to have any pattern. EX: Node changes from empty, to potatoe node, to rock node, to crystal mode, every server tick

*Replication:* Unsure. Was a fresh spawn Ory entering into burrows that did not belong to me and were old / edited multiple times by many other orys all at seperate intervals. Try entering burrows at spawn points in servers with high traffic, these tend to have a higher chance of having this issue.

**Comment by Predatoria** [comment]
I have no idea what this would be, and have no idea how to reproduce it.  Burrows seem to be working fine for me.

**Comment by Predatoria** [comment]
We found a way to reproduce this.  Nodes just above sea level do this every time the tide updates.

**Comment by Predatoria** [comment]
Fixed it!
