### ISSUE TITLE
[Major Bug] skins not saveable

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#456]
_Originally written by **Squid Knee | 76561198040493007**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

my skins still do not save. if i were to leave the game completely, reopen it, and make a new creature, my saved skins are no longer there.

**Comment by Trip-Trap** [comment]
#461
