### ISSUE TITLE
[Quality of life] Vigilance Broke prexisting Velo talents

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#457]
_Originally written by **]N[ Fighting Physics | 76561197995889938**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD Ryzen 5 1600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **velociraptor** 
Map: Rival_Shores

my velo talents are bugged before the update that introduced the new dinosaur, Heavy had 3/3 and after the major update talent replacement vigilance completely broke my velociraptor, it didnt remburse my talents now im stuck with a broken velo that is missing 3 talent points from hard earned growth (2.858) that the talents should have at least been reset completely so i can put back my hours put into this

**Comment by Predatoria** [comment]
Won't be fixing this.  Just an unfortunate side effect of us changing a talent.
