### ISSUE TITLE
[Bug] Burrow exit

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#458]
_Originally written by **Egg Dog | 76561198029200412**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **in burrow** 
Map: Forest_Island

i send a simular bug already with that bug but i wanted to mention , that i can even use my burrow exit 8 blocks under the exit with 2 roofs between it

**Comment by Trip-Trap** [comment]
#430
