### ISSUE TITLE
[Quality of life] Ory and Sai skins don't save?

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#459]
_Originally written by **YangXiaoLong | 76561198144115130**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD A10-7700K Radeon R7, 10 Compute Cores 4C+6G
Vendor: AuthenticAMD
GPU Brand: AMD Radeon(TM) R7 Graphics
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **In the server le chill hideout, I respawned a few times and died the other time to an itchy** 
Map: Rival_Shores

I made a new skin for the ory, and saved it and went on my way, well I died and went to use the same skin but no matter how long I waited or restarted the skins never showed back up, they weren't nested skins just normal ignition for sai and crested for ory, I colors them and then saved them.

**Comment by Trip-Trap** [comment]
#461
