### ISSUE TITLE
[Bug] Crashes

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#46]
_Originally written by **?????? Sailor Moon ?????? | 76561198968972143**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Lost Beasts 2** 

When ever it growth storms or floods, the server crashes. And when you log back in, you lose about an hour's worth of growth.

**Comment by Predatoria** [comment]
The crashes we've seen on Sentry are not related to storms, but we do have a few server crash fixes coming up in our next build.  I'll mark this as potentially fixed.

**Comment by Predatoria** [comment]
Marking this as fixed.  Crashing is very substantially lower as of our hotfix last night for patch 1.1.946
