### ISSUE TITLE
[Bug] Random death

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4608]
_Originally written by **eatmygrandmaplz | 76561199045028898**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **with Pteranodoon** 
Map: Rival_Shores

I was driking water when all of sudden I died (comfort was high, and I wasn't inside of water)

**Comment by TeaTimeJess** [comment]
Not enough information.
