### ISSUE TITLE
[Quality of life] Saved skins disappearing

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#461]
_Originally written by **Arvaid | 76561198051629573**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **After Ory Update** 
Map: Rival_Shores

So, after the Ory's got introduced into the game, I have noticed that any skins I had saved before are gone. I remake them and new ones, save them, and as long as I stay in the game everything is fine and dandy. The problem comes when I boot up the game after having exited, any and all skins I had saved are gone, and are nowhere to be found.

This problem repeats everytime I save a skin, exit, and re-enter the game. It is very disheartening, especially when you make an awesome skin only to have it be erased the next time you play. I am unsure what is making this happen but I feel it would help to get it fixed. For if one person is experiencing it, it is likely others are as well.

**Comment by Trip-Trap** [comment]
#28

**Comment by Trip-Trap** [comment]
fixed :dab:
