### ISSUE TITLE
[Bug] Only 1 inherit on a 1.2 growth ory?

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#464]
_Originally written by **WildcatStorm | 76561198086116683**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory female, life cycle, Rival Shores** 
Map: Rival_Shores

I have no idea how you would reporduce it, but I ended up with only a single inherit on my 1.2 Ory female. It was a +1 in surefooted. I've always known it as you'd get at least 2 inherits per dino so I am very confused.

**Comment by Predatoria** [comment]
Fixing this next patch.
