### ISSUE TITLE
[Bug] Skin wont save

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#465]
_Originally written by **Zero | 76561198002492029**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD Ryzen 9 3900X 12-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1080 Ti
GPU Driver Info: Unknown
Num CPU Cores: 12
===================*
Context: **As far as I can tell as a ory if you make your skin color and save it wont be saved on death.** 
Map: Rival_Shores

*Expected Results:*  Skin color wont save as a ory
*Actual Results:* skin color wont save as a ory
*Replication:* skin wont save as a ory and the skin will go away on death

**Comment by Trip-Trap** [comment]
#461  duplicate
