### ISSUE TITLE
[Quality of life] Underwater Frame Drops with Update

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#47]
_Originally written by **FullerPhoenix | 76561198094152637**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: AMD FX(tm)-8320 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 960
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Mosa** 

The game plays fine until the camera is positioned under the surface of water. It will then drop frames while viewing anything underwater. Played around in the settings menu but found no difference or temporary fix. Running a GTX 960 card and don't usually encounter frame drops, only happened upon the recent update.

**Comment by Thy-Vipe** [comment]
Cannot reproduce.
