### ISSUE TITLE
[Enhancement] ory bottom jaw jiggle while sitting

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#472]
_Originally written by **disaster strikes | 76561198040981157**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2070 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Rival_Shores

ory bottom jaw spazzes while in sitting animation

**Comment by Predatoria** [comment]
Checked this.  Cannot reproduce it.
