### ISSUE TITLE
[Bug] Swiffness does nothing

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#473]
_Originally written by **Zero | 76561198002492029**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD Ryzen 9 3900X 12-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1080 Ti
GPU Driver Info: Unknown
Num CPU Cores: 12
===================*
Context: **From what most players can tell the swiffness talent does nothing** 
Map: Rival_Shores

I'm also going combat so I can fight velo's but I find even with 3/3 swifftness it does nothing to make you faster.

**Comment by Predatoria** [comment]
Wondering if this is true or not.  I am wondering if they just aren't noticing a difference.
