### ISSUE TITLE
[Bug] Apato Stomping in Water

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#474]
_Originally written by **Starcatcher | 76561198116205644**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G  
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 960
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Map: Rival_Shores

At the surface in water deep enough to swim in, apato can still stomp.

**Comment by Predatoria** [comment]
Fixed it!
