### ISSUE TITLE
[Bug] ory healing

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#477]
_Originally written by **Slameo | 76561197983783386**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Game** 
Map: Rival_Shores

ory attacking a sai with 5 thick hide heals sai

**Comment by Predatoria** [comment]
Fixed next tester patch.

**Comment by cleafspear** [comment]
fixed on tester
