### ISSUE TITLE
[Major Bug] Inherits bug!!!

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#478]
_Originally written by **Morme | 76561198061494185**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 980
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Sai and apato** 
Map: Rival_Shores

I have a 2.1+ sai, and I'm nesting with a 1.4+ sai (both full, or almost, combat) and our kids only get one inherit at the time. Evrey time. And always only +1 survival inherits. Even tho we nested a lot and got kids with pretty good and multiple combat inherits before the patch! And we are not the only people to get this bug. The 1.5+ apas in our herd have it too with their kids.
Please, fixe that bug. Nesting and inherits are a huge part of this game.

**Comment by Predatoria** [comment]
Should be fixed on the build we just deployed.
