### ISSUE TITLE
[Bug] cant get air

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#48]
_Originally written by **Worthless | 76561198375567291**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: AMD Ryzen 5 1400 Quad-Core Processor           
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **mosasaur** 

im playing as a mosasaur, i breach the surface and press alt to lift my head then e to get air but the air meter isnt filling up and ive tried force respawning.

**Comment by Predatoria** [comment]
I'm suspecting user error on this.  I've tested it in PIE and mosa breathing works fine.  If it's some kind of state jam or other issue, I'd need more information to reproduce this.  I'll mark it as closed / unable to reproduce.
