### ISSUE TITLE
[Bug] Dropping Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#482]
_Originally written by **Diablo | 76561198450263549**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 3GB
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **As a Para** 
Map: Ancestral_Plains

Ok I pick up various ferns and plants on Lurdu as a para to help feed a sai and smol apa, when I go to drop the various plants most if not all of them vanish just poof I can't give any better of a description other than this hope it's helpful.

**Comment by Predatoria** [comment]
This is fixed in the patch we just deployed, and was confirmed on tester.
