### ISSUE TITLE
[Bug] food/items being carried fall through the ground every now and then

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#483]
_Originally written by **[DPD] Johnnyy | 76561198965420922**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **as a mosa in the deep sea** 
Map: Ancestral_Plains

every now and then when dropping something u are carrying as a marine dino, the thing you dropped falls through the ground making you unable to pick it back up

**Comment by Predatoria** [comment]
This is likely the same foliage carrying bug we've already fixed.  Going to close this, as it was fixed this patch on public
