### ISSUE TITLE
[Quality of life] Bullsheit

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#49]
_Originally written by **Nyx'Shara | 76561198282990863**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: AMD Ryzen 7 3700X 8-Core Processor             
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2070
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Mosa** 

Mosas shouldn't be oneshot instantly by a kronos's lunge, and a mosa shouldn't be able to grab an apato since logically it would shatter their jaw. Get your shiet together devs.

**Comment by Predatoria** [comment]
Marking this as closed / not fixing.
