### ISSUE TITLE
[Bug] came out of a tunnel

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#490]
_Originally written by **Demi | 76561198051871738**_
Game Version: 1.1.1005

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

for a good 5 sec after exiting an ori tunnel, i still had the vision as we have in the tunnel

**Comment by Predatoria** [comment]
Server lag maybe?  Not sure, but I know we won't be able to reproduce this without more info.
