### ISSUE TITLE
[Bug] in the tunnel as an ori

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#491]
_Originally written by **Demi | 76561198051871738**_
Game Version: 1.1.1005

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

it sais i can dig, and some of the animation are there, but no tunel is mad... mulitble times around same spot. thinking its aither should or should not be possible
Location: X=-68624.563 Y=57242.973 Z=6232.162

**Comment by Predatoria** [comment]
huh
