### ISSUE TITLE
[Major Bug] Lag spikes

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4911]
_Originally written by **Atlas | 76561197969239706**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

Huges FPS drops when players render in. This issue isnt an issue with other games.

Location: X=136758.406 Y=91082.430 Z=4809.485

**Comment by cleafspear** [comment]
issue is due to device being WELL below min spec. the lag is caused when the character is built on the replication.
