### ISSUE TITLE
[Major Bug] still the inherits

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#497]
_Originally written by **Morme | 76561198061494185**_
Game Version: 1.1.1005

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 980
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **sai** 
Map: Rival_Shores

Inherits still broken, kids often get none even with 2.1 and 1.5+ parents with both 3 good parent

**Comment by Predatoria** [comment]
Got a fix for this finally
