### ISSUE TITLE
[Bug] Game freezing

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4979]
_Originally written by **Atlas | 76561197969239706**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

Game Freezing for a split second when using Sniff?

Location: X=159837.469 Y=142163.812 Z=5862.897

**Comment by cleafspear** [comment]
Duplicate of #4976
