### ISSUE TITLE
[Bug] I'm stuck

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4983]
_Originally written by **Zemfira | 76561198294727678**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2070
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Zemfira** 
Map: Rival_Shores

I was flying through a cave on the Rival map, and then I got stuck in the ceiling of the cave ( in the desert)
Location: X=12218.897 Y=223367.859 Z=5773.014

**Comment by Predatoria** [comment]
Cannot find an issue here
