### ISSUE TITLE
[Bug] Black Screen when leaving burrow

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#499]
_Originally written by **The Lonely Kiwi | 76561198379313880**_
Game Version: 1.1.1005

*===== System Specs =====
CPU Brand: AMD FX(tm)-8350 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

I am a 0.5 Female Ory with a recently dug burrow. When I leave the burrow, there is a good chance that my game state will not be updated to Outside the burrow. I still have the blindness, underground ambiance, and dirt meter. The only way i have found to fix this issue is to go back into the burrow and try again or wait for the forceful leave burrow button in the esc menu.

**Comment by cleafspear** [comment]
issue resolved with new burrow system
