### ISSUE TITLE
[Bug] acro S Grade

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#50]
_Originally written by **???? Frey~Sama???? | 76561198830529278**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
acro S Grade dose no dmg but just bleed

**Comment by Trip-Trap** [comment]
Duplicate #37
