### ISSUE TITLE
[Bug] Walking on top of a burrow as a large dino destroys framerates.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#500]
_Originally written by **Desknight | 76561198138190538**_
Game Version: 1.1.1005

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Apato, rex, acro, para.** 
Map: Rival_Shores

Everytime i walk above a burrow my frames instantly drop from 60 to 1 anytime i move. Even if i move just my camera it drops to 40. It forces me to stay away from any and all burrows unless i want to watch a slideshow.

**Comment by Predatoria** [comment]
Log shows some lag in TrackingComponent.cpp.  I mentioned it to Vipe

**Comment by Predatoria** [comment]
Putting a maybe fix for this
