### ISSUE TITLE
[Bug] Camery frakout carried

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#506]
_Originally written by **RaiOkami | 76561199078056293**_
Game Version: 1.1.1005

*===== System Specs =====
CPU Brand: AMD Phenom(tm) II X6 1090T Processor
Vendor: AuthenticAMD
GPU Brand: AMD Radeon (TM) R9 390 Series
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Rex** 
Map: Rival_Shores

I am a baby rex, and the camera, after .3+ somwhere absolutely freaks out when I am carried by my parent! I heared a friend i nested in say the same when I was carrying them as acro.

**Comment by Trip-Trap** [comment]
Part of the experience id say at this point.
