### ISSUE TITLE
[Bug] I died from being dropped only and inch from the ground

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#508]
_Originally written by **Grapachi | 76561197990899580**_
Game Version: 1.1.1005

*===== System Specs =====
CPU Brand: Intel(R) Pentium(R) Gold G5400 CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Map: Rival_Shores

I was picked up by my parents as an apa and just up and died

**Comment by Trip-Trap** [comment]
#297
