### ISSUE TITLE
[Enhancement] hole in ground, can see trough from side

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5084]
_Originally written by **Zequron | 76561197988771356**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: AMD Ryzen 7 5800X 8-Core Processor             
Vendor: AuthenticAMD
GPU Brand: Radeon RX Vega
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **in cave** 
Map: Rival_Shores

Location: X=2036.435 Y=238302.031 Z=9008.664

A hole that can be seen from the side!

**Comment by Predatoria** [comment]
Fixed this in another ticket
