### ISSUE TITLE
[Bug] The story of how my FPS fell 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#51]
_Originally written by **!Doriner?????? | 76561199002422659**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
after the uptade my fps fell. Everything suits ne according to system requirements.
before the patch i had 50 fps with the highest settings. i now have 3 fps with the lowest settings
i reinstalled all the drivers nothing helps((

**Comment by Trip-Trap** [comment]
Duplicate #32
