### ISSUE TITLE
[Quality of life] Lightning SFX abit overwhelming in volume inside caves

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5102]
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.1149

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Tropeognathus** 
Map: Rival_Shores

I dont think it should be entirely mellowed out, but sometimes its so loud that it sounds like I'm still outside when I'm inside a cave. Theres also the white noise in the back of each one that becomes prominent when its not accompanied by the sound of wind and rain.

**Comment by Predatoria** [comment]
Next patch has different lightning sounds, so I'm going to close this one.
