### ISSUE TITLE
[Bug] A Giant Carnivore- In the Merrkat Dinosaur Burrow.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5114]
_Originally written by **ilovegaming4you | 76561199003311122**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 3GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Aging Up** 
Map: Forest_Island

Is this supposed to happen? I'm the dinosaur that has teh identification skill.. and- I went into the meerkat Dinosaur's Burrow.

**Comment by cleafspear** [comment]
not a Bug, funny tho
