### ISSUE TITLE
[Major Bug] Hole in map

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5115]
_Originally written by **Agent Deviant | 76561198857261973**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: AMD FX(tm)-8320 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Forest_Island

I fell through the map into a hole in the cave near the pond on top of a mountian
Location: X=-97698.219 Y=-162369.438 Z=7751.688

**Comment by Predatoria** [comment]
Fixed hole and cleaned up cave entrance
