### ISSUE TITLE
[Bug] Map hole

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5122]
_Originally written by **Wildberry Poptart ??? | 76561197983739707**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2070 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Ory** 
Map: Forest_Island

See through the map 
Location: X=23730.346 Y=-127958.234 Z=6357.897

**Comment by Predatoria** [comment]
Placed rock here
