### ISSUE TITLE
[Bug] Talent point issue

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5123]
_Originally written by **DragonessAzure | 76561198385188957**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Forest_Island

Cannot put more than one point into brawler stat.

**Comment by Predatoria** [comment]
Likely user error and lacking of prereq talents
