### ISSUE TITLE
[Major Bug] Immediate stale sir buff

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#513]
_Originally written by **EmoPhoenix | 76561198171859598**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2060
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory Hatching** 
Map: Ancestral_Plains

Immediately recieving stale air buff when entering burrow as baby ory, does not matter how deep in the burrow, immediatle have the buff

**Comment by Predatoria** [comment]
Fixed this morning
