### ISSUE TITLE
[Major Bug] Stuck falling in water

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5152]
_Originally written by **dtex | 76561198051077213**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Tropeognathus** 
Map: Rival_Shores

I was playing as a flyer doing some fishing, and suddenly got stuck at the top of the water with a bone cracking sound. Using unjam and unstuck buttons have only resulted in more bone cracking sounds wiht no other results.
Location: X=-5748.169 Y=70717.023 Z=2112.441

**Comment by Predatoria** [comment]
Not sure what to make of this.  Wondering if they got injured by another player and couldn't fly.
