### ISSUE TITLE
[Quality of life] Stuck in a pond

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5156]
_Originally written by **j zendo | 76561198871435005**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **T Rex** 
Map: Forest_Island

My creature got stuck in a pond while drinking. The creature slipped in and couldnt get out because the sides were too steep

**Comment by Predatoria** [comment]
No coordinates
