### ISSUE TITLE
[Bug] Stuck in cave

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5161]
_Originally written by **???????????????????????????????t | 76561198014389089**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **as a midsize t-rex** 
Map: Forest_Island

Stuck in a cave entrance on us east 1. The cave is near a swamp. I am a t-rex, growth of .726 at the time of getting stuck trying to exit the cave.
Location: X=-39971.168 Y=-142974.125 Z=4226.736

**Comment by Predatoria** [comment]
Made arch bigger
