### ISSUE TITLE
[Bug] Cave Growth Issue

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5163]
_Originally written by **HairyBaldy | 76561198161649481**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-10600KF CPU @ 4.10GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Tyrannosaurus Rex** 
Map: Rival_Shores

*Expected Results:* I wanted to walk in and out of the cave after obtaining my drink.
*Actual Results:* I ended up getting stuck inside after growing to a certain size while I was drinking.
*Replication:* I walked in at roughly 1.048 and could not walk out after I grew a little. Somewhere like 1.049 or 1.05
Location: X=2171.356 Y=238168.859 Z=9193.587

**Comment by Predatoria** [comment]
Made arch taller.  Fixed!
