### ISSUE TITLE
[Severe Bug] STUCK

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5172]
_Originally written by **NoSoulWolf.TTV | 76561198053265371**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: AMD Ryzen 9 3900X 12-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 12
===================*
Map: Forest_Island

I was turning and am stuck on the side of this well now. I cant get unstuck out out. I've tried using the unjam and unstuck buttons. 
Location: X=18855.385 Y=-145782.109 Z=12420.354

**Comment by Predatoria** [comment]
Put invisible blocking volumes in the wells.  It should be impossible to get stuck here now
