### ISSUE TITLE
[Bug] Forest Island map issue

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5173]
_Originally written by **EchoAlien | 76561198015374176**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand:        Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 970
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Forest_Island

Location: X=-34601.152 Y=-145576.391 Z=5018.079

Major deathtrap spot in the cave where a 'wall' overlaps with part of the tunnel piece, players can get stuck in it. Found like 5 gores in it from players that died trapped there.

**Comment by Predatoria** [comment]
Adjusted a cave section.  Fixed
