### ISSUE TITLE
[Bug] talents dissapearing

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#518]
_Originally written by **Myrial | 76561199079450246**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand:       Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 4000
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **ory female 1,72** 
Map: Rival_Shores

my talents reset when i laid eggs. i added a point in persistance a few minutes earlier without issue. dont know if this is new or happened before, i know you already did some fixes with this.1,72 ory female.

**Comment by Trip-Trap** [comment]
#887
