### ISSUE TITLE
[Major Bug] Cheater found

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5185]
_Originally written by **[OFTN] Hollesan | 76561198027504899**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **T-Rex** 
Map: Ancestral_Plains

I was on a mountain top and Butah teleported behind me and killed me.

**Comment by Skyedrago** [comment]
Either use of teleporting commands or hacking report that should have been a ticket
