### ISSUE TITLE
[Bug] Stuck in terrain on beach

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5188]
_Originally written by **Bladefeather | 76561198005918057**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Life Cycle** 
Map: Forest_Island

Walking, minding my own business when I fell in a sharp, inverted pyramid shaped hole that I am going to starve and dehydrate in. Tried unjam/stuck and relogging.
Location: X=-158458.141 Y=-87646.805 Z=2139.389

**Comment by Predatoria** [comment]
Smoothed the terrain out here
