### ISSUE TITLE
[Major Bug] soft wall to under map

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5195]
_Originally written by **John | 76561198000437375**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Forest_Island

in pool by death spot, soft wall that you can swim through

**Comment by Predatoria** [comment]
No location.  Cannot find this
