### ISSUE TITLE
[Major Bug] Data loss

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#52]
_Originally written by **Diablo | 76561198450263549**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 3GB
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Apato** 

The server i was on Forgotten Realms had a crash which has been more frequently after the most recent pacth/update, after loading back in i have lost a good 30 minutes to an hour of growth on an Apa maybe longer i was .95+ after the crash dropped me to .85+

**Comment by Thy-Vipe** [comment]
Should be fixed - closing until further notice.
