### ISSUE TITLE
[Major Bug] Burrow crunch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#520]
_Originally written by **Cuddles27 | 76561198288299039**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 760
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Icthy** 
Map: Rival_Shores

*Expected Results:* Not to break a childs legs on leaving a burrow
*Actual Results:* Legs go crunch while taking a child out of a burrow in your mouth
*Replication:*

**Comment by Predatoria** [comment]
Duplicate of 297
