### ISSUE TITLE
[Severe Bug] Getting Kicked 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#527]
_Originally written by **{MM} Doc | 76561199028541007**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

Every 5 minutes or so I get kicked from the game. I freeze then the game just closes I dont know why, but I can't play when I keep getting kicked.

**Comment by Trip-Trap** [comment]
Seems a pretty old bug will close it for now
