### ISSUE TITLE
[Bug] Inescapable river part for apato

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#53]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Apato** 

*Map:* Rival Shores
*Coordinates:* -152515 -7597 8848
*Picture:* https://cdn.discordapp.com/attachments/526080929660403713/721695680090865705/unknown.png

*Description:* This river part is unescapable as the river sides are too steep and rocks block their way in both directions where they could find a spot to get out of the river. The stucks apatos size was 1.3, apatos above also can not get out.

**Comment by Predatoria** [comment]
I'll fix it when we do a round of map fixes on AP.  I like to do them all at once so we don't bloat the github with too many copies of AP being changed.

**Comment by Predatoria** [comment]
Confirmed as fixed on tester
