### ISSUE TITLE
[Quality of life] Ory Blind

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#533]
_Originally written by **Sol | 76561198866539162**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Velociraptors/Pteras** 
Map: Ancestral_Plains

This is more of a suggestion, normally I wouldn't write these, but I saw the category and thought I might as well. 
I think as of right now, the ory blind is completely overpowered. Being able to slow and blind is troublesome enough, but not being able to run or jump is pure death sentence, especially with the range now increased.
The blind should be a means of defense, not a means of herbivore trying to kill carnivore. 
The buff on this ability has made it completely impossible to hunt orys as they can just perma blind you and butt-ride you. It's even worse if you're a velo or a ptera, cause then you just die and all your time has been wasted due to not being able to fly/jump.
Velos and pteras only have mobility for them, taking that away is quite literally discouraging people from even playing those dinosaurs.
And I won't even get into how overpowered it is when an ory is in a herd.

**Comment by Trip-Trap** [comment]
Balance issue was adressed
