### ISSUE TITLE
[Bug] strong blur

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#54]
_Originally written by **'??????????^^ | 76561199012288316**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: AMD A9-9425 RADEON R5, 5 COMPUTE CORES 2C+3G   
Vendor: AuthenticAMD
GPU Brand: AMD Radeon(TM) R5 Graphics
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **all time** 

when you get out of the water, there is a strong blur on the screen, so you cant see anything. When parents raise their child, the same thing happens.

**Comment by Trip-Trap** [comment]
This seems to be happening for non-aquatics/non-semi aquatics mostly. The underwater blurr will stay for a bit before going away, instead of the shift to non-blur being instant like when going into water.

**Comment by Trip-Trap** [comment]
Duplicate #81
