### ISSUE TITLE
[Quality of life] Player wishing death on others, server 1 3/23/2021 5:55 Moutnain Time

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5434]
_Originally written by **A Clout King | 76561198079173835**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i9-9920X CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080
GPU Driver Info: Unknown
Num CPU Cores: 12
===================*
Map: Forest_Island

PlayerName:slyfox196, SteamID:76561198835306879 this is the steam id of the player wishing death on others

**Comment by Skyedrago** [comment]
Potential rule break. Not a bug
