### ISSUE TITLE
[Bug] When it rain you can swim in the dessert cave

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#548]
_Originally written by **Pablo Rookie Gamer | 76561198317981860**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

There is a point in the cave in the big mountain of the dessert that when it rains you can swim.
Location: X=6593.899 Y=230181.859 Z=6449.460

**Comment by Trip-Trap** [comment]
#608
