### ISSUE TITLE
[Bug] Gores coming back fresh after server restart instead of spoilt

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#55]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **N/A** 

*Expected Results:* Gore-spoil level saving and still be the same amount of spoilt after the server restart.
*Actual Results:* All gores will be fully fresh again after a server restart.
*Replication:* Wait for gores and sticks to rot a bit, then restart the server. Note that they will be fresh again.

**Comment by Predatoria** [comment]
We probably aren't going to bother fixing this.
