### ISSUE TITLE
[Bug] Ory glitch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#552]
_Originally written by **SlidingTBebble | 76561198847106602**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2070 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory** 
Map: Ancestral_Plains

i was in my burrow laying down and it said i had lost connection to the server, so i tried to join back in and when i got in i wasnt in my burrow and it didnt spawn me at the entrance, i was floating inside the mountain, not falling, and i could see thru the mountain, the admin had to TP me out becasue it didnt register that i was in a burrow so i didnt have a force leave button. i fear if i would have tried to walk i would have fallen and died.

**Comment by cleafspear** [comment]
this would occur with large burrows that haven't loaded in yet to someone who has hardlogged in the burrow. the player did not wait for the burrow to finish loading

**Comment by Trip-Trap** [comment]
#382
