### ISSUE TITLE
[Bug] Mosa cannot smell and detect fish

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#555]
_Originally written by **chaotical | 76561198995367388**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **While playing a 0.416 mosa** 
Map: Rival_Shores

Issue: the mosa cant detect fish while smelling. 
How to recreate it: play as a mosa, go to an are with fish and smell

**Comment by cleafspear** [comment]
working as intended. mosa is not a piscivore and isnt intended for it to smell fish.
