### ISSUE TITLE
[Quality of life] Default talent tree background when opening the talent menu

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#56]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **N/A** 

*Expected Results:* Talent tree background being the correct deity when opening the Talent Menu is opened
*Actual Results:* When the talent menu is opened the background will only update until a tick happens - unless you spend a talent point ofc.
*Replication:* Go on any creature, spend a telent point. Close the Talent Tree menu and reopen it again. Note that you will have the default background until a tick happens - unless you spend a talent point.

*Evidene:* https://drive.google.com/file/d/1QMMCb0a3mZVPUYXFuxbiA5it_jBgGaoR/view
[Original Report from Official]

**Comment by Predatoria** [comment]
I successfully reproduced this in PIE.

It has been fixed and tested in PIE.

Marking this as potentially fixed!
