### ISSUE TITLE
[Quality of life] Name Tag Glitch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#57]
_Originally written by **Andromeda | 76561198189428795**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: AMD FX(tm)-6300 Six-Core Processor             
Vendor: AuthenticAMD
GPU Brand: AMD Radeon R9 200 Series
GPU Driver Info: Unknown
Num CPU Cores: 3
===================*
Context: **In a group.** 

I keep encountering on multiple dinos this glitch where, when you or a group member exits render range the nametags go to the upper left hand corner of the screen and strobe out. It makes going to group members kind of difficult as I have to turn on and off nameplates, or stay within render range of their dino in order to avoid the glitch.

**Comment by Predatoria** [comment]
I can reproduce this.  I've noticed it frequently.  I'll be working on a fix.

**Comment by Predatoria** [comment]
Fixed in PIE!  Marking this one as potentially fixed.

**Comment by Trip-Trap** [comment]
Only a slight hitch now when the transition happens, before it assigns the icon to the proper place again. Will not strobe out in the upper left corner anymore tho. If its more of an issue on servers with big population we can open this issue up again.
