### ISSUE TITLE
[Bug] lighting glitch 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#58]
_Originally written by **Spoooky | 76561198247642756**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: AMD Ryzen 3 3200G with Radeon Vega Graphics    
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Acro ** 

I was nested in as acro on rival sures and we were at the top of snow mountain and when they picked me up and put me down on the ice my lighting would glitch and it would all be dark

**Comment by Trip-Trap** [comment]
Very likely related to issue #41. When the child was put on the ice it probably "fell into water" for a brief second - as it open happens when put down, and by that touching the water beneath the ice which causes the "black-out".

**Comment by Trip-Trap** [comment]
Duplicate #41
