### ISSUE TITLE
[Bug] Auto Eating

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#584]
_Originally written by **Dakryn | 76561198019255138**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **I got to eat really fast....** 
Map: Ancestral_Plains

If you press interact on a burrow you cannot enter, you can eat while walking.

**Comment by Trip-Trap** [comment]
#779
