### ISSUE TITLE
[Quality of life] dinos working together that shouldn't be

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5879]
_Originally written by **ScooterMcDermin | 76561198090004442**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: AMD Ryzen 7 3700X 8-Core Processor             
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2070
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Rival_Shores

multiple species of dinos are working together on this island

**Comment by cleafspear** [comment]
not a bug, but more of a player interaction issue
