### ISSUE TITLE
[Bug] Velo Getting Stuck in Trees

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#59]
_Originally written by **BlackPanda | 76561198929224037**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **I was a velo jumped onto a swamp tree and got sucked there my intire life i couldnt leave i watched the ppl around me age and die i watched many fights i watched the making of earth and the ending the tree has lachted ontio me for 600 years * but no actually pls fix the trees my velo is still stuck for 3 days*** 

The swamp trees are glitched and if u jump onto them sometimes u get stucck there 
unstuck/unjam dosnt work

**Comment by Trip-Trap** [comment]
Most of these trees were fixed. Will close this issue as reports of this have deminished.
