### ISSUE TITLE
[Bug] talents gone when laying eggs

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#594]
_Originally written by **Myrial | 76561199079450246**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand:       Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 4000
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **ory female 1,8+** 
Map: Rival_Shores

again today my talents reset when i laid eggs. few days ago it happened and babies from those eggs was really bad. removing these eggs now... the talents came back a few minutes later and babies was good again. will see how it goes this time.

**Comment by Trip-Trap** [comment]
#887
