### ISSUE TITLE
[Bug] Rain Glitch, Ptera Dive

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#598]
_Originally written by **MamaItoshii | 76561198953573937**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: AMD Ryzen 7 1700 Eight-Core Processor          
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **during a growth storm.** 
Map: Rival_Shores

When diving to gain momentum as a Ptera the rain animation disappears. The sound continues to play, it is only the visual effect of the rain that is affected. Can provide video if needed.

**Comment by Predatoria** [comment]
Seems to have been fixed when we swapped our rain particles out.
