### ISSUE TITLE
[Bug] Can't Send Mate Request To My Mate

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#600]
_Originally written by **TheNightsSecrets | 76561198234195244**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA Quadro K2000
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

Having a problem of not being able to send my mate a, mate request from either tab or command, it has been like this past few days, though was told it should end in few hours and yet it still has not.

Me and friend loged in first time today and make some eggs but it still coming up with,

Your request to *Username* to mate with you could not be sent! *username* refused such from you recently.

They can send me a mate reuqest fine and it works but for me it is not working, not if if a bug?

They did press reject a day ago from mis click but it shoulda ended by now.

**Comment by Trip-Trap** [comment]
Lag issue, that was fixed, closing report
