### ISSUE TITLE
[Severe Bug] cave swimming bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#608]
_Originally written by **Rick | 76561198992290906**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) Iris(R) Pro Graphics 580
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

so in the desert cave on rival shores somewhere in the tunnel entrance if you touch the left wall when you come in you start swimming and it can cause you to go under the map and die.
Location: X=6742.251 Y=230546.078 Z=6372.846

**Comment by Predatoria** [comment]
Moved the water source, fixed!
