### ISSUE TITLE
[Quality of life] while swimming upsidedown or walking over blackspots create dead views

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#61]
_Originally written by **Hollow | 76561198196470533**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Swimming and diving in waterponds** 

its bugs the hole view of the game and turns shadows light and rendering all to a shadow like fog
this hinders the player from playing and view the game 

How i found it: i swim upside down in a pond of water wile doing so i found a shadow like black spot that turnd my hole game to a black foggy like shaders.. 

cent play the game like this and have to restart the game wen this heppends

**Comment by Trip-Trap** [comment]
Duplicate #41
