### ISSUE TITLE
[Quality of life] Low frame rate in this specific area despite using high end pc

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#614]
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Icthyovenator** 
Map: Ancestral_Plains

Playing as icthyovenator, if it runs fine without other players then perhaps it may be when its populated- or perhaps even related to the burrow that im standing right next to.

**Comment by Predatoria** [comment]
Known issue.  It is standing on burrows, or plants being picked up.  Going to close this due to duplicates.
