### ISSUE TITLE
[Quality of life] [K.O.S] Daged and BeoRem killed me while food was nearby.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#6147]
_Originally written by **putrid carcass | 76561198295886482**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Ancestral_Plains

Their reasoning was "why would we let you live? We're all carnis." even though we are not currently on a realism server. BeoRem also tried to say K.O.S mean't something in German and did not mean Kill On Sight. BeoRem has been like this all night, has admitted to, and has clearly killed for sport and to see player's upset. I did not agitate them. I was simply walking by, looking for water. They ran and attacked first.

**Comment by cleafspear** [comment]
this is a private server issue, not a bug
