### ISSUE TITLE
[Severe Bug] Op elasmo grab

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#628]
_Originally written by **Cuddles27 | 76561198288299039**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 760
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Icthy** 
Map: Rival_Shores

I found out that a 2.0 elasmo can lift a 1.5+ icthy, after multiple friends had been grabbed and drowned

**Comment by cleafspear** [comment]
this is normal if the elasmo has inherits in grab talents
