### ISSUE TITLE
[Bug] Test Map Report

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#63]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.939

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **jk** 
Map: Rival_Shores

There is a spot here that eats velo. Toes first and leaves the tail tip for last. Very bad :<

Location: X=192261.000 Y=330192.000 Z=5610.143

**Comment by Trip-Trap** [comment]
Test
