### ISSUE TITLE
[Bug] Jump into Water turns Beach Texture Black

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#64]
_Originally written by **[LUST] ???Carno Reeves??? | 76561198872224641**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: Microsoft Basic Display Driver
GPU Driver Info: 
Num CPU Cores: 6
===================*
Context: **Velo** 

After I jumped into the Water (Tried it with Velo), the whole Beach texture turned Black.  To check If it's a new bug, we tried to reproduce the Bug, with another Velo from my Pack. He jumped into the Water aswell and the same bug appeart.

**Comment by Trip-Trap** [comment]
Duplicate #41
