### ISSUE TITLE
[Bug] Fish highlight does not always work with Ichthy

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#644]
_Originally written by **IMevolved | 76561198269013026**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ichthy** 
Map: Rival_Shores

Fish that are far away can be seen, but when you get close they disappear and I can't find them other than just using sight. Sometimes it does work when up close but it is inconsistent.

**Comment by cleafspear** [comment]
issue resolved with ocean rework
