### ISSUE TITLE
[Bug] Elasmo

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#645]
_Originally written by **Seba | 76561198019060530**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: AMD Ryzen 7 3800X 8-Core Processor             
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Ichty** 
Map: Rival_Shores

Elasmo , is to fast . Ela 2.0 can grab ichty 2.0 this is  joke. Guys please nerf elasmo...

**Comment by Trip-Trap** [comment]
actually... "got fixed" in one way or the other :'''''''''''''''''D
