### ISSUE TITLE
[Bug] Resolution Scale at Options Settings

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#647]
_Originally written by **Martijn | 76561197970762634**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand:        Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 980
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

My Resolution scale when i increase the slider or whatever its called it always drop back to zero or all the way to the left even when i press apply button

**Comment by Trip-Trap** [comment]
Cant reproduce, hope its fixed with the setting remake
