### ISSUE TITLE
[Major Bug] pteras crash server on purpose

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#65]
_Originally written by **Nosferatu | 76561198381624932**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3600 6-Core Processor              
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **was just playing and boom** 

Please do somehting about pteras they make 40 eggs and the server crsashes on lost beasts i lost like 0.500 growth point diue to it.......since pteras can get food so easily nerf them or do soemthing about them if i play 3 hgours a server crashes 5 times and always ptera players in chat : ;) eggooosss

**Comment by Predatoria** [comment]
Have not seen this on sentry.  Crash likely was not related to this.
