### ISSUE TITLE
[Bug] i dead

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#657]
_Originally written by **jaimito0425 | 76561198437006415**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  
Vendor: AuthenticAMD
GPU Brand: AMD Radeon(TM) Vega 8 Graphics
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **i was a ptera 1.9 but I had lag and I got out of the game and appeared dead** 
Map: Rival_Shores

i was a ptera 1.9 but I had lag and I got out of the game and appeared dead

**Comment by Thy-Vipe** [comment]
Not enough info, this seems to me that the ptera died after getting disconnected.
