### ISSUE TITLE
[Bug] Saving skins

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#66]
_Originally written by **Squish Bee | 76561199038664058**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **this game** 

my skins are being deleted, even after I save them

**Comment by Trip-Trap** [comment]
#461
