### ISSUE TITLE
[Severe Bug] i cant damage anybody 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#665]
_Originally written by **chimp | 76561198366507885**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: AMD FX(tm)-6300 Six-Core Processor             
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 3
===================*
Context: **i dont even know when** 
Map: Rival_Shores

whenever i hit someone i do no damage and they dont make a noise indicating that they have been hit. But my damage shows on the bottom of the screen  and bloods comes off of them?

**Comment by Trip-Trap** [comment]
server lag issue
