### ISSUE TITLE
[Bug] Lying down Twice switched Camera Movement in the Modell of the Velo

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#67]
_Originally written by **[LUST] ???Carno Reeves??? | 76561198872224641**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: Microsoft Basic Display Driver
GPU Driver Info: 
Num CPU Cores: 6
===================*
Context: **Velo** 

I wanted to check some Spots, to see the Camera Movement from the Velo. I've noticed that when you Lying down twice (Sleep Mode), the Camera switches into the Modell of my Velo. Same happend to the other Velos of my Pack. To check If it's only a Problem on the Ptera Mountain, I walked over to the Jungle and Desert Isle to try it aswell. Same Bug appeard on this Isles aswell. Same with lying down on Rocks, Land and Trees.

**Comment by Predatoria** [comment]
I can reproduce this with sit, but not sleep, playing as a 3.0 velo and sitting on the slope on BB_Test_Map

**Comment by Predatoria** [comment]
Fixed by disabling Velo's camera lowering during sitting and laying down
