### ISSUE TITLE
[Major Bug] Shader turned full black entering the water on top of snow mountain

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#68]
_Originally written by **Vistani | 76561198064621346**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: AMD Ryzen 3 2200G with Radeon Vega Graphics    
Vendor: AuthenticAMD
GPU Brand: AMD Radeon(TM) Vega 8 Graphics
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **A Velo** 

*Expected Results:* Shader changes to match the water, and then upon exiting returns to normal
*Actual Results:* Shader turned full black inside the water, and then did not return to normal. 
*Replication:* Be a velo, enter the water on top of snow mountain. 

A note, entering/exiting full cover did not remove this issue for me. Nor did entering/exiting the water again.

**Comment by Trip-Trap** [comment]
Duplicate #41
