### ISSUE TITLE
[Bug] Krono lunge bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#681]
_Originally written by **Anatze | 76561198302304278**_
Game Version: 1.1.1013

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

*Expected Results:* Krono should not recover it's ability power while charging it's lunge
*Actual Results:* Krono recover it's ability while charging. So it makes lunge cost on 20-30% less to consume
*Replication:* Press "Shift" button while charging your lunge on Krono

**Comment by Predatoria** [comment]
Fixed next tester patch
