### ISSUE TITLE
[Bug] Broken groups

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#6818]
_Originally written by **'-???Oxa3???-(Zoe)' | 76561198072049152**_
Game Version: 1.1.1231

*===== System Specs =====
CPU Brand: AMD Ryzen 7 5800X 8-Core Processor             
Vendor: AuthenticAMD
GPU Brand: AMD Radeon RX 5700 XT
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **can't join groups  i have to ask an admin to inv me to the group idk if it's realy bad :0** 
Map: Rival_Shores

in mixpacks of chill servers  you can't join a group you need an admin to inv you

**Comment by Trip-Trap** [comment]
Was never a thing
