### ISSUE TITLE
[Bug] Krovo lunging with meat

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#682]
_Originally written by **Anatze | 76561198302304278**_
Game Version: 1.1.1013

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Krono** 
Map: Rival_Shores

*Expected Results:* Krono can't lunge with meat in it's mouth
*Actual Results:* Krono can lunge with meat
*Replication:* Put the meat near your head as a krono, start charging and grab your meat in this moment, then stop charging and FLY

**Comment by Predatoria** [comment]
Fixed next tester
