### ISSUE TITLE
[Bug] Dart refill it's ability pull with no timer

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#683]
_Originally written by **Anatze | 76561198302304278**_
Game Version: 1.1.1013

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

*Expected Results:* Dart should recover it's ability/stamina in 2 seconds it's been used
*Actual Results:* After creature used it's dart, ability power can immediately start to recover
*Replication:* After you used dart on aquatic/semi aquatic - press the Shift or C button once

**Comment by Predatoria** [comment]
I can't seem to reproduce this

**Comment by Predatoria** [comment]
This was reproduced and fixed on tester.
