### ISSUE TITLE
[Severe Bug] Abuse with console commands

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#685]
_Originally written by **Anatze | 76561198302304278**_
Game Version: 1.1.1013

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

*Expected Results:* Console commands that can broke fair gameplay should be blocked
*Actual Results:* Vipe sai that will block them, but how you can see no
*Replication:* Go on a server that allows to use console commands, use this commands: 
r.LimitRenderingFeatures
a.URO.Draw
r.viewdistanceScale
a.visualizeLODs
Then logg out from this server, commands will still be activated and then you can go on some other server

**Comment by Predatoria** [comment]
Blocking and closing.  Not posting these in the public / tester patch notes.
