### ISSUE TITLE
[Bug] Ory "burrow creating hud" get stuck

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#686]
_Originally written by **Anatze | 76561198302304278**_
Game Version: 1.1.1013

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

*Expected Results:* player should not see ory burrow creating icon if they not digging an enterance 
*Actual Results:* This icon can get stuck on a player screen, and only relogging can solve it
*Replication:* Start to dig an enterance and logg in to save slots (and you should be still digging), or go in to the creacture select screen

**Comment by Predatoria** [comment]
Fixed next tester patch!
