### ISSUE TITLE
[Severe Bug] Texture glitch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#69]
_Originally written by **Vex | 76561198035390794**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2070 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Rival Shores on the icey peak of the island. If you enter the water, upon leaving, all textures are removed and placed with black. I hope this gets fixed soon, I lost a dino I had around 40 hours of growth on due to this. :/

**Comment by Trip-Trap** [comment]
Duplicate #41
