### ISSUE TITLE
[Bug] Blind Glitcha

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#70]
_Originally written by **RustyKing | 76561198799330872**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand:         Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 3GB
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Megalo** 

Whenever I go into the water and come out, I am blind and cannot see.

**Comment by Trip-Trap** [comment]
Duplicate #41
