### ISSUE TITLE
[Major Bug] can not map keys

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#71]
_Originally written by **TheTreeDragon | 76561198892480211**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **always** 

can not move forward because the forward control will not map to any key

**Comment by Trip-Trap** [comment]
Duplicate of #322 will close this issue.
