### ISSUE TITLE
[Enhancement] Glitchy visuals

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#72]
_Originally written by **Sailor Moon | 76561198968972143**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
When it rains on any of the maps, the ground has a visual glitch where it flickers different colors brightly

**Comment by Trip-Trap** [comment]
Duplicate #38
