### ISSUE TITLE
[Bug] Pick up Glitch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#727]
_Originally written by **Moma_Karma | 76561198073738676**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Rival_Shores

a friend was going to pick up a baby pachy when the pachy glitched behind it while still being held

**Comment by Predatoria** [comment]
This is a duplicate of a known grab issue.
