### ISSUE TITLE
[Bug] Colored Unedible crystals despawning in Burrows 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#728]
_Originally written by **CosmicGhost | 76561198170621081**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: AMD A8-9600 RADEON R7, 10 COMPUTE CORES 4C+6G  
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

I have a den with many many colored crystals, i spawned in a blue one and tried to dig another blue beside it when the crystal just despawned without touching the meshcube of dirt it sat on.
Location: X=-270643.125 Y=-141508.672 Z=5240.828

**Comment by Predatoria** [comment]
I believe this is a report of intentional, 'decorative mesh / actor' despawning mechanics that were implemented to keep players from digging themselves stuck into rocks and stuff.
