### ISSUE TITLE
[Bug] Sleep bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#73]
_Originally written by **Intrique | 76561198336049231**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: AMD Ryzen 7 2700X Eight-Core Processor         
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Velociraptor, Rival Shores** 

On Rival Shores, I hit R twice to sleep and suddenly my screen was pushed way in, which i found odd as it was working until recently.

**Comment by Trip-Trap** [comment]
Duplicate #31
