### ISSUE TITLE
[Quality of life] Aqua Affini-tree

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#732]
_Originally written by **vulture | 76561198324288318**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

In this spot there are jungle trees growing out of the water

**Comment by Trip-Trap** [comment]
No coords, closing the issue
