### ISSUE TITLE
[Enhancement] The administrator

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#7375]
_Originally written by **Mc | 76561198430026224**_
Game Version: 1.1.1239

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

I need to buy eggs，apato and rex，What should I do？

**Comment by cleafspear** [comment]
not a bug
