### ISSUE TITLE
[Severe Bug] Visual glitch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#74]
_Originally written by **Valadriel | 76561198133366309**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 620
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Beasts of Bermuda** 

I fell into a pool and when i reached the surface the world turned black, now the only thing i can see is water surfaces

**Comment by Trip-Trap** [comment]
Duplicate #41
