### ISSUE TITLE
[Bug] Burrow Display 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#748]
_Originally written by **Toshii~ | 76561198254439760**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **ory** 
Map: Rival_Shores

 after stopping to create an entry it still showed up the burrow- in display and neither unstuck nor unjam did help

**Comment by Predatoria** [comment]
Works fine for me.  Not enough info
