### ISSUE TITLE
[Bug] Zooms in when Sleeping

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#75]
_Originally written by **MysticTulip | 76561198135362013**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Velociraptor** 

I don't know if this happens to all dinos but when I am playing my Velociraptor I rest during a storm or to heal it sometimes has a annoying habit of zooming up close to the Velo that you can see only it's feathers and nothing else. It seems it only happens when my Velo is laying near anything like a rock or trees even small plants. It's annoying and gets me worried because I wouldn't be able to see those around me for any predators. This wasn't a issue before the update but now it is so hopefully you can look into it.

**Comment by Trip-Trap** [comment]
Duplicate #31
