### ISSUE TITLE
[Bug] No death icon

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#76]
_Originally written by **Squid Knee | 76561198040493007**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 4600
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **bob** 

After respawning and leaving a gore, my slot usually shows as the dino being dead. When I did it this time, there was no dead dino slot, just create new and my other dinos i already had previously. im worried this could mean others who die to a glitch or rule break will permanantly lose their dino and not be able to get it back via revive.

**Comment by Thy-Vipe** [comment]
The code that runs when you force respawn is different than the one that runs when spawning normally. Forcing the way through will delete the creature.
