### ISSUE TITLE
[Major Bug] Screen 'jumping'

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#760]
_Originally written by **galaxyfish | 76561198406668635**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 520
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Map: Rival_Shores

The entire game window is flickering and 'jumping' every few seconds; nothing seems to help or fix it

**Comment by Predatoria** [comment]
Sounds like the player didn't enable vertical sync.
