### ISSUE TITLE
[Severe Bug] unstuck not working

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#768]
_Originally written by **WendyWomp | 76561199038352308**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700T CPU @ 2.90GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Velo** 
Map: Test_Performance

Velo stuck in climbing pose and can't move

**Comment by Trip-Trap** [comment]
likely fixed
