### ISSUE TITLE
[Major Bug] roll back

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#77]
_Originally written by **Nosferatu | 76561198381624932**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3600 6-Core Processor              
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **yes** 

second time i lost growth 0.5 amd the wsecond time i lost 0.6  in 2 days rollback this awfully pathc that was not ready for public at all

**Comment by Trip-Trap** [comment]
Duplicate #52
