### ISSUE TITLE
[Bug] Hit exit/enter burrow while being carried

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#771]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.1023

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory burrowing** 
Map: DM_Caldera

*Expected Results:* Not being able to leave burrow while carried.
*Actual Results:* If you are carried you can still use the burrow entrance/exit, resulting in some glitchy behaviour.
*Replication:* Carry someone to a burrow entrance/exit. Let that player use the entrance/exit. Note that it will tp the player to the entrance and let them enter.

**Comment by Predatoria** [comment]
Fixed next tester patch
