### ISSUE TITLE
[Quality of life] One shot by lightning with a 1.0 Rex

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#7722]
_Originally written by **Annonnymous771 | 76561198137982973**_
Game Version: 1.1.1239

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Growing t-rex for like 4 hours. One shot by lightning randomly.... no, just no** 
Map: Rival_Shores

Got randomly one shot by lighting with a t-rex i grew for like 4 hours. He just was 1.0 growth. No, stop that, no

**Comment by cleafspear** [comment]
this was due to the rex not having 3/3 weather. working as intended.
