### ISSUE TITLE
[Severe Bug] Dinosaur Disappeared

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#78]
_Originally written by **Andromeda | 76561198189428795**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: AMD FX(tm)-6300 Six-Core Processor             
Vendor: AuthenticAMD
GPU Brand: AMD Radeon R9 200 Series
GPU Driver Info: Unknown
Num CPU Cores: 3
===================*
*Expected Results:* Character save selection screen to be fully functional with a list of dinos that you have grown - all of which still there from previous playthroughs.

*Actual Results:* Dinos go missing because save files are either corrupt or a server data rollback.

*Replication:* Not sure how to replicate it.

I started growing a Megalo last night with my boyfriend and a group of friends and grew to about 1.2, when we logged out we were all still alive and well, and this morning when I logged in my Megalo had completely disappeared. No death log, no character selection stating it had died, only that I didn't have it anymore. I'm not sure if it is a currently known bug, or if it is known, but I figured it would be best to make a bug report so that more dinos don't disappear.

**Comment by Trip-Trap** [comment]
Duplicate #52
