### ISSUE TITLE
[Bug] Orys give each other adrenaline.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#780]
_Originally written by **Scanova the Carnotaurus | 76561198073961258**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Oryctodromeus** 
Map: Rival_Shores

Grouped oryctodromeus can give themselves adrenaline through pocket sand. Unsure whether this is intentional or not.

**Comment by Predatoria** [comment]
Fixed it next tester patch
