### ISSUE TITLE
[Major Bug] Losing Growth 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#79]
_Originally written by **-MM- Daddy Draco | 76561198101239550**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 4600
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
I lost a good hour or so worth of growth thanks to a server crash

**Comment by Trip-Trap** [comment]
Duplicate #52
