### ISSUE TITLE
[Severe Bug] Good staff read ! :D

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#7947]
_Originally written by **Maelstream25 | 76561198258307146**_
Game Version: 1.1.1239

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

I particularly find your work quite disappointing.

I have 9h00 of prog on a Kronosore.

I got killed by a baby rex, he took 30 minutes to kill me.

All because, on dry land, slowness is matched only by your incompetence and your stupidity.

9:00 am killed by a baby. you are the laughing stock of Dinosaur survival games. Fewer and fewer people will come over the years, and you could finally eat your macdo with the money earned by decent people.

You are morons and very very tall incompetent between 18 and 30: 'D

**Comment by cleafspear** [comment]
cant fix stupidity.
