### ISSUE TITLE
[Bug] Krono attacking without air

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#80]
_Originally written by **|Pride| Lucky2punch | 76561198261304745**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: AMD FX(tm)-6300 Six-Core Processor             
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 3
===================*
Context: **While growing a krono and testing out what happens if i run out of air** 
Map: Rival_Shores

I played krono today and found out i can still attack although on the debuff it says that if i run out of air im not able to attack or anything, not the lunge just the normal attack

**Comment by Predatoria** [comment]
Can reproduce this in PIE.  This is also present on Elasmosaurus.  Fixed and tested it in PIE.

**Comment by Thy-Vipe** [comment]
Mah man
