### ISSUE TITLE
[Severe Bug] Broken Good Parent tallent

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#802]
_Originally written by **Anatze | 76561198302304278**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

*Expected Results:* Good parent should improve the inherits for your kids
*Actual Results:* The more points you have in Good parent - the worse your kids would be

**Comment by Katze-eng** [comment]
seems like after the new patch got uploaded, gp starts to work

**Comment by Trip-Trap** [comment]
Marking it as fixed then and closing the issue
