### ISSUE TITLE
[Quality of life] Unfair MUTE

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#8022]
_Originally written by **Neli | 76561198066879512**_
Game Version: 1.1.1239

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1080 Ti
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Official 2 EAST US** 
Map: Rival_Shores

I was muted for 24HR for jokingly saying "No russian communists" in chat by an admin after the "English Only" rule was announced and was instantly muted by Admin. The problem is player named VenomB did the same thing and the only thing Admin said was "We dont say that here Venom". That is extremely not fair to allow any other person to say that and to mute 2 others because of a joke.

**Comment by cleafspear** [comment]
not a bug
