### ISSUE TITLE
[Quality of life] drought during storm

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#807]
_Originally written by **Pierce Hawthorne | 76561198385155962**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

ive been noticing that if it rains when the ocean is dropping the ocean will continue to drop, i was wondering if this is intended or not (if so could someone explain it to me, my discord name is kellemen, i recently contacted twilight for a rule break if that will make it eaiser to find me on discord) if this isnt then i would like to make it known that the rain does not stop the drought and the drought will continue its process during the storm (very noticible on ancestral plains)

**Comment by Trip-Trap** [comment]
Likely just tide going down. And tide is very noticeable on AP compared to RS
