### ISSUE TITLE
[Quality of life] Blurry after got Grabbed/or after getting out of water 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#81]
_Originally written by **???~Kambori~??? | 76561198317416950**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: AMD FX(tm)-6300 Six-Core Processor             
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 3
===================*
Map: Rival_Shores

sometimes after i got grabbed, or i got out of the water or just random, mah whole screen got blurry, it fixes from alone but still kinda annoying if u cant see smth for a while

**Comment by Thy-Vipe** [comment]
Should be fixed.
