### ISSUE TITLE
[Bug] Talent Wipe - Visual Bug - Fixed by relogging onto server. 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#818]
_Originally written by **Yucky | 76561198003960531**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ory** 
Map: Rival_Shores

*Expected Results:* 
*Actual Results:* 
*Replication:* 
Location: X=-227313.922 Y=-14029.862 Z=18328.045

**Comment by Trip-Trap** [comment]
#887
