### ISSUE TITLE
[Quality of life] Floating apa spikes

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#819]
_Originally written by **Gling | 76561198120397137**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

One of the dorsal/back spines is floating, high satiate/overfed if that affects it

**Comment by Trip-Trap** [comment]
Closing this as apa gets a remodel
