### ISSUE TITLE
[QualityOfLife] Grass missing on AP

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#82]
_Originally written by **Eleven | 76561198041582355**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: AMD Ryzen 7 2700X Eight-Core Processor         
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2070
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Ancestral_Plains

the static vegetation is missing or gone  in the Ancestral_Plains Map.
only eatable plants appear in the game  this happed today after the last patch

**Comment by Predatoria** [comment]
Loaded AP in PIE.  Played in editor.  Can interact with soft foliage, all rocks / trees / foliage objects seem to be present and working as intended.

**Comment by Trip-Trap** [comment]
The non-interactable grass is missing, not interactable foliage. Updated the report.
![grafik](https://user-images.githubusercontent.com/56919683/84711864-8ec52b00-af67-11ea-95ef-a768af076db3.png)

**Comment by Trip-Trap** [comment]
Before:
![Desktop Screenshot 2019 12 28 - 00 16 04 29](https://user-images.githubusercontent.com/56919683/84712474-faf45e80-af68-11ea-8b58-2b1e7689310e.png)

**Comment by Predatoria** [comment]
We had a similar issue on Rival Shores a while back.  I don't remember what the issue was or how it was fixed.  @Thy-Vipe do you know?
