### ISSUE TITLE
[Bug] Krono group

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#823]
_Originally written by **Camilla | 76561198028667515**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 980
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

it said that you can be more then 2 but you can only be 2 before getting debuff

**Comment by Predatoria** [comment]
Sounds like a private server config file / posted rules discrepancy.  We've not seen any issues with soft caps not working.  Going to assume user error and close this.
