### ISSUE TITLE
[Bug] Delete Item

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#83]
_Originally written by **{BG} Modon55 [GER] ??? | 76561198833882155**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Ancestral_Plains

If I will change my species, i have chose to delete my species.

**Comment by Predatoria** [comment]
This is intended functionality.  One must choose to delete their species or wait out the combat timer to return to the save select screen.  Marking as not fixing
