### ISSUE TITLE
[Bug] edit burrow view distance bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#855]
_Originally written by **Beenless | 76561198213334393**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **ory** 
Map: Rival_Shores

climed in an old burrow, when i exit the burrow my view distance is the same as being in a burrow. i also have the sand bucket hud.

**Comment by Predatoria** [comment]
Not sure how to reproduce this.  We've already tried to protect against this state jam in a few different ways.  I'd need more info
