### ISSUE TITLE
[Bug] Skin issue

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#859]
_Originally written by **Annie | 76561198143131168**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD FX(tm)-8350 Eight-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 960
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Anything** 
Map: Rival_Shores

It looks like if you make a skin and save it, then leave the game it deletes the skins you save.

**Comment by Trip-Trap** [comment]
#461
