### ISSUE TITLE
[Quality of life] cant mate

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#860]
_Originally written by **witchphrodite | 76561198331121268**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Xeon(R) CPU           E5530  @ 2.40GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **apatosaurus** 
Map: Rival_Shores

cant mate at all, sent tons of request and its not happening :c

**Comment by Predatoria** [comment]
This is a symptom of the server issues we were seeing after the latest patch.  I'm going to close this since it's a known issue / symptom bug report.
