### ISSUE TITLE
[Quality of life] no dmg

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#861]
_Originally written by **witchphrodite | 76561198331121268**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Xeon(R) CPU           E5530  @ 2.40GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

There is no carnivore that can do dmg to anyone :c

**Comment by cleafspear** [comment]
this is closed after testing, unable to reproduce anymore on 1130
