### ISSUE TITLE
[Bug] JUST READ IT

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#8613]
_Originally written by **Erostuno | 76561198012019107**_
Game Version: 1.1.1239

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Map: Rival_Shores

*Expected Results:* UNMUTE ME 
*Actual Results:* 
*Replication:* 
Location: X=104750.305 Y=210361.406 Z=5085.490

**Comment by cleafspear** [comment]
no.
