### ISSUE TITLE
[Bug] Carrying any creature bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#863]
_Originally written by **Sicario | 76561198302304278**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Ancestral_Plains

*Expected Results:*  Grabbed creature should not be able to lay down and heal
*Actual Results:* Grabbed creature can lay down right in the mouth
*Replication:* Be grabbed and then press Unjam, then you can use R button to lay down and heal properly. Also some times that makes babys running in sleeping animation

**Comment by Predatoria** [comment]
I blocked the use of this next tester patch while grabbed.
