### ISSUE TITLE
[Bug] Stale Air debuff

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#865]
_Originally written by **>^Catilena1890^< | 76561198232735148**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory** 
Map: Rival_Shores

*Expected Results:*  Don't get stale air debuff while in burrow
*Actual Results:* Stale Air debuff despite being under exit hole
*Replication:* dig a burrow and lay down.
Location: X=28250.000 Y=233875.000 Z=4735.202

**Comment by Predatoria** [comment]
Suspect maybe it's possible that in certain areas, the character's location may be getting rounded to the node beneath the, which would cause this.  Nonetheless, I cannot seem to reproduce it.

**Comment by Predatoria** [comment]
Tried as a 0.2 ory and getting as low as I could.
