### ISSUE TITLE
[Major Bug] wasd controls broke

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#866]
_Originally written by **???AA??? Morose | 76561198076369754**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 with Max-Q Design
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ptera** 
Map: Rival_Shores

I lost my ability to move my ptera while I was in the air for some reason. The only keys affected were the WASD controls.

**Comment by Predatoria** [comment]
Not sure how to reproduce this.
