### ISSUE TITLE
[Major Bug] Able to see underground dinosaurs

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#868]
_Originally written by **Koalaballa | 76561198076707464**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Pteranodon** 
Map: Rival_Shores

Was flying around as a pteranodon and was using my scent when I noticed I was able to see any underground orodromeus. This feels entirely unfair to them and I feel as if this was an unintended bug.

**Comment by Predatoria** [comment]
Not really sure what to make of this.  From a first pass, I can't see anything wrong.  I'm wondering if they simply mean they can smell burrow entrances.  If so, that's intentional.
