### ISSUE TITLE
[Major Bug] Random jumping

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#869]
_Originally written by **??? TheOnceTrueKing ??? | 76561198262587445**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD FX-8370 Eight-Core Processor               
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Elasmo** 
Map: Ancestral_Plains

I was an elasmo and it threw me out of the water while i was in GL, without hitting any buttons

**Comment by Predatoria** [comment]
I have no idea how to reproduce this.
