### ISSUE TITLE
[Bug] meshing

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#87]
_Originally written by **Twin | 76561198345597967**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

i found a way to get threw the wall 
Location: X=-53436.543 Y=333177.875 Z=12126.659

**Comment by Predatoria** [comment]
I'll round this up when we go through all of our map bugs.

**Comment by Predatoria** [comment]
Fixed
