### ISSUE TITLE
[Bug] Egg Icons disappear

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#873]
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Parent of eggs** 
Map: Rival_Shores

*Expected Results:* Egg icons to stay on the egg.
*Actual Results:* If you pick up an egg its icon will disappear. If you open ESC menu its icons will disappear. The egg icons will not return.
*Replication:* Make some eggs. Note that the icons will appear as soon as you lay them. Pick an egg up. Note that it will disappear as you pick it up and not reappear when you put it down. All the egg icons will disappear when you open the ESC menu and will not come back when you close the ESC menu.

*additional note: it was reported that eggs will also not rejoin group after restart.

**Comment by Predatoria** [comment]
Should be fixed next tester patch.
