### ISSUE TITLE
[Bug] Egg Icons

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#874]
_Originally written by **Queenie | 76561198841434722**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600X Six-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2060
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ptera** 
Map: Rival_Shores

The Icons for eggs disappear after being layed after about 20 minutes

**Comment by Predatoria** [comment]
Likely a less specific duplicate of issue 873
