### ISSUE TITLE
[Bug] para model visual bug when an egg hatches

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#876]
_Originally written by **Beenless | 76561198213334393**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **para** 
Map: Rival_Shores

Upon a para hatchling using their ability key to hatch from an egg, from another players perspective the egg switches to a default baby para model (looks about 0.3 size and with the idle animation). this shows for a couple seconds then shrinks to the actual hatched player with the skin they hatched with. 

i am not a para at the moment, but have seen this visual bug occur a couple times as the para eggs have been hatching

**Comment by Trip-Trap** [comment]
Just how it is with every egg needs a bit of time to update
