### ISSUE TITLE
[Severe Bug] Oh no speed hack

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#877]
_Originally written by **Anatze | 76561198302304278**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Ancestral_Plains

*Expected Results:* speed hack should not work in bob
*Actual Results:* this hack works
*Replication:* for example you can use Cheat Engine and set speed of the game to x10, your speed, stamina/ability heal going to be hella fast

**Comment by Trip-Trap** [comment]
Fix for this was tested
