### ISSUE TITLE
[Severe Bug] Hits don't land

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#879]
_Originally written by **RoT | Holly | 76561199003520429**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand:         Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 660
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Sai at snowy** 
Map: Rival_Shores

Hits do not land, for this i am a sai trying to hit a rex, both sides dont land hits. We are at the top of waterfall at snowy, but it happens at other places too, and with all dinos. 
Location: X=-218674.359 Y=-11629.382 Z=20339.145

**Comment by Trip-Trap** [comment]
Server lag issue
