### ISSUE TITLE
[Bug] eggs after server crash

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#88]
_Originally written by **Serenity | 76561198130229125**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **megalo ** 
Map: Rival_Shores

hey, so in 2 cases we had eggs that duplicated after the server crashing and they are out of the group after we come back in

**Comment by Thy-Vipe** [comment]
Might be tied to #92

**Comment by Predatoria** [comment]
This has been fixed on tester.  Marking this as fixed and closing.
