### ISSUE TITLE
[Major Bug] Ground attacked me

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#880]
_Originally written by **Strelka | 76561198138109371**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 4600
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **a Pteradactly ** 
Map: Ancestral_Plains

While flying down a ledge to go get water I was landing in slowly when all the sudden the game glitched me into the ground and killed me. I was coming in as slow as possible and only 3 feet from the ground when this happened. It happened int the spiral cave of DOOM. This cave is EVIL. :(

**Comment by Predatoria** [comment]
Dunno what happened, but I know we won't be able to reproduce this
