### ISSUE TITLE
[Bug] climb animation 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#882]
_Originally written by **-PDS- D3adlyR3aper | 76561198880415303**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand:         Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: AMD Radeon R7 250 Series
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

*Expected Results:* 
*Actual Results:* 
*Replication:* 

velo stuck on climb animation

**Comment by Trip-Trap** [comment]
#121
