### ISSUE TITLE
[Bug] my meg doesnt jump like it should

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#884]
_Originally written by **cobra | 76561198345200062**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2070 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **meg** 
Map: Ancestral_Plains

i logged in today and my wasnt jumping on my meg wasnt working liek it normally does it wont let me jump nearly as high as i was last night

**Comment by Trip-Trap** [comment]
#901
