### ISSUE TITLE
[Bug] Egg Name Bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#885]
_Originally written by **Sechssarius | 76561198068405409**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Lay it down in the nest** 
Map: Ancestral_Plains

Egg Name Tag is gone but egg is still there.

**Comment by Trip-Trap** [comment]
#873
