### ISSUE TITLE
[Major Bug] Hitbox

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#886]
_Originally written by **SlidingTBebble | 76561198847106602**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2070 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Elasmo** 
Map: Ancestral_Plains

*Expected Results:* mosa dart to deal damage upon contact of the target
*Actual Results:* mosa dart dealt damage with dart a mosa length away from me (a rough 1.0 mosa)

i have video proof of it but i dont think i can send it via report a bug in game

**Comment by Trip-Trap** [comment]
Likely due to server lag. Closing this issue.
