### ISSUE TITLE
[Bug] Fish and eggs increase in size

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#8908]
_Originally written by **Tally | 76561198100362619**_
Game Version: 1.1.1239

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **a dino** 
Map: Rival_Shores

Eggs and fish increase in size as a player grows.

**Comment by cleafspear** [comment]
this is a known issue. per @Predatoria its too funny to fix. and honestly. i agree.
