### ISSUE TITLE
[Bug] Cannot fill in ory burrow slot

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#892]
_Originally written by **AtomixSpark | 76561198132359190**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Ory** 
Map: Rival_Shores

*Expected Results:* filling in an ory burrow 
*Actual Results:* "a creature is too close" error despite nobody being near me.
*Replication:* seemingly random but persists between attempts. Close to the burrow entrance if that helps any.

**Comment by Predatoria** [comment]
I know I won't be able to find and reproduce this without more info
