### ISSUE TITLE
[Bug] Saved Skin doesn't work

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#894]
_Originally written by **Bean | 76561199029194131**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Skin selector / Respawning** 
Map: Rival_Shores

Hello!

I've noticed that my "save skin" function doesn't work. I can save skins while playing but once I delete that dino and respawn it doesn't show up in the "saved skins"-list anymore (the list is always empty after respawning).

This happens on every kind of dino.

I hope this is helpful. :)

Best regards,
Bean

**Comment by Trip-Trap** [comment]
#461
