### ISSUE TITLE
[Bug] Egg icons disappering

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#895]
_Originally written by **LuminecentEyes???(2 | 76561199080193628**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

Once eggs are layed the egg icon goes away, sometimes you can see it for a little bit. But it goes away soon after appering.

**Comment by Trip-Trap** [comment]
#873
