### ISSUE TITLE
[Bug] Apa and ory burrows

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#896]
_Originally written by **Reddragon | 76561198267003759**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD Ryzen 7 3700X 8-Core Processor             
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Rival_Shores

when double tapping e over a a dryo burrow apa and move and eat

**Comment by Trip-Trap** [comment]
#779
