### ISSUE TITLE
[Bug] FPS bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#897]
_Originally written by **Darkest | 76561198974784973**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 3GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

So I've been super laggy randomly, as soon as I turn off hud its steady 80

**Comment by Predatoria** [comment]
This has been fixed on tester
