### ISSUE TITLE
[Bug] Meg Jump Inconsistencies

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#901]
_Originally written by **SaltyTreatMan | 76561197987731592**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 970
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

My 1.0ish nested Meg with 5/3 jump skill often won't jump as high as it should be able to.  It seems that roughly every other jump behaves as a 0/3 jump.

I've logged and relogged, switched to other dinos (who jump just fine), even switched my keyboard, and the meg will still only do it's 'proper' jump about 50% of the time.

**Comment by tinystarpaws** [comment]
Cannot reproduce. Using the new global admin command to set inherits, I tested both 5/3 powerful legs and 0/3 powerful legs jumps, and there was a large difference between the two consistently. I did about 10 jumps with each setup.
