### ISSUE TITLE
[Severe Bug] ghjkl;

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#9055]
_Originally written by **Onyx The Idiot | 76561198978618562**_
Game Version: 1.1.1239

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

vbnjkl;'
4
';lkjhvc

**Comment by cleafspear** [comment]
spam
