### ISSUE TITLE
[Quality of life] Удалите свою игрк нахуй

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#906]
_Originally written by **! ???H??? Psycho Jenny | 76561198377931910**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

Меня заебала ваша игра вы чмошники сдохните от спида пжлст
Location: X=-207150.422 Y=26042.113 Z=22517.334

**Comment by Trip-Trap** [comment]
>:V dont even bother translating. Salty review
