### ISSUE TITLE
[Bug] slap/knockback glitch on baby apas. 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#908]
_Originally written by **Miss.Wolfie??? [alt] | 76561199087841371**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Le Hide-Out** 
Map: Rival_Shores

If a baby apa is picked up and slaps right before being picked up or something like that... it tend to make the baby do dmg to others with its tail without attacking. Along with knockbacn by the tail too.. I thought this was fixed until it started doing it again.

**Comment by Trip-Trap** [comment]
Will report a reproduction for this.
