### ISSUE TITLE
[Bug] Flower Gathering Animation bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#91]
_Originally written by **Colonel_Relish | 76561198053464420**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: AMD Ryzen 5 1600 Six-Core Processor            
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **T-Rex** 
Map: Rival_Shores

While gathering comfort flowers on my T-rex, an animation loop of feeding began, causing my character to appear as though he was sliding along the ground. After approximately one minute, an incredibly loud noise began to feedback through my headphones.

**Comment by Predatoria** [comment]
@Peter22FIN pushed a fix for this.  It's pending confirmation on tester.
