### ISSUE TITLE
[Bug] achivement glitch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#917]
_Originally written by **Nocturnal_Star | 76561198973355572**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3500 6-Core Processor              
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **as a megalo** 
Map: Rival_Shores

after drinking water from same source says u have found a neew source every time i drink

**Comment by Trip-Trap** [comment]
maybe didnt move/switched water source. not enough info, cant reproduce
