### ISSUE TITLE
[Major Bug] No Death Slot

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#92]
_Originally written by **Ra'va | 76561198039772275**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Elasmo** 
Map: Rival_Shores

Got a bad egg when i was nested so parents offerd new egg. they kill me so that i can take the new egg to try again and i noticed that there was no death slot, the game acted as if my dino never existed.

**Comment by Thy-Vipe** [comment]
Okay we need reproduction on this. They might be onto something.

**Comment by Thy-Vipe** [comment]
Should be fixed - closing until further notice.
