### ISSUE TITLE
[Bug] Crystals change color after being picked up and replaced using ory's excavation ability

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#9243]
_Originally written by **Cleitedubh | 76561198293999459**_
Game Version: 1.1.1285

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1650
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Oryctodromeus** 
Map: Ancestral_Plains

Picked up an orange crystal in a burrow (crystal cluster model, not individual crystal model) and placed it somewhere else, and instead of being the orange crystal cluster it became the green individual cluster model. Doesn't happen 100% of the time, seems to be completely random. I noticed that orange crystals that were named SM_LProp_Crystals_01_Green would turn green after being placed but orange crystals that were named SM_LProp_Crystals_03_Green would remain orange regardless of how often they were picked up and put back down.

**Comment by cleafspear** [comment]
this is a known issue with how crystal colors are determined. this is not a bug
