### ISSUE TITLE
[Bug] loeing saved skins 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#938]
_Originally written by **production3269 | 76561198949870308**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 3GB
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **the game ** 
Map: Ancestral_Plains

well i was playing the game and every time i play and i dont feel like makeing a new skin i go to my saved skins and i dont have any there i hope you can fix this and take your time on it if you like im not trying to rush you on it :3

**Comment by Trip-Trap** [comment]
FIXED
