### ISSUE TITLE
[Quality of life] Waterfall loud as nado.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#94]
_Originally written by **Eve Stargaze | 76561198137104876**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand:        Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 960
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

Waterfall sounds are as loud as nados from about two apatos length away turning down all the sounds does nothing except maybe a bit of the game volume but then you dont hear any dino sounds/footsteps.

**Comment by Thy-Vipe** [comment]
lowered the sound - they are however properly attached to "environment" so the setting might not ever apply or get overridden anyhow..
