### ISSUE TITLE
[Bug] Gores don't drop if a player's killed in deep ocean

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#942]
_Originally written by **Jxck | 76561198799229491**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

So I'm playing on RS as a Krono and I saw a mosa, I killed the thing but it went above this area of the ocean that's super deep, it's not off the map, but near the big crystal surrounded by seaweed. I hope that this can get fixed because it can get really annoying killing something when you're very hungry then ending up with just a kill. Here's the video I have of this happeneing: https://youtu.be/uGCvlgqHFqo

**Comment by tinystarpaws** [comment]
Has been fixed on tester. Bodies now float in the ocean where they were killed.
