### ISSUE TITLE
[Quality of life] rock without collision

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#944]
_Originally written by **SixtyWhy | 76561198984222361**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  
Vendor: AuthenticAMD
GPU Brand: AMD Radeon(TM) Vega 8 Graphics
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

this rock has inncorrect colliosion, thus dinos can mesh fully inside and grow
Location: X=-8367.894 Y=-112075.398 Z=2846.992

**Comment by Predatoria** [comment]
I replaced those rocks with another with better collision in a different report.
