### ISSUE TITLE
[Major Bug] Losing Growth with restart

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#96]
_Originally written by **-MM- Daddy Draco | 76561198101239550**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 4600
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Meg** 
Map: Ancestral_Plains

i dont know how it happened, i safe logged almost 20 minutes before a restart and have been reverted from 1.0 to .9

**Comment by Thy-Vipe** [comment]
Should be fixed - closing until further notice.
