### ISSUE TITLE
[Bug] S Grade not registering

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#960]
_Originally written by **Nekrothaftis | 76561198866737534**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD Ryzen 3 1200 Quad-Core Processor           
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Ancestral_Plains

we have S great with my friend apa but i cant do damage to him and he can do damage to me.... im apa too..

**Comment by tinystarpaws** [comment]
Cannot reproduce, not enough information.
