### ISSUE TITLE
[Severe Bug] Severe bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#962]
_Originally written by **ArrasandoESP | 76561198318959208**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

You can leave the map in this location, I have a screenshot.

Location: X=54588.160 Y=221869.188 Z=3961.591

**Comment by Trip-Trap** [comment]
Assume is fixed, cant find any hole
