### ISSUE TITLE
[Severe Bug] para performance issues

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#971]
_Originally written by **Madmax | 76561198363069430**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics Family
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Not sure if it start happening when i spawn, but i can't damage other creatures as para, game said i do but other dinos get no damage (i can get damage from they)** 
Map: Rival_Shores

Probably it started when i spawn, don't know how to fix it

**Comment by Trip-Trap** [comment]
Server lag
