### ISSUE TITLE
[Bug] Ptera Skin Pattern Reset

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#977]
_Originally written by **Sawbus | 76561198025190854**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Official 1: Ptera** 
Map: Forest_Island

I am on Official 1 playing a ptera. I am simply flying around trying to change my skin, however every single time after leaving the character screen my colors revert back to what they were before.

**Comment by Predatoria** [comment]
This is probably fixed after Vipe messed with skin saving and all that this patch
