### ISSUE TITLE
[Bug] its laggy

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#9805]
_Originally written by **Chungus | 76561199199111602**_
Game Version: 1.1.1311

*===== System Specs =====
CPU Brand: Intel(R) Pentium(R) Silver J5040 CPU @ 2.00GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 605
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **in maps** 
Map: Forest_Island

please fix this lagg i just got this game and its so laggy when when i started it when i bought it

**Comment by cleafspear** [comment]
this issue cannot be resolved due to the player having WELL below min spec on hardware.
