### ISSUE TITLE
[Bug] Talent Dc glitch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#9825]
_Originally written by **Patrick Hyo San | 76561199067543995**_
Game Version: 1.1.1320

*===== System Specs =====
CPU Brand:        Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: AMD Radeon RX 5600 XT
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **i was rex i try to use my point in weatehr it Dc me 4 times ** 
Map: Rival_Shores

whne i hold Shift and click or just click on weather resistence it just dissconnects me it happend alot

**Comment by cleafspear** [comment]
resolved with the latest patch
