### ISSUE TITLE
[Severe Bug] bleed animation

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#9829]
_Originally written by **Triton | 76561197969239706**_
Game Version: 1.1.1320

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

please correct the bleed animation 
it is still shows after being healed. The animation continues until the player logs out,

**Comment by cleafspear** [comment]
this is resolved
