### ISSUE TITLE
[Severe Bug] Hole in Mesh

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#983]
_Originally written by **Stimky | 76561198219851059**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2060 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Velociraptor** 
Map: Rival_Shores

There is a hole in the world mesh, that allows the player to gain access to the underside of the map
Location: X=120724.234 Y=88531.133 Z=5484.792

**Comment by tinystarpaws** [comment]
The given coordinates aren't correct, but QA Tester BlueJays/Pizza Tycoon was able to find and provide the proper location.
![velo map seam](https://user-images.githubusercontent.com/38923098/111083431-fb178f80-84e3-11eb-8899-8afe8458c6c3.png)

**Comment by Predatoria** [comment]
Filled hole with rock
