### ISSUE TITLE
[Major Bug] Waterfall trap

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#991]
_Originally written by **Loaf of Pear Bread | 76561198809334506**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

At the top on the snowy moutain water fall there is a small space that dions can fall in to but get out.

**Comment by Predatoria** [comment]
Found and fixed
